# 20 data cleaning practice questions

# Basic Exploration & Missing Values

In [2]:
# Basic Exploration & Missing Values
# 1. How many missing values are there in each column? Which column has the highest
# number of missing values?
# 2. What percentage of rows have at least one missing value?
# 3. Drop all rows that have more than 3 missing values. How many rows remain?



import pandas as pd 
import matplotlib as plt
import numpy as np
import seaborn as sns

df = pd.read_csv("C:\\Users\\Shree\\Downloads\\Customer_datasets.csv")
df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,False
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,False
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,True
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,True
...,...,...,...,...,...,...,...,...,...,...,...
2025,1131,Customer_1131,74,46818.31,2018-08-09,Marketing,46.8,user1130@outlook.com,Phoenix,Other,False
2026,1295,Customer_1295,72,64255.45,2017-08-23,Support,Excellent,user1294@outlook.com,San Jose,Male,False
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,True
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,False
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,False

In [7]:
print(df.isnull().sum(), "\nHighest:", df.isnull().sum().idxmax())

Customer_ID            0
Name                 145
Age                   84
Salary                97
Join_Date            254
Department            51
Performance_Score     39
Email                 49
City                  43
Gender                34
Is_Active             25
dtype: int64
Highest: Join_Date

In [11]:
print(df.isnull().any(axis=1).mean() * 100)

34.87684729064039

In [20]:
df.dropna(thresh=df.shape[1] - 3)

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,False
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,False
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,True
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,True
...,...,...,...,...,...,...,...,...,...,...,...
2025,1131,Customer_1131,74,46818.31,2018-08-09,Marketing,46.8,user1130@outlook.com,Phoenix,Other,False
2026,1295,Customer_1295,72,64255.45,2017-08-23,Support,Excellent,user1294@outlook.com,San Jose,Male,False
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,True
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,False
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,False

# Duplicates

In [18]:
# 4. How many exact duplicate rows are present in the dataset?

df.duplicated().sum()

np.int64(30)

In [22]:
# 5. How many duplicate Customer_IDs are there? Keep only the first occurrence of each
# Customer_ID.


df["Customer_ID"] = df["Customer_ID"].duplicated().sum()
df["Customer_ID"]

0       2029
1       2029
2       2029
3       2029
4       2029
        ...
2025    2029
2026    2029
2027    2029
2028    2029
2029    2029
Name: Customer_ID, Length: 2030, dtype: int64

# Age Column

In [24]:
# 6. Convert the Age column to numeric. How many values could not be converted
# (became NaN)?

df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")

df["Age"] = df["Age"].isna().sum()
df["Age"]

0       0
1       0
2       0
3       0
4       0
       ..
2025    0
2026    0
2027    0
2028    0
2029    0
Name: Age, Length: 2030, dtype: int64

In [25]:
# 7. After converting Age to numeric, identify and remove outliers using the IQR method.
# How many outliers were removed?


Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.25)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 *IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["Age"] < lower_bound ) | (df["Age"] > upper_bound)]

print(outliers)
print(lower_bound)
print(upper_bound)

Empty DataFrame
Columns: [Customer_ID, Name, Age, Salary, Join_Date, Department, Performance_Score, Email, City, Gender, Is_Active]
Index: []
0.0
0.0

In [27]:
# 8. Replace remaining missing values in Age with the median age.

median_age = df["Age"].median()

df["Age"].fillna(median_age)

0       0
1       0
2       0
3       0
4       0
       ..
2025    0
2026    0
2027    0
2028    0
2029    0
Name: Age, Length: 2030, dtype: int64

# Salary Column

In [29]:
# 9. Clean the Salary column: remove currency symbols ($), commas, and convert
# everything possible to numeric. How many values remained non-numeric?

df["Salary"] = df["Salary"].replace({"$":"",
                                     ",":""})
df["Salary"]

0       29664.12
1       47373.17
2       63380.36
3       56746.57
4       61654.21
          ...
2025    46818.31
2026    64255.45
2027         NaN
2028    46179.42
2029    58869.43
Name: Salary, Length: 2030, dtype: object

In [33]:
df["Salary"] = pd.to_numeric(df["Salary"],errors ="coerce")
df["Salary"]

0       29664.12
1       47373.17
2       63380.36
3       56746.57
4       61654.21
          ...
2025    46818.31
2026    64255.45
2027         NaN
2028    46179.42
2029    58869.43
Name: Salary, Length: 2030, dtype: float64

In [34]:
# 10. After cleaning, find the mean and median salary. Which one is more affected by
# outliers?

df["Salary"].median()

55625.34

# Date Column

In [36]:
# 11. Convert the Join_Date column to proper datetime format. How many dates failed to
# parse?


df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Join_Date"]

0      2022-06-14
1             NaT
2             NaT
3             NaT
4      2019-03-12
          ...
2025   2018-08-09
2026   2017-08-23
2027   2019-10-28
2028   2020-01-06
2029   2020-01-17
Name: Join_Date, Length: 2030, dtype: datetime64[ns]

In [41]:
# 12. Extract the year from the cleaned Join_Date. What is the most common joining year?

df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Join_Date"] = df["Join_Date"].dt.year.mode()[0]
df["Join_Date"]

0       1970
1       1970
2       1970
3       1970
4       1970
        ...
2025    1970
2026    1970
2027    1970
2028    1970
2029    1970
Name: Join_Date, Length: 2030, dtype: int32

# Categorical Columns (Inconsistencies)

In [42]:
# 13. Standardize the Department column (fix casing, trim spaces, fix common typos like
# “Sale” → “Sales”, “Financ” → “Finance”, etc.). How many unique departments remain
# after cleaning?

df["Department"] = df["Department"].str.strip().str.title()
df["Department"] = df["Department"].replace({"Sale":"Sales",
                                             "Financ":"Finance",
                                             "Hr":"HR"})
df["Department"]

0               HR
1        Marketing
2       Operations
3               It
4          Finance
           ...
2025     Marketing
2026       Support
2027       Finance
2028            It
2029       Finance
Name: Department, Length: 2030, dtype: object

In [46]:
# 14. Clean the City column (standardize names, fix “Los Angles” → “Los Angeles”, “NY” →
# “New York”, “Philly” → “Philadelphia”, etc.). List the final unique cities.

df["City"] = df["City"].replace({"Los Angles":"Los Angeles",
                                 "NY":"New York",
                                 "Philly":"Philandelphia"})
df["City"] = df["City"].nunique()
df["City"]

0       1
1       1
2       1
3       1
4       1
       ..
2025    1
2026    1
2027    1
2028    1
2029    1
Name: City, Length: 2030, dtype: int64

In [52]:
# 15. Standardize the Gender column so it only contains “Male”, “Female”, and “Other”.
# How many records were changed?

df["Gender"] = df["Gender"].replace({
    "male": "Male", "m": "Male",
    "female": "Female", "f": "Female",
    "other": "Other", "o": "Other"
})
changed_count = (df["Gender"].isin(["Male","Female","Other"]) == False).sum()
changed_count

np.int64(2030)

# Performance_Score & Is_Active

In [54]:
# 16. Convert Performance_Score to numeric. Replace non-numeric values with NaN, then
# fill missing scores with the mean.

df["Performance_Score"] = pd.to_numeric(df["Performance_Score"],errors = "coerce")
df["Performance_Score"]

0       69.1
1        1.9
2       78.2
3       85.8
4       82.5
        ...
2025    46.8
2026     NaN
2027    43.7
2028    17.5
2029    47.4
Name: Performance_Score, Length: 2030, dtype: float64

In [57]:
df["Performance_Score"] = df["Performance_Score"].mean()
df["Performance_Score"]

0       51.67763
1       51.67763
2       51.67763
3       51.67763
4       51.67763
          ...
2025    51.67763
2026    51.67763
2027    51.67763
2028    51.67763
2029    51.67763
Name: Performance_Score, Length: 2030, dtype: float64

In [58]:
# 17. Clean the Is_Active column so it becomes a proper boolean (True/False). Map values
# like “Yes”, “Y”, “1”, “Active”, “true” → True and “No”, “N”, “0”, “Inactive”, “false” →
# False.

df["Is_Active"] = df["Is_Active"].replace({
    "yes": True, "y": True, "1": True, "active": True, "true": True,
    "no": False, "n": False, "0": False, "inactive": False, "false": False})
df["Is_Active"]

0       False
1       False
2         NaN
3        True
4        True
        ...
2025    False
2026    False
2027     True
2028    False
2029    False
Name: Is_Active, Length: 2030, dtype: object

# Email & Name

In [60]:
# 18. Flag invalid email addresses (those that do not contain “@” or have incomplete
# domains). How many invalid emails are there?

df["Email"] = df["Email"].astype(str).str.strip().str.contains("@") == False
df["Email"]

0       True
1       True
2       True
3       True
4       True
        ...
2025    True
2026    True
2027    True
2028    True
2029    True
Name: Email, Length: 2030, dtype: bool

In [62]:
# 19. Clean the Name column: replace empty strings, “N/A”, and “Unknown” with NaN.
# How many names are still missing after this step?

df["Name"] = df["Name"].replace(["", "N/A", "Unknown"], pd.NA)
df["Name"] = df["Name"].isna().sum()
df["Name"]

0       0
1       0
2       0
3       0
4       0
       ..
2025    0
2026    0
2027    0
2028    0
2029    0
Name: Name, Length: 2030, dtype: int64

# Final Challenge

In [65]:
# 20. Perform a complete data cleaning pipeline on the entire dataset and save the
# cleaned version as cleaned_dataset.csv. Report the final shape of the cleaned dataset
# and briefly describe the main cleaning steps you applied.

df = pd.read_csv("C:\\Users\\Shree\\Downloads\\Customer_datasets.csv")

df = df.drop_duplicates()

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df = df.dropna(thresh=df.shape[1]-3)

df.to_csv("cleaned_dataset.csv", index=False)

print("Final shape:", df.shape)

df

Final shape: (2000, 11)

,customer_id,name,age,salary,join_date,department,performance_score,email,city,gender,is_active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,False
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,False
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,True
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,True
...,...,...,...,...,...,...,...,...,...,...,...
2024,1096,Customer_1096,74,43331.22,2016-09-10 00:00:00,Finance,92.2,user1095@gmail.com,San Antonio,Male,True
2025,1131,Customer_1131,74,46818.31,2018-08-09,Marketing,46.8,user1130@outlook.com,Phoenix,Other,False
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,True
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,False
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,False