# Data Cleaning — 20 Questions

In [1]:
# 1. Column Names
# Display all column names. Identify columns having leading/trailing spaces and
# rename all columns into a consistent snake_case format.

import pandas as pd

df = pd.read_csv("C:\\Users\\Shree\\Downloads\\matplotlib_messy_sales_2000.csv")
df

,Customer ID,Order Date,City,Product Category,Customer Segment,Gender,Sales Channel,Age,Units Sold,Unit Price,Discount %,Customer Rating,Is Active,Returned,Payment Method,Gross Sales,Discount Amount,Revenue,Cost,Profit
0,CUST00594,2025-05-05 00:00:00,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14
1,CUST01103,2025-10-22 00:00:00,Mumbai,Clothing,Premium,Female,Corporate,38.0,5,16789.55,10.59,4.3,1,0,Cash,83947.75,8890.07,75057.68,61426.31,13631.37
2,CUST00690,2025-04-24 00:00:00,Delhi,Home & Kitchen,Regular,Male,Retail,65.0,2,24579.97,36.22,4.5,1,0,Debit Card,49159.94,17805.73,31354.21,24948.21,6406.00
3,CUST00215,2025-05-17 00:00:00,Chennai,Electronics,Regular,Male,Corporate,34.0,9,6240.13,20.44,3.9,1,0,Net Banking,56161.17,11479.34,NaN,26470.33,18211.50
4,CUST01270,2025-08-30 00:00:00,Delhi,Clothing,Budget,Female,Corporate,41.0,1,23491.23,10.48,3.7,1,0,Net Banking,23491.23,2461.88,21029.35,12312.38,8716.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CUST00043,2025-12-17 00:00:00,Pune,Sports,Premium,Male,Retail,24.0,10,9181.27,18.05,3.7,1,0,UPI,91812.70,16572.19,75240.51,39994.75,35245.76
2016,CUST00602,2025-12-22 00:00:00,Pune,Sports,Regular,Female,Retail,44.0,9,6947.94,32.93,1.5,1,0,Cash,62531.46,20591.61,41939.85,33246.33,8693.52
2017,CUST01708,2025-05-28 00:00:00,Hyderabad,Home & Kitchen,Premium,Male,Retail,56.0,5,5393.37,25.19,3.4,1,0,UPI,26966.85,6792.95,20173.90,13654.93,6518.97
2018,CUST00614,2025-08-27 00:00:00,Chennai,Sports,Premium,Male,Online,41.0,7,10803.59,0.5,5.0,1,0,UPI,75625.13,378.13,75247.00,46822.20,28424.80
2019,CUST01948,2025-12-23 00:00:00,Pune,Beauty,Regular,Female,Retail,68.0,12,18336.56,23.29,4.7,1,0,Credit Card,220038.72,51247.02,168791.70,107140.44,61651.26

In [2]:
df.columns

Index(['Customer ID', ' Order Date ', 'City', 'Product Category',
       'Customer Segment', 'Gender', 'Sales Channel', 'Age', 'Units Sold',
       'Unit Price', 'Discount %', 'Customer Rating', 'Is Active', 'Returned',
       'Payment Method', 'Gross Sales', 'Discount Amount', 'Revenue', 'Cost',
       'Profit'],
      dtype='object')

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['customer_id', 'order_date', 'city', 'product_category',
       'customer_segment', 'gender', 'sales_channel', 'age', 'units_sold',
       'unit_price', 'discount_%', 'customer_rating', 'is_active', 'returned',
       'payment_method', 'gross_sales', 'discount_amount', 'revenue', 'cost',
       'profit'],
      dtype='object')

In [4]:
# 2. Duplicate Records
# Find the number of duplicate rows. Remove the duplicate records and verify that no
# duplicates remain.

df.duplicated().sum()

np.int64(20)

In [5]:
df.drop_duplicates()

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05 00:00:00,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14
1,CUST01103,2025-10-22 00:00:00,Mumbai,Clothing,Premium,Female,Corporate,38.0,5,16789.55,10.59,4.3,1,0,Cash,83947.75,8890.07,75057.68,61426.31,13631.37
2,CUST00690,2025-04-24 00:00:00,Delhi,Home & Kitchen,Regular,Male,Retail,65.0,2,24579.97,36.22,4.5,1,0,Debit Card,49159.94,17805.73,31354.21,24948.21,6406.00
3,CUST00215,2025-05-17 00:00:00,Chennai,Electronics,Regular,Male,Corporate,34.0,9,6240.13,20.44,3.9,1,0,Net Banking,56161.17,11479.34,NaN,26470.33,18211.50
4,CUST01270,2025-08-30 00:00:00,Delhi,Clothing,Budget,Female,Corporate,41.0,1,23491.23,10.48,3.7,1,0,Net Banking,23491.23,2461.88,21029.35,12312.38,8716.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CUST00043,2025-12-17 00:00:00,Pune,Sports,Premium,Male,Retail,24.0,10,9181.27,18.05,3.7,1,0,UPI,91812.70,16572.19,75240.51,39994.75,35245.76
2016,CUST00602,2025-12-22 00:00:00,Pune,Sports,Regular,Female,Retail,44.0,9,6947.94,32.93,1.5,1,0,Cash,62531.46,20591.61,41939.85,33246.33,8693.52
2017,CUST01708,2025-05-28 00:00:00,Hyderabad,Home & Kitchen,Premium,Male,Retail,56.0,5,5393.37,25.19,3.4,1,0,UPI,26966.85,6792.95,20173.90,13654.93,6518.97
2018,CUST00614,2025-08-27 00:00:00,Chennai,Sports,Premium,Male,Online,41.0,7,10803.59,0.5,5.0,1,0,UPI,75625.13,378.13,75247.00,46822.20,28424.80
2019,CUST01948,2025-12-23 00:00:00,Pune,Beauty,Regular,Female,Retail,68.0,12,18336.56,23.29,4.7,1,0,Credit Card,220038.72,51247.02,168791.70,107140.44,61651.26

In [6]:
# 3. Missing Values
# Display the missing-value count and missing-value percentage for every column.

missing_value = df.isnull().sum()
missing_value

customer_id          0
order_date           4
city                25
product_category    25
customer_segment     0
gender               0
sales_channel        0
age                 28
units_sold           4
unit_price          25
discount_%          28
customer_rating     25
is_active            0
returned             0
payment_method      25
gross_sales          0
discount_amount      0
revenue             26
cost                 0
profit               0
dtype: int64

In [7]:
missing_per = missing_value / len(df)*100
missing_per

customer_id         0.000000
order_date          0.198020
city                1.237624
product_category    1.237624
customer_segment    0.000000
gender              0.000000
sales_channel       0.000000
age                 1.386139
units_sold          0.198020
unit_price          1.237624
discount_%          1.386139
customer_rating     1.237624
is_active           0.000000
returned            0.000000
payment_method      1.237624
gross_sales         0.000000
discount_amount     0.000000
revenue             1.287129
cost                0.000000
profit              0.000000
dtype: float64

In [8]:
# 4. Missing Categorical Values
# Handle missing values in city, product_category, and payment_method using an
# appropriate strategy.

for col in ["city", "product_category", "payment_method"]:
   df[col].fillna(df[col].mode()[0])

print(df[["city", "product_category", "payment_method"]].isna().sum())

city                25
product_category    25
payment_method      25
dtype: int64

In [9]:
# 5. Missing Numerical Values
# Handle missing values in age, unit_price, discount_pct, customer_rating, and
# revenue. Explain why you selected mean, median, or another method.


df.fillna(df.median(numeric_only = True))

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05 00:00:00,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14
1,CUST01103,2025-10-22 00:00:00,Mumbai,Clothing,Premium,Female,Corporate,38.0,5,16789.55,10.59,4.3,1,0,Cash,83947.75,8890.07,75057.68,61426.31,13631.37
2,CUST00690,2025-04-24 00:00:00,Delhi,Home & Kitchen,Regular,Male,Retail,65.0,2,24579.97,36.22,4.5,1,0,Debit Card,49159.94,17805.73,31354.21,24948.21,6406.00
3,CUST00215,2025-05-17 00:00:00,Chennai,Electronics,Regular,Male,Corporate,34.0,9,6240.13,20.44,3.9,1,0,Net Banking,56161.17,11479.34,69394.97,26470.33,18211.50
4,CUST01270,2025-08-30 00:00:00,Delhi,Clothing,Budget,Female,Corporate,41.0,1,23491.23,10.48,3.7,1,0,Net Banking,23491.23,2461.88,21029.35,12312.38,8716.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CUST00043,2025-12-17 00:00:00,Pune,Sports,Premium,Male,Retail,24.0,10,9181.27,18.05,3.7,1,0,UPI,91812.70,16572.19,75240.51,39994.75,35245.76
2016,CUST00602,2025-12-22 00:00:00,Pune,Sports,Regular,Female,Retail,44.0,9,6947.94,32.93,1.5,1,0,Cash,62531.46,20591.61,41939.85,33246.33,8693.52
2017,CUST01708,2025-05-28 00:00:00,Hyderabad,Home & Kitchen,Premium,Male,Retail,56.0,5,5393.37,25.19,3.4,1,0,UPI,26966.85,6792.95,20173.90,13654.93,6518.97
2018,CUST00614,2025-08-27 00:00:00,Chennai,Sports,Premium,Male,Online,41.0,7,10803.59,0.5,5.0,1,0,UPI,75625.13,378.13,75247.00,46822.20,28424.80
2019,CUST01948,2025-12-23 00:00:00,Pune,Beauty,Regular,Female,Retail,68.0,12,18336.56,23.29,4.7,1,0,Credit Card,220038.72,51247.02,168791.70,107140.44,61651.26

In [10]:
print(df[['age', 'unit_price', 'discount_amount',
          'customer_rating', 'revenue']].isnull().sum())

age                28
unit_price         25
discount_amount     0
customer_rating    25
revenue            26
dtype: int64

In [11]:
df.columns

Index(['customer_id', 'order_date', 'city', 'product_category',
       'customer_segment', 'gender', 'sales_channel', 'age', 'units_sold',
       'unit_price', 'discount_%', 'customer_rating', 'is_active', 'returned',
       'payment_method', 'gross_sales', 'discount_amount', 'revenue', 'cost',
       'profit'],
      dtype='object')

In [12]:
print(df[['age', 'unit_price', 'discount_amount',
          'customer_rating', 'revenue']].isnull().sum())

age                28
unit_price         25
discount_amount     0
customer_rating    25
revenue            26
dtype: int64

In [13]:
# 6. Date Cleaning
# Convert order_date into a proper datetime format. Identify invalid date values and
# handle them appropriately.

df["order_date"] = pd.to_datetime(df["order_date"],errors = "coerce",dayfirst=True)
df["order_date"]

0      2025-05-05
1             NaT
2             NaT
3             NaT
4             NaT
          ...
2015          NaT
2016          NaT
2017          NaT
2018          NaT
2019          NaT
Name: order_date, Length: 2020, dtype: datetime64[ns]

In [14]:
# 7. Age Cleaning
# The age column contains values such as 25 years, 30 yrs, 45Y, and N/A. Extract the
# numerical age and convert the column into a numeric datatype.

df["age"] = pd.to_numeric(df["age"],errors = "coerce")
df["age"]

0       36.0
1       38.0
2       65.0
3       34.0
4       41.0
        ...
2015    24.0
2016    44.0
2017    56.0
2018    41.0
2019    68.0
Name: age, Length: 2020, dtype: float64

In [17]:
# 8. Age Outliers
# Identify unrealistic ages such as 120, 150, and 200. Detect them using the IQR
# method and handle them appropriately.

# 8. Age Outliers
# Identify unrealistic ages using the IQR method

import numpy as np

# Convert age column to numeric
df['age'] = pd.to_numeric(df['age'], errors='coerce')

Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR



age_outliers = df[
    (df['age'] < lower_bound) |
    (df['age'] > upper_bound)
]

print("Age outliers:")
print(age_outliers['age'])

Age outliers:
193     150.0
256     120.0
323     120.0
329     200.0
467     120.0
534     200.0
647     120.0
777     150.0
869     150.0
991     150.0
1023    120.0
1532    150.0
1731    120.0
2000    120.0
Name: age, dtype: float64

In [18]:
# 9. Unit Price Cleaning
# The unit_price column contains values such as ₹15000, $20000, 25000 INR, and 10k.
# Convert all valid values into a single numeric format.


import re
import numpy as np

def clean_price(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().strip()

    if 'k' in value:
        number = re.findall(r'[\d.]+', value)
        if number:
            return float(number[0]) * 1000

    value = re.sub(r'[₹$]', '', value)
    value = re.sub(r'inr', '', value)
    value = re.sub(r'[^\d.]', '', value)

    if value:
        return float(value)

    return np.nan

df['unit_price'] = df['unit_price'].apply(clean_price)

print(df['unit_price'].head(10))

0     24235.73
1     16789.55
2     24579.97
3      6240.13
4     23491.23
5      1808.30
6     28497.86
7     23023.33
8    250000.00
9     18649.79
Name: unit_price, dtype: float64

In [19]:
# 10. Unit Price Outliers
# Detect extreme unit_price values using the IQR method. Compare the number of
# outliers before and after treatment.

df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')

Q3 = df["unit_price"].quantile(0.25)
Q1 = df["unit_price"].quantile(0.25)

IQR = Q3 - Q1 

lower = Q1 - 1.5 * IQR 
upper = Q3 + 1.5 * IQR

outliers = (df["unit_price"] < lower) | (df["unit_price"] > upper)
print(lower)
print(upper)
print(outliers)

7575.3
7575.3
0       True
1       True
2       True
3       True
4       True
        ...
2015    True
2016    True
2017    True
2018    True
2019    True
Name: unit_price, Length: 2020, dtype: bool

In [20]:
# 11. Units Sold Cleaning
# Clean values such as 5 units, 10 pcs, twenty, N/A, and 3 and convert the column into
# a numeric datatype.

df["units_sold"] = pd.to_numeric(df["units_sold"],errors = "coerce")
df["units_sold"]

0        8.0
1        5.0
2        2.0
3        9.0
4        1.0
        ...
2015    10.0
2016     9.0
2017     5.0
2018     7.0
2019    12.0
Name: units_sold, Length: 2020, dtype: float64

In [21]:
#12. Discount Cleaning
# Clean values such as 10%, 20 percent, 5 %, none, and N/A. Convert the final
# discount_pct column into numeric values between 0 and 100.


df["discount_%"] = df["discount_%"].astype(str)

df["discount_%"] = df["discount_%"].str.replace("%", "", regex=False)
df["discount_%"] = df["discount_%"].str.replace("percent", "", regex=False)

df["discount_%"] = df["discount_%"].str.strip()

df["discount_%"] = pd.to_numeric(df["discount_%"], errors="coerce")

df["discount_%"] = df["discount_%"].fillna(0)
df["discount_%"]

0       22.91
1       10.59
2       36.22
3       20.44
4       10.48
        ...
2015    18.05
2016    32.93
2017    25.19
2018     0.50
2019    23.29
Name: discount_%, Length: 2020, dtype: float64

In [22]:
# 13. Discount Outliers
# Identify invalid discount values such as 75, 90, and 120. Determine which values are
# unrealistic and handle them.

outliers = df[df["discount_%"].isin([75, 90, 120])]
print(outliers)

df.loc[df["discount_%"] > 100, "discount_%"] = np.nan

     customer_id order_date       city product_category customer_segment  \
92     CUST00908        NaT      Delhi      Electronics          Premium
422    CUST01829        NaT      Delhi           Sports          Regular
535    CUST01613        NaT      Delhi           Sports          Regular
567    CUST00305        NaT  Bengaluru           Sports          Regular
884    CUST00421        NaT     Mumbai         Clothing          Regular
1390   CUST00305        NaT  Bengaluru           Sports          Regular
1419   CUST00649        NaT       Pune      Electronics          Premium
1584   CUST00800        NaT       Pune           Sports          Regular
1638   CUST00381        NaT  Bengaluru      Electronics          Regular
1814   CUST00011 2025-07-04      Delhi           Sports          Regular
1994   CUST00803        NaT  Bengaluru           Sports          Regular

      gender sales_channel   age  units_sold  unit_price  discount_%  \
92      Male        Online  22.0        12.0     8647.35       120.0
422   Female        Retail  65.0        13.0    22779.14        75.0
535     Male     Corporate  36.0         2.0     9230.59        90.0
567   Female        Retail  35.0         5.0     8352.68       120.0
884     Male        Online  68.0         4.0    19949.75       120.0
1390  Female        Retail  35.0         5.0     8352.68       120.0
1419  Female     Corporate  26.0         9.0     8275.94       120.0
1584    Male        Retail  21.0         8.0    16929.14        90.0
1638  Female        Retail  53.0         7.0    22605.87        75.0
1814  Female     Corporate  60.0         9.0    26935.82        90.0
1994    Male        Online  67.0         3.0    11194.48       120.0

      customer_rating is_active returned payment_method  gross_sales  \
92                3.5         1        0    Credit Card    103768.20
422               4.4         1        0            UPI    296128.82
535               4.3         1        0           Cash     18461.18
567               1.6         1        0            UPI     41763.40
884               1.7         1        1    Credit Card     79799.00
1390              1.6         1        0            UPI     41763.40
1419              2.8         1        0            UPI     74483.46
1584              2.8         0        0     Debit Card    135433.12
1638              4.5         1        1            UPI    158241.09
1814              2.3         1        1     Debit Card    242422.38
1994              4.9         0        0    Credit Card     33583.44

      discount_amount    revenue       cost    profit
92           17194.39   86573.81   57490.94  29082.87
422          63874.99  232253.83  172759.27  59494.56
535           1894.12   16567.06    8317.16   8249.90
567           9484.47   32278.93   19129.09  13149.84
884          25631.44   54167.56   41541.43  12626.13
1390          9484.47   32278.93   19129.09  13149.84
1419         27372.67   47110.79   32512.94  14597.85
1584          1042.84  134390.28  112130.74  22259.54
1638         25255.28  132985.81   68528.62  64457.19
1814         18908.95  223513.43  169068.64  54444.79
1994          5433.80   28149.64   19955.46   8194.18

In [27]:
# 14. City Standardization
# Standardize inconsistent city values such as:
# o Mumbai
# o mumbai
# o MUMBAI
# o Mumbai
# o Bangalore
# o bangalore
# o Hyderbad

# Create one consistent set of city names.

city_mapping = {
    "mumbai": "Mumbai",
    "bangalore": "Bangalore",
    "hyderbad": "Hyderabad"
}

df["city"] = (
    df["city"]
    .str.strip()
    .str.lower()
    .replace(city_mapping)
    .str.title()
)

print(df["city"].unique())

['Mumbai' 'Delhi' 'Chennai' 'Hyderabad' 'Pune' 'Bengaluru' nan 'Bangalore']

In [30]:
# 15. Product Category Cleaning
# Standardize values such as Electronics, electronics, ELECTRONICS, Home and Kitchen,
# home & kitchen, and Beauty .


df["product_category"] = (
    df["product_category"]
    .str.strip()
    .str.lower()
    .replace({
        "electronics": "Electronics",
        "home and kitchen": "Home & Kitchen",
        "home & kitchen": "Home & Kitchen",
        "beauty": "Beauty"
    })
)
df["product_category"]

0             clothing
1             clothing
2       Home & Kitchen
3          Electronics
4             clothing
             ...
2015            sports
2016            sports
2017    Home & Kitchen
2018            sports
2019            Beauty
Name: product_category, Length: 2020, dtype: object

In [32]:
# 16. Gender Cleaning
# Standardize values such as Male, male, Male, FEMALE, female , M, and F into
# consistent categories.

df["gender"] = df["gender"].str.strip().str.lower()

df["gender"] = df["gender"].replace({"male":"Male",
                                     "m" : "Male",
                                     "female":"Female",
                                     "f":"Female"})
df["gender"]

0         Male
1       Female
2         Male
3         Male
4       Female
         ...
2015      Male
2016    Female
2017      Male
2018      Male
2019    Female
Name: gender, Length: 2020, dtype: object

In [36]:
# 17. Customer Segment Cleaning
# Identify invalid values such as Prem, Reg, VIP, and Unknown. Map valid variations to
# the correct categories and decide how to handle invalid categories.

df["customer_segment"] = (df["customer_segment"].replace({ "Prem":"preminum",
                                                           "Reg":"Regular",
                                                           "vip":"VIP",
                                                           "premium":"Premium"}))
df["customer_segment"] = df["customer_segment"].replace({"unknown":np.nan})
df["customer_segment"]

0       Premium
1       Premium
2       Regular
3       Regular
4        Budget
         ...
2015    Premium
2016    Regular
2017    Premium
2018    Premium
2019    Regular
Name: customer_segment, Length: 2020, dtype: object

In [39]:
# 18. Binary Column Cleaning
# Clean is_active and returned, where values contain combinations of:
# o 0/1
# o Yes/No
# o  Y/N
# o Active/Inactive
# o Returned/Not Returned
# Convert both columns into a consistent 0/1 binary format.


df["is_active"] = (
    df["is_active"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({
        "1": 1,
        "0": 0,
        "yes": 1,
        "no": 0,
        "y": 1,
        "n": 0,
        "active": 1,
        "inactive": 0
    })
)

df["returned"] = (
    df["returned"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({
        "1": 1,
        "0": 0,
        "yes": 1,
        "no": 0,
        "y": 1,
        "n": 0,
        "returned": 1,
        "not returned": 0
    })
)
df["is_active"] = pd.to_numeric(df["is_active"], errors="coerce")
df["returned"] = pd.to_numeric(df["returned"], errors="coerce")

print(df["is_active"])
print(df["returned"])

0       1
1       1
2       1
3       1
4       1
       ..
2015    1
2016    1
2017    1
2018    1
2019    1
Name: is_active, Length: 2020, dtype: int64
0       0
1       0
2       0
3       0
4       0
       ..
2015    0
2016    0
2017    0
2018    0
2019    0
Name: returned, Length: 2020, dtype: int64

C:\Users\Shree\AppData\Local\Temp\ipykernel_10948\2652660988.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\Shree\AppData\Local\Temp\ipykernel_10948\2652660988.py:33: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({

In [40]:
# 19. Data-Type Validation
# After cleaning, display df.info() and verify that:
# o Dates are datetime
# o Numerical columns are numeric
# o Binary columns contain only 0 and 1
# o Categorical columns contain clean strings

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2020 non-null   object
 1   order_date        816 non-null    datetime64[ns]
 2   city              1995 non-null   object
 3   product_category  1995 non-null   object
 4   customer_segment  2020 non-null   object
 5   gender            2020 non-null   object
 6   sales_channel     2020 non-null   object
 7   age               1969 non-null   float64
 8   units_sold        2003 non-null   float64
 9   unit_price        1988 non-null   float64
 10  discount_%        2014 non-null   float64
 11  customer_rating   1995 non-null   float64
 12  is_active         2020 non-null   int64
 13  returned          2020 non-null   int64
 14  payment_method    1995 non-null   object
 15  gross_sales       2020 non-null   float64
 16  discount_amount   2020 non-null   float64
 17  revenue           1994 non-null   float64
 18  cost              2020 non-null   float64
 19  profit            2020 non-null   float64
dtypes: datetime64[ns](1), float64(10), int64(2), object(7)
memory usage: 315.8+ KB

In [51]:


print("\nis_active values:")
print(df["is_active"].unique())

print("\nreturned values:")
print(df["returned"].unique())

print("\nGender:")
print(df["gender"].unique())

print("\nCustomer Segment:")
print(df["customer_segment"].unique())

print("\nProduct Category:")
print(df["product_category"].unique())

is_active values:
[1 0]

returned values:
[0 1]

Gender:
['Male' 'Female' 'other']

Customer Segment:
['Premium' 'Regular' 'Budget' 'preminum']

Product Category:
['clothing' 'Home & Kitchen' 'Electronics' 'sports' 'Beauty' nan]

In [52]:
# 20. Final Data Quality Check — Hardest
# Perform a complete final audit of the cleaned dataset:
# o Check duplicate rows
# o Check missing values
# o Check invalid dates
# o Check numerical columns
# o Check outliers
# o Check categorical inconsistencieso
# o Check binary values
# o Check datatypes
# o Verify that Revenue, Cost, and Profit are logically consistent


df.duplicated().sum()

np.int64(20)

In [53]:
df.isnull().sum()

customer_id            0
order_date          1204
city                  25
product_category      25
customer_segment       0
gender                 0
sales_channel          0
age                   51
units_sold            17
unit_price            32
discount_%             6
customer_rating       25
is_active              0
returned               0
payment_method        25
gross_sales            0
discount_amount        0
revenue               26
cost                   0
profit                 0
dtype: int64

In [54]:
df["customer_id"].isna().sum()

np.int64(0)

In [55]:
df.select_dtypes(include = np.number).columns.tolist()

['age',
 'units_sold',
 'unit_price',
 'discount_%',
 'customer_rating',
 'is_active',
 'returned',
 'gross_sales',
 'discount_amount',
 'revenue',
 'cost',
 'profit']

In [57]:
numeric_cols = df.select_dtypes(include = np.number).columns
numeric_cols

Index(['age', 'units_sold', 'unit_price', 'discount_%', 'customer_rating',
       'is_active', 'returned', 'gross_sales', 'discount_amount', 'revenue',
       'cost', 'profit'],
      dtype='object')

In [58]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    
    print(col, ":", len(outliers), "outliers")

age : 14 outliers
units_sold : 17 outliers
unit_price : 15 outliers
discount_% : 5 outliers
customer_rating : 0 outliers
is_active : 0 outliers
returned : 221 outliers
gross_sales : 17 outliers
discount_amount : 112 outliers
revenue : 22 outliers
cost : 39 outliers
profit : 71 outliers

In [59]:
for col in df.select_dtypes(include=["object", "string"]).columns:
    print("\n", col)
    print(df[col].unique())

 customer_id
['CUST00594' 'CUST01103' 'CUST00690' ... 'CUST01708' 'CUST00614'
 'CUST01948']

 city
['Mumbai' 'Delhi' 'Chennai' 'Hyderabad' 'Pune' 'Bengaluru' nan 'Bangalore']

 product_category
['clothing' 'Home & Kitchen' 'Electronics' 'sports' 'Beauty' nan]

 customer_segment
['Premium' 'Regular' 'Budget' 'preminum']

 gender
['Male' 'Female' 'other']

 sales_channel
['Retail' 'Corporate' 'Online' 'Corp' 'retail ' 'online' 'offline'
 'ON-LINE']

 payment_method
['UPI' 'Cash' 'Debit Card' 'Net Banking' 'Credit Card' nan]

In [60]:
df["is_active"].unique()

array([1, 0])

In [61]:
df["returned"].unique()

array([0, 1])

In [63]:
df.dtypes

customer_id                 object
order_date          datetime64[ns]
city                        object
product_category            object
customer_segment            object
gender                      object
sales_channel               object
age                        float64
units_sold                 float64
unit_price                 float64
discount_%                 float64
customer_rating            float64
is_active                    int64
returned                     int64
payment_method              object
gross_sales                float64
discount_amount            float64
revenue                    float64
cost                       float64
profit                     float64
dtype: object

In [65]:
df["revenue"].colums

AttributeError: 'Series' object has no attribute 'columns'