# Exam Task on Pandas Method (Data Cleaning)

In [438]:
#1. Load the dataset
# Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
# Then display the first 10 rows.
# Use: pd.read_csv(), head()

import pandas as pd
df = pd.read_csv("C:\\Users\\Shree\\Downloads\\customer_analytics.csv")

In [439]:
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68.0,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47.0,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65.0,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42.0,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [440]:
#2. Inspect the end of the dataset
# Display the last 15 rows.
# Use: tail()

df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51.0,214004.0,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573.0,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54.0,123511.0,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31.0,125500.0,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619.0,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41.0,201611.0,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61.0,128850.0,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33.0,88037.0,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43.0,122756.0,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18.0,189232.0,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [441]:
#3.Random inspection
# Display 10 random records.
# Use: sample()

df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
481,101910,56.0,215731.0,157069.07,315,2,Delhi,SME,Agent,2021-09-27 00:00:00,Yes,High,5808.17,88,3.6
353,100354,37.0,176094.0,NaN,846,8,Kolkata,Retail,Agent,2024-04-01 00:00:00,Yes,Low,41123.43,105,9.2
1566,100828,62.0,98794.0,273350.49,537,0,Bangalore,SME,Online,2026-01-01 00:00:00,Yes,High,missing,136,NaN
1971,100014,41.0,152015.0,245462.0,788,3,Hyderabad,Corporate,Mobile,2024-01-22 00:00:00,NO,Low,38953.15,48,5.7
1138,101765,34.0,101975.0,147669.69,443,5,Delhi,Premium,Agent,2025-09-29 00:00:00,Yes,High,10832.76,24,4.9
58,101713,38.0,NaN,122314.73,682,12,Kolkata,Retail,Online,2026-01-25 00:00:00,Yes,Medium,NaN,50,2.1
1554,101167,54.0,173702.0,166406.31,672,9,Chennai,Corporate,Online,2022-03-20 00:00:00,Yes,Medium,NaN,47,7.3
296,101971,73.0,-,184928.45,320,12,Chennai,SME,Mobile,2024-07-02 00:00:00,NO,High,49326.73,21,4.3
222,100050,24.0,NaN,224955.23,573,3,Hyderabad,SME,Agent,2022-11-21 00:00:00,No,Medium,47239.07,65,NaN
117,101905,64.0,60292.0,147616.35,460,12,Pune,Premium,Branch,2021-12-24 00:00:00,Yes,High,41708.23,24,6.2

In [442]:
#4. Dataset audit
# Use info() to identify:
# • Number of rows
# • Number of columns
# • Columns with missing values
# •  Columns having incorrect/object datatypes
# Use: info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [443]:
#5. Missing-value audit
# Calculate the number of missing values in every column.
# Then verify the result using both:
# isnull()
# and
# isna()

df.isnull().sum()
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

# Part 2 — Detect & Fix Data Quality Problems

In [444]:
#6. Duplicate investigation
# Find how many duplicate rows exist.
# Do not remove them yet.
# Use: duplicated()

df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

In [445]:
#7. Remove duplicates
# Remove all duplicate records and store the cleaned result back into df.
# Then verify that duplicates no longer exist.
# Use: drop_duplicates(), duplicated()

df.drop_duplicates()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [446]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

In [447]:
#8. Numeric column investigation
# Select only numeric columns.
# Identify which columns are currently numeric and which potentially numeric columns have
# become object because of invalid values.
# Use: select_dtypes()

df.select_dtypes

<bound method DataFrame.select_dtypes of       Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
0          101317  55.0       44033.0       111350.85          772
1          101001  32.0      215546.0       254378.37          374
2          101069  23.0      226403.0       159975.42          668
3          101968  66.0       87824.0        295741.6          315
4          100530  67.0       31570.0       242423.78          370
...           ...   ...           ...             ...          ...
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel            Join_Date  \
0                3    Bangalore        SME   Agent  2022-08-15 00:00:00
1                8        Delhi     Retail   Agent  2025-01-11 00:00:00
2               12      Chennai    Premium   Agent  2024-08-01 00:00:00
3               14       Mumbai    Premium   Agent  2021-05-15 00:00:00
4                4   bangalore      Retail   Agent  2026-02-03 00:00:00
...            ...          ...        ...     ...                  ...
2035            12    Hyderabad     Retail   Agent  2021-07-10 00:00:00
2036             8       Mumbai  Corporate   Agent  2025-07-05 00:00:00
2037             8      Kolkata     Retail  Online  2022-10-17 00:00:00
2038             8    Bangalore     Retail   Agent  2023-08-26 00:00:00
2039             6      Chennai     Retail  Branch                  NaN

     Active Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0       Yes        Low      23066.19          135                 3.1
1       Yes       High           NaN          106                 8.2
2        No     Medium      28536.34          146                 6.3
3       Yes       High      12869.71          115                 9.7
4        No       High      34163.02           94                 3.7
...     ...        ...           ...          ...                 ...
2035     No     Medium       8455.42          119                 8.6
2036    Yes       High      34087.69          134                 2.6
2037    Yes        Low      26518.74           87                 1.3
2038     No        Low      20943.11          107                 9.3
2039    Yes        Low      48511.32          119                 3.1

[2040 rows x 15 columns]>

In [448]:
#9. Fix Age
# The Age column contains:
# • Valid numbers
# • Missing values
# •  Invalid text such as unknown, N/A, etc.
# Convert Age into a proper numeric column.
# Invalid values should become missing values.
# Then fill missing Age values using the median age.
# Use: pd.to_numeric(), median(), fillna()


df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [449]:
age_median = df["Age"].median()
age_median

47.0

In [450]:
df["Age"].fillna(age_median)

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2040, dtype: float64

In [451]:
#10.  Fix Annual Income
# Clean Annual_Income.
# Requirements:
# 1. Convert invalid values to missing.
# 2. Convert the column to a numeric datatype.
# 3 . Calculate the median.
# 4. Fill missing values using the median.
# Use: pd.to_numeric(), median(), fillna(), astype()

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [452]:
Annual_Income = df["Annual_Income"].median()
Annual_Income

139999.5

In [453]:
df["Annual_Income"].fillna(Annual_Income)

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2040, dtype: float64

In [454]:
df["Annual_Income"] = df["Annual_Income"].astype(float)
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

# Part 3 — Numerical Cleaning

In [455]:
#11. Clean Account Balance
# The Account_Balance column contains invalid strings and missing values.
# Clean the column and replace missing values with the mean Account Balance.
# Use:
# • pd.to_numeric()
# • mean()
# • fillna()

df["Account_Balance"] = pd.to_numeric(df["Account_Balance"],errors = "coerce")
df["Account_Balance"]

0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2040, dtype: float64

In [456]:
balance_mean = df["Account_Balance"].mean()
balance_mean

np.float64(151049.05422603106)

In [457]:
df["Account_Balance"].fillna(balance_mean)

0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2040, dtype: float64

In [458]:
#12. Clean Credit Score
# Clean Credit_Score.
# Invalid values should become missing.
# Then replace missing values with the median Credit Score.
# Finally convert the column to integer.
# Use:
# • pd.to_numeric()
# • median()
# • fillna()
# • astype()

df["Credit_Score"] = pd.to_numeric(df["Credit_Score"],errors = "coerce")
df["Credit_Score"]

0       772.0
1       374.0
2       668.0
3       315.0
4       370.0
        ...
2035    677.0
2036    392.0
2037    737.0
2038    794.0
2039    783.0
Name: Credit_Score, Length: 2040, dtype: float64

In [459]:
median_Credit_Score= df["Credit_Score"].median()
median_Credit_Score

570.0

In [460]:
df["Credit_Score"].fillna(median_Credit_Score)

0       772.0
1       374.0
2       668.0
3       315.0
4       370.0
        ...
2035    677.0
2036    392.0
2037    737.0
2038    794.0
2039    783.0
Name: Credit_Score, Length: 2040, dtype: float64

In [461]:
df["Credit_Score"] = df["Credit_Score"].astype(float)
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370.0,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [462]:
#13. Clean Monthly Spend
# Clean Monthly_Spend.
# Then:
# • Convert it to numeric.
# • Replace invalid values.
# • Replace missing values using the median.
# • Make sure the final column is numeric.


df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370.0,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [463]:
monthly_spend_median = df["Monthly_Spend"].median()
monthly_spend_median

24646.77

In [464]:
df["Monthly_Spend"].fillna(monthly_spend_median)

0       23066.19
1       24646.77
2       28536.34
3       12869.71
4       34163.02
          ...
2035     8455.42
2036    34087.69
2037    26518.74
2038    20943.11
2039    48511.32
Name: Monthly_Spend, Length: 2040, dtype: float64

In [465]:
df["Monthly_Spend"].dtype

dtype('float64')

In [466]:
#14. Clean Transactions
# The Transactions column contains invalid strings.
# Convert it to numeric and replace invalid values with the median number of transactions.
# Then convert the final column to integer.

df["Transactions"] = pd.to_numeric(df["Transactions"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135.0,3.1
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106.0,8.2
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146.0,6.3
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115.0,9.7
4,100530,67.0,31570.0,242423.78,370.0,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94.0,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119.0,8.6
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134.0,2.6
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87.0,1.3
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107.0,9.3
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119.0,3.1

In [467]:
median_transactions = df["Transactions"].median()
median_transactions

76.0

In [468]:
df["Transactions"].fillna(median_transactions)
df["Transactions"]

0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Transactions, Length: 2040, dtype: float64

In [469]:
df["Transactions"] = df["Transactions"].astype(float)
df["Transactions"]

0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Transactions, Length: 2040, dtype: float64

In [470]:
#15. Clean Satisfaction Score
# Clean Satisfaction_Score.
# Replace missing/invalid values using the mean Satisfaction Score.
# Then convert the column to float.

df["Satisfaction_Score"] = pd.to_numeric(df["Transactions"],errors = "coerce")
df["Satisfaction_Score"]

0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Satisfaction_Score, Length: 2040, dtype: float64

In [471]:
mean_Satisfaction_Score = df["Satisfaction_Score"].mean()
mean_Satisfaction_Score

np.float64(75.50725362681341)

In [472]:
df["Satisfaction_Score"].fillna(mean_Satisfaction_Score)
df["Satisfaction_Score"]

0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Satisfaction_Score, Length: 2040, dtype: float64

In [473]:
df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)
df["Satisfaction_Score"]

0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Satisfaction_Score, Length: 2040, dtype: float64

# Part 4 — Date Cleaning

In [474]:
#16. Investigate Join_Date
# Inspect the Join_Date column.
# Identify the problems caused by:
# •  Missing dates
# • Different date formats
# • Invalid date strings

df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors = "coerce",dayfirst = True)
df["Join_Date"]

C:\Users\Shree\AppData\Local\Temp\ipykernel_7868\1246900030.py:8: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors = "coerce",dayfirst = True)

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

In [475]:
df["Join_Date"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039     True
Name: Join_Date, Length: 2040, dtype: bool

In [476]:
df["Join_Date"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2040 entries, 0 to 2039
Series name: Join_Date
Non-Null Count  Dtype
--------------  -----
1912 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 16.1 KB

In [477]:
#17. Convert Join_Date
# Convert Join_Date into a proper Pandas datetime column.
# Any invalid dates should become missing values.
# Use: pd.to_datetime()

df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors = "coerce",dayfirst = True)
df["Join_Date"]

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

In [478]:
#18. Handle missing dates
# After conversion, find how many missing dates remain.
# Then replace missing dates appropriately using a reasonable date-based strategy.

df= df["Join_Date"].isna().sum()
df

np.int64(128)

# Part 5 — Categorical Cleaning

In [479]:
#19. Clean City
# The City column contains values such as:
# Mumbai
# mumbai
# Mumbai
# mumbai
# Standardize the values so that logically identical cities are represented consistently.
# Then check the unique frequency distribution.
# Use: replace(), value_counts()


df["City"].value_counts()

IndexError: invalid index to scalar variable.

In [ ]:
df["City"] = df["City"].replace({"mumbai":"Mumbai"})
df["City"]

In [ ]:
#20. Analyze Segment
# Check the frequency of:
# Retail
# SME
# Corporate
# Premium
# Also determine whether missing values exist.
# Then replace missing Segment values with the most appropriate category based on your
# analysis.
# Use: value_counts(), fillna()

df["Segment"] = df["Segment"].value_counts(dropna = False)
df["Segment"]

In [ ]:
df["Segment"] = df["Segment"].isna().sum()
df["Segment"]

In [ ]:
#21. Clean Active
# Active is supposed to be a binary column, but it contains:
# Yes
# No
# Y 
# N
# YES
# NO
# yes
# no
# 1
# 0
# Transform these into a consistent representation:
# Yes
# No
# Then verify the result with value_counts().
# Use: replace(), value_counts()

df["Active"] = df["Active"].replace({"Y":"Yes","N":"No","yes":1,"no":0})
df["Active"]

In [ ]:
df["Active"] = df["Active"].value_counts()
df["Active"]

In [ ]:
#22. Clean Risk_Level
# Check the distribution of:
# High
# Medium
# Low
# Verify whether missing values exist.
# Then display the final class distribution.

df["Risk_Level"] = df["Risk_Level"].isna().sum()
df["Risk_Level"]

In [ ]:
df["Risk_Level"] = df["Risk_Level"].value_counts()
df["Risk_Level"]

# Part 6 — Column Transformation

In [ ]:
#23. Rename columns
# Rename these columns:
# Customer_ID → Customer_ID
# Annual_Income → AnnualIncome
# Account_Balance → AccountBalance
# Credit_Score → CreditScore
# Tenure_Years → Tenure
# Join_Date → CustomerJoinDate
# Risk_Level → RiskLevel
# Monthly_Spend → MonthlySpend
# Satisfaction_Score → SatisfactionScore
# Use rename().

df.rename(columns = {"Customer_ID":"Customer_ID","Annual_Income":"AnnualIncome","Account_Balance":"AccountBalance","Credit_Score":"CreditScore","Tenure_Years":"Tenure","Join_Date":"CustomerJoinDate","Risk_Level":"RiskLevel","Monthly_Spend":"Monthly_Spend","Satisfaction_Score":"SatisfactionScore"},inplace = True)
df

In [ ]:
#24. Add a prefix
# Add:
# Customer_
# to every column.
# Example:
# Age
# becomes:
# Customer_Age
# Use: add_prefix()

df.add_prefix("Customer_")
df

In [ ]:
#25. Remove unnecessary column
# Determine whether Customer_ID should be retained for analysis.
# Create a cleaned DataFrame without the identifier column.
# Use: drop()

df = df.drop(columns=["Customer_ID"],errors = "ignore")
df

# Part 7 — Create New Columns

In [ ]:
#26. Create Annual Income in Lakhs
# Create:
# Income_Lakhs
# using:
# AnnualIncome / 100000
#Then check the first 10 records. 

df["AnnualIncome"] = pd.to_numeric(df["AnnualIncome"],errors="coerce")
df["Income_Lakhs"] = df["AnnualIncome"] / 100000

df.head(10)

In [ ]:
#27. Create Monthly Income
# Create:
# MonthlyIncome
# using:
# AnnualIncome / 12
# Then create:
# Income_After_Spending
# using:
# MonthlyIncome - MonthlySpend

df["MonthlyIncome"] = df["AnnualIncome"] /12
df["MonthlyIncome"]

In [ ]:
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors = "coerce")

df["Income_After_Spending"] = df["MonthlyIncome"] -df["Monthly_Spend"]
df["Income_After_Spending"]

In [ ]:
#28. Create Balance-to-Income Ratio
# Create:
# Balance_Income_Ratio
# using:
# AccountBalance / AnnualIncome
# Then inspect the first 10 rows.
# Think carefully about division by zero and missing values.

df["AccountBalance"] = pd.to_numeric(df["AccountBalance"],errors= "coerce")
df["AccountBalance"]

In [ ]:
df["AnnualIncome"] = pd.to_numeric(df["AnnualIncome"],errors= "coerce")
df["AnnualIncome"]

In [ ]:
df["Balance_Income_Ratio"] = df["AccountBalance"] / df["AnnualIncome"]
df["Balance_Income_Ratio"]

In [ ]:
df.head(10)

# Part 8 — Final Real-World Cleaning Challenge

In [ ]:
#29. Prepare the ML-ready dataset
# Perform the following complete pipeline:
# 1. Load the dataset.
# 2. Inspect the first 10 rows.
# 3. Inspect the last 10 rows.
# 4. Inspect 10 random records.
# 5. Run info().
# 6. Check missing values.
# 7. Check duplicates.
# 8. Remove duplicates.
# 9. Clean all numeric columns.
# 10. Convert invalid numeric values to missing.
# 11. Fill numerical missing values appropriately.
# 12. Convert Join_Date to datetime.
# 13. Handle invalid dates.
# 14. Standardize categorical values.
# 15. Clean the binary Active column.
# 16. Rename the columns.
# 17. Remove unnecessary columns.
# 18. Verify the final datatypes.
# 19. Generate descriptive statistics.
# 20. Check categorical distributions.

import pandas as pd
df2 = pd.read_csv("C:\\Users\\Shree\\Downloads\\customer_analytics.csv")
df2

In [ ]:
#2.
df2.head(10)

In [ ]:
#3. 
df2.tail(10)

In [ ]:
#4.
df2.sample(10)

In [ ]:
#5.
df2.info()

In [ ]:
#6.
df2.isnull().sum()

In [ ]:
#7.
df2.duplicated().sum()

In [ ]:
#8.
df.drop_duplicates()

In [ ]:
#9.
numeric_cols = df.select_dtypes(include = ["int64","float64"]).columns
numeric_cols

In [ ]:
#10. 
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col],errors = "coerce")
df[col]

In [ ]:
#11. 
for col in numeric_cols:
    median_value = df[col].median()
print(df[numeric_columns].isnull().sum())

In [ ]:
#12. 
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors = "coerce")
df["Join_Date"]

In [ ]:
#13. 
df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors = "coerce")
if not df["Join_Date"].mode().empty:
    df["Join_Date"].fillna(df["Join_Date"].mode()[0])
else:
    df["Join_Date"].fillna(pd.Timestamp("2020-01-01"))
df["Join_Date"]

In [ ]:
#14. 

categorical_cols = df.select_dtypes(include = "object").column
for col in categorical_cols:
    df[col] = df[col].str.strip().str.title()
print("categorical columns:",categorical_cols)
print(df[categorical_cols].head())

In [ ]:
#15. 
if "Active" in df.columns:
    df["Active"] = df["Active"].str.strip().str.lower().map({"yes":1,"no":0})

In [ ]:
#16. 
df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
}, inplace=True)
df

In [ ]:
#17. 
df.drop(columns=["RowNumber","Surname"], errors="ignore", inplace=True)
df

In [481]:
#18. 
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [480]:
#19. 
df2.describe()

         Customer_ID  Tenure_Years  Satisfaction_Score
count    2040.000000   2040.000000         1955.000000
mean   100999.696078      7.566176            5.595908
std       577.289267      4.614468            2.578004
min    100001.000000      0.000000            1.000000
25%    100500.750000      4.000000            3.400000
50%    100999.500000      8.000000            5.700000
75%    101498.250000     12.000000            7.800000
max    102000.000000     15.000000           10.000000

In [ ]:
#20.
for col in df2.select_types(include = "object").columns:
    print(df[col].value_counts())

#Q30 — Ultimate Pandas Cleaning Project

In [4]:
# Q30 — Ultimate Pandas Cleaning Project
# You are a Data Scientist at a bank. Your raw customer dataset contains 2,000+ records with:
# • Missing values
# • Duplicate records
# • Invalid numerical values
# • Mixed datatypes
# • Invalid dates
# • Mixed date formats
# • Inconsistent categorical values
# • Binary text inconsistencies
# • Unnecessary identifier columns
# Your task is to produce a final clean analytical dataset.
# Required workflow
# Step 1 — Load
# pd.read_csv()
# Step 2 — Inspect
# head()
# tail()
# sample()
# info()

# Step 3 — Missing-value analysis
# isnull()
# isna()

# Step 4 — Duplicate handling
# duplicated()
# drop_duplicates()

# Step 5 — Numeric cleaning
# Clean:
# Age
# Annual_Income
# Account_Balance
# Credit_Score
# Monthly_Spend
# Transactions
# Satisfaction_Score

# Use:
# pd.to_numeric()
# mean()
# median()
# fillna()
# astype()

# Step 6 — Date cleaning
# Clean:
# Join_Date
# using:
# pd.to_datetime()

# Step 7 — Categorical cleaning
# Clean:
# City
# Segment

# Channel
# Active
# Risk_Level
# Use:
# replace()
# value_counts()
# fillna()

# Step 8 — Column transformation
# Use:
# rename()
# add_prefix()
# drop()

# Step 9 — Create analytical features
# Create at least these:
# Income_Lakhs
# MonthlyIncome
# Income_After_Spending
# Balance_Income_Ratio

# Step 10 — Final validation
# Your final DataFrame must pass these checks:
# No duplicate rows
# No invalid numeric values
# No unexpected object datatype in numeric columns
# No invalid dates
# No inconsistent Yes/No values

# Missing values handled
# Column names standardized

# Finally display:
# head()
# tail()
# sample()
# info()
# describe()
# value_counts()

import pandas as pd
df3 = pd.read_csv("C:\\Users\\Shree\\Downloads\\customer_analytics.csv")
df3

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [487]:
print(df3.head())
print(df3.tail())
print(df3.sample())
print(df3.info())

   Customer_ID   Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0       101317  55.0       44033.0       111350.85          772             3
1       101001  32.0      215546.0       254378.37          374             8
2       101069  23.0      226403.0       159975.42          668            12
3       101968  66.0       87824.0        295741.6          315            14
4       100530  67.0       31570.0       242423.78          370             4

          City  Segment Channel            Join_Date Active Risk_Level  \
0    Bangalore      SME   Agent  2022-08-15 00:00:00    Yes        Low
1        Delhi   Retail   Agent  2025-01-11 00:00:00    Yes       High
2      Chennai  Premium   Agent  2024-08-01 00:00:00     No     Medium
3       Mumbai  Premium   Agent  2021-05-15 00:00:00    Yes       High
4   bangalore    Retail   Agent  2026-02-03 00:00:00     No       High

  Monthly_Spend Transactions  Satisfaction_Score
0      23066.19          135                 3.1
1           NaN          106                 8.2
2      28536.34          146                 6.3
3      12869.71          115                 9.7
4      34163.02           94                 3.7
      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years       City    Segment Channel            Join_Date Active  \
2035            12  Hyderabad     Retail   Agent  2021-07-10 00:00:00     No
2036             8     Mumbai  Corporate   Agent  2025-07-05 00:00:00    Yes
2037             8    Kolkata     Retail  Online  2022-10-17 00:00:00    Yes
2038             8  Bangalore     Retail   Agent  2023-08-26 00:00:00     No
2039             6    Chennai     Retail  Branch                  NaN    Yes

     Risk_Level Monthly_Spend Transactions  Satisfaction_Score
2035     Medium       8455.42          119                 8.6
2036       High      34087.69          134                 2.6
2037        Low      26518.74           87                 1.3
2038        Low      20943.11          107                 9.3
2039        Low      48511.32          119                 3.1
     Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
624       100722  69.0       96031.0       129162.06          732

     Tenure_Years   City Segment Channel            Join_Date Active  \
624             5  Delhi  Retail  Online  2021-12-23 00:00:00    Yes

    Risk_Level Monthly_Spend Transactions  Satisfaction_Score
624        Low      40842.88           25                 8.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB
None

In [490]:
# Step 3 — Missing-value analysis

print(df3.isnull().sum())
print(df3.isna().sum())

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [493]:
# Step 4 — Duplicate handling

print(df3.duplicated())
print(df3.drop_duplicates())

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool
      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
0          101317  55.0       44033.0       111350.85          772
1          101001  32.0      215546.0       254378.37          374
2          101069  23.0      226403.0       159975.42          668
3          101968  66.0       87824.0        295741.6          315
4          100530  67.0       31570.0       242423.78          370
...           ...   ...           ...             ...          ...
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel            Join_Date  \
0                3    Bangalore        SME   Agent  2022-08-15 00:00:00
1                8        Delhi     Retail   Agent  2025-01-11 00:00:00
2               12      Chennai    Premium   Agent  2024-08-01 00:00:00
3               14       Mumbai    Premium   Agent  2021-05-15 00:00:00
4                4   bangalore      Retail   Agent  2026-02-03 00:00:00
...            ...          ...        ...     ...                  ...
2035            12    Hyderabad     Retail   Agent  2021-07-10 00:00:00
2036             8       Mumbai  Corporate   Agent  2025-07-05 00:00:00
2037             8      Kolkata     Retail  Online  2022-10-17 00:00:00
2038             8    Bangalore     Retail   Agent  2023-08-26 00:00:00
2039             6      Chennai     Retail  Branch                  NaN

     Active Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0       Yes        Low      23066.19          135                 3.1
1       Yes       High           NaN          106                 8.2
2        No     Medium      28536.34          146                 6.3
3       Yes       High      12869.71          115                 9.7
4        No       High      34163.02           94                 3.7
...     ...        ...           ...          ...                 ...
2035     No     Medium       8455.42          119                 8.6
2036    Yes       High      34087.69          134                 2.6
2037    Yes        Low      26518.74           87                 1.3
2038     No        Low      20943.11          107                 9.3
2039    Yes        Low      48511.32          119                 3.1

[2000 rows x 15 columns]

In [6]:
# Step 5 — Numeric cleaning

import pandas as pd

numeric_cols = [
    "Age","Annual_Income","Account_Balance","Credit_Score","Monthly_Spend","Transactions","Satisfaction_Score"]
for col in numeric_cols:
    df3[col] = pd.to_numeric(df3[col],errors = "coerce")
    df3[col].fillna(df3[col].median())
    df3[col].fillna(df3[col].mean())
    df3[col] = df3[col].astype(float)

# Step 6 — Date cleaning

In [15]:
df3["Join_Date"] = pd.to_datetime(df3["Join_Date"],errors = "coerce")
df3["Join_Date"]

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039   2022-01-25
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

In [16]:
df3["Join_Date"].fillna(df3["Join_Date"].mode()[0])

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039   2022-01-25
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

#7. Step 7 — Categorical cleaning

In [20]:
df3["City"] = df3["City"].str.strip().str.title()
df3["City"].value_counts(dropna = False)

City
Mumbai       314
Hyderabad    298
Delhi        288
Kolkata      276
Pune         274
Chennai      255
Bangalore    254
NaN           81
Name: count, dtype: int64

In [24]:
df3["Segment"] = df3["Segment"].replace({"retail" :"Retail","corporate":"Coporate","premium":"Premium"})
df3["Segment"]

0             SME
1          Retail
2         Premium
3         Premium
4          Retail
          ...
2035       Retail
2036    Corporate
2037       Retail
2038       Retail
2039       Retail
Name: Segment, Length: 2040, dtype: object

In [25]:
df3["Segment"].value_counts(dropna  = False)

Segment
Premium      523
Retail       481
Corporate    475
SME          456
NaN          105
Name: count, dtype: int64

In [26]:
df3["Channel"].value_counts(dropna = False)

Channel
Agent     541
Online    505
Branch    505
Mobile    489
Name: count, dtype: int64

In [29]:
df3["Channel"] = df3["Channel"].replace({"online":"Online","branch":"Branch","mobile":"Mobile"})
df3["Channel"]

0        Agent
1        Agent
2        Agent
3        Agent
4        Agent
         ...
2035     Agent
2036     Agent
2037    Online
2038     Agent
2039    Branch
Name: Channel, Length: 2040, dtype: object

In [33]:
df3["Active"] = df3["Active"].str.strip().str.lower().replace({
    "yes":1,"y":1,"true":1,
    "no":0,"n":0,"false":0
})
df3

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,NaN,Low,23066.19,135.0,3.1
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,NaN,High,NaN,106.0,8.2
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,NaN,Medium,28536.34,146.0,6.3
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,NaN,High,12869.71,115.0,9.7
4,100530,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,NaN,High,34163.02,94.0,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,NaN,Medium,8455.42,119.0,8.6
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,NaN,High,34087.69,134.0,2.6
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,NaN,Low,26518.74,87.0,1.3
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,NaN,Low,20943.11,107.0,9.3
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2022-01-25,NaN,Low,48511.32,119.0,3.1

# Step 8 — Column transformation

In [36]:
df3.rename(columns={
    "CustomerId": "Customer_ID",
    "Annual_Income": "Income",
    "Account_Balance": "Balance"
}, inplace=True)
df3

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,NaN,Low,23066.19,135.0,3.1
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,NaN,High,NaN,106.0,8.2
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,NaN,Medium,28536.34,146.0,6.3
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,NaN,High,12869.71,115.0,9.7
4,100530,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,NaN,High,34163.02,94.0,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,NaN,Medium,8455.42,119.0,8.6
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,NaN,High,34087.69,134.0,2.6
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,NaN,Low,26518.74,87.0,1.3
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,NaN,Low,20943.11,107.0,9.3
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2022-01-25,NaN,Low,48511.32,119.0,3.1

In [37]:
df3.add_prefix("Cust_")

,Cust_Customer_ID,Cust_Age,Cust_Income,Cust_Balance,Cust_Credit_Score,Cust_Tenure_Years,Cust_City,Cust_Segment,Cust_Channel,Cust_Join_Date,Cust_Active,Cust_Risk_Level,Cust_Monthly_Spend,Cust_Transactions,Cust_Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,NaN,Low,23066.19,135.0,3.1
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,NaN,High,NaN,106.0,8.2
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,NaN,Medium,28536.34,146.0,6.3
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,NaN,High,12869.71,115.0,9.7
4,100530,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,NaN,High,34163.02,94.0,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,NaN,Medium,8455.42,119.0,8.6
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,NaN,High,34087.69,134.0,2.6
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,NaN,Low,26518.74,87.0,1.3
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,NaN,Low,20943.11,107.0,9.3
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2022-01-25,NaN,Low,48511.32,119.0,3.1

In [39]:
df3.drop(columns=["Cust_RowNumber","Cust_Surname"], errors="ignore")

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,NaN,Low,23066.19,135.0,3.1
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,NaN,High,NaN,106.0,8.2
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,NaN,Medium,28536.34,146.0,6.3
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,NaN,High,12869.71,115.0,9.7
4,100530,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,NaN,High,34163.02,94.0,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,NaN,Medium,8455.42,119.0,8.6
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,NaN,High,34087.69,134.0,2.6
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,NaN,Low,26518.74,87.0,1.3
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,NaN,Low,20943.11,107.0,9.3
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2022-01-25,NaN,Low,48511.32,119.0,3.1

In [40]:
df3.columns

Index(['Customer_ID', 'Age', 'Income', 'Balance', 'Credit_Score',
       'Tenure_Years', 'City', 'Segment', 'Channel', 'Join_Date', 'Active',
       'Risk_Level', 'Monthly_Spend', 'Transactions', 'Satisfaction_Score'],
      dtype='object')

# Step 9 — Create analytical features

In [45]:
df3["Income_Lakhs"] = df3["Income"] / 100000
df3["Income_Lakhs"]

0       0.44033
1       2.15546
2       2.26403
3       0.87824
4       0.31570
         ...
2035    0.88530
2036    2.05738
2037    2.11994
2038    0.30105
2039    2.48332
Name: Income_Lakhs, Length: 2040, dtype: float64

In [48]:
df3["MonthlyIncome"] = df3["Income"] / 12
df3["MonthlyIncome"]

0        3669.416667
1       17962.166667
2       18866.916667
3        7318.666667
4        2630.833333
            ...
2035     7377.500000
2036    17144.833333
2037    17666.166667
2038     2508.750000
2039    20694.333333
Name: MonthlyIncome, Length: 2040, dtype: float64

In [51]:
df3["Income_After_Spending"] = (
    df3["MonthlyIncome"] - df3["Monthly_Spend"]
)
df3["Income_After_Spending"]

0      -19396.773333
1                NaN
2       -9669.423333
3       -5551.043333
4      -31532.186667
            ...
2035    -1077.920000
2036   -16942.856667
2037    -8852.573333
2038   -18434.360000
2039   -27816.986667
Name: Income_After_Spending, Length: 2040, dtype: float64

In [55]:
df3["Balance_Income_Ratio"] = (
df3["Balance"] / df3["Income"]
)
df3["Balance_Income_Ratio"]

0       2.528805
1       1.180158
2       0.706596
3       3.367435
4       7.678929
          ...
2035    1.733771
2036    1.317158
2037    0.757133
2038    1.066838
2039    1.107312
Name: Balance_Income_Ratio, Length: 2040, dtype: float64

In [56]:
df3.head()

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,NaN,Low,23066.19,135.0,3.1,0.44033,3669.416667,-19396.773333,2.528805
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,NaN,High,NaN,106.0,8.2,2.15546,17962.166667,NaN,1.180158
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,NaN,Medium,28536.34,146.0,6.3,2.26403,18866.916667,-9669.423333,0.706596
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,NaN,High,12869.71,115.0,9.7,0.87824,7318.666667,-5551.043333,3.367435
4,100530,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,NaN,High,34163.02,94.0,3.7,0.31570,2630.833333,-31532.186667,7.678929

In [59]:
# step 10 - Final Validation

print(df3.duplicated().sum())

40

In [64]:
df3.isnull().sum()

Customer_ID                 0
Age                       128
Income                    152
Balance                   173
Credit_Score               40
Tenure_Years                0
City                       81
Segment                   105
Channel                     0
Join_Date                   0
Active                   2011
Risk_Level                  0
Monthly_Spend             151
Transactions               41
Satisfaction_Score         85
Income_Lakhs              152
MonthlyIncome             152
Income_After_Spending     296
Balance_Income_Ratio      314
dtype: int64

In [76]:
df3.value_counts(dropna = False).sum()

np.int64(2040)

In [74]:
df3["Join_Date"].dtypes

dtype('<M8[ns]')

In [77]:
df3["Active"].value_counts(dropna = False)

Active
NaN    2011
0        17
1        12
Name: count, dtype: int64

In [78]:
df3.head()

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,NaN,Low,23066.19,135.0,3.1,0.44033,3669.416667,-19396.773333,2.528805
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,NaN,High,NaN,106.0,8.2,2.15546,17962.166667,NaN,1.180158
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,NaN,Medium,28536.34,146.0,6.3,2.26403,18866.916667,-9669.423333,0.706596
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,NaN,High,12869.71,115.0,9.7,0.87824,7318.666667,-5551.043333,3.367435
4,100530,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,NaN,High,34163.02,94.0,3.7,0.31570,2630.833333,-31532.186667,7.678929

In [79]:
df3.tail()

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,NaN,Medium,8455.42,119.0,8.6,0.88530,7377.500000,-1077.920000,1.733771
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,NaN,High,34087.69,134.0,2.6,2.05738,17144.833333,-16942.856667,1.317158
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,NaN,Low,26518.74,87.0,1.3,2.11994,17666.166667,-8852.573333,0.757133
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,NaN,Low,20943.11,107.0,9.3,0.30105,2508.750000,-18434.360000,1.066838
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2022-01-25,NaN,Low,48511.32,119.0,3.1,2.48332,20694.333333,-27816.986667,1.107312

In [80]:
df3.sample()

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
1970,100242,69.0,74268.0,NaN,548.0,2,Kolkata,Corporate,Branch,2025-12-05,NaN,High,17127.74,107.0,5.5,0.74268,6189.0,-10938.74,NaN

In [81]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            2040 non-null   int64
 1   Age                    1912 non-null   float64
 2   Income                 1888 non-null   float64
 3   Balance                1867 non-null   float64
 4   Credit_Score           2000 non-null   float64
 5   Tenure_Years           2040 non-null   int64
 6   City                   1959 non-null   object
 7   Segment                1935 non-null   object
 8   Channel                2040 non-null   object
 9   Join_Date              2040 non-null   datetime64[ns]
 10  Active                 29 non-null     object
 11  Risk_Level             2040 non-null   object
 12  Monthly_Spend          1889 non-null   float64
 13  Transactions           1999 non-null   float64
 14  Satisfaction_Score     1955 non-null   float64
 15  Income_Lakhs           1888 non-null   float64
 16  MonthlyIncome          1888 non-null   float64
 17  Income_After_Spending  1744 non-null   float64
 18  Balance_Income_Ratio   1726 non-null   float64
dtypes: datetime64[ns](1), float64(11), int64(2), object(5)
memory usage: 302.9+ KB

In [82]:
df3.describe()

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,Join_Date,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
count,2040.000000,1912.000000,1888.000000,1867.000000,2000.00000,2040.000000,2040,1889.000000,1999.000000,1955.000000,1888.000000,1888.000000,1744.000000,1726.000000
mean,100999.696078,47.049686,138282.272775,151049.054226,576.03550,7.566176,2023-07-20 08:19:45.882353152,24918.982107,75.507254,5.595908,1.382823,11523.522731,-13463.674828,1.533345
min,100001.000000,18.000000,25163.000000,55.960000,300.00000,0.000000,2021-01-01 00:00:00,559.580000,1.000000,1.000000,0.251630,2096.916667,-46902.986667,0.000281
25%,100500.750000,33.000000,82796.750000,76082.955000,433.00000,4.000000,2022-02-16 00:00:00,12247.050000,39.000000,3.400000,0.827967,6899.729167,-25461.499167,0.553147
50%,100999.500000,47.000000,139999.500000,153954.930000,570.00000,8.000000,2023-07-05 12:00:00,24646.770000,76.000000,5.700000,1.399995,11666.625000,-13064.303333,1.124677
75%,101498.250000,62.000000,192704.250000,227359.760000,722.00000,12.000000,2024-11-06 06:00:00,37514.940000,112.000000,7.800000,1.927042,16058.687500,-1056.959167,1.899580
max,102000.000000,75.000000,249977.000000,299914.140000,850.00000,15.000000,2026-03-13 00:00:00,49942.820000,149.000000,10.000000,2.499770,20831.416667,19642.133333,11.427467
std,577.289267,16.735675,64422.142068,86477.979699,162.19825,4.614468,NaN,14379.933164,43.074845,2.578004,0.644221,5368.511839,15386.632249,1.530741

In [85]:
df3.value_counts()
df3

,Customer_ID,Age,Income,Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,NaN,Low,23066.19,135.0,3.1,0.44033,3669.416667,-19396.773333,2.528805
1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,NaN,High,NaN,106.0,8.2,2.15546,17962.166667,NaN,1.180158
2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,NaN,Medium,28536.34,146.0,6.3,2.26403,18866.916667,-9669.423333,0.706596
3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,NaN,High,12869.71,115.0,9.7,0.87824,7318.666667,-5551.043333,3.367435
4,100530,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,NaN,High,34163.02,94.0,3.7,0.31570,2630.833333,-31532.186667,7.678929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,NaN,Medium,8455.42,119.0,8.6,0.88530,7377.500000,-1077.920000,1.733771
2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,NaN,High,34087.69,134.0,2.6,2.05738,17144.833333,-16942.856667,1.317158
2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,NaN,Low,26518.74,87.0,1.3,2.11994,17666.166667,-8852.573333,0.757133
2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,NaN,Low,20943.11,107.0,9.3,0.30105,2508.750000,-18434.360000,1.066838
2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2022-01-25,NaN,Low,48511.32,119.0,3.1,2.48332,20694.333333,-27816.986667,1.107312

In [86]:
df3.to_csv("Clean_data.csv")