In [77]:
# 1. Load the Flight Price dataset into a Pandas DataFrame and display the first
# five rows.

import pandas as pd

df = pd.read_excel("C:\\Users\\Shree\\Downloads\\Data_Train.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [78]:
#2. Find the number of rows and columns in the dataset.
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [79]:
# 3. Display all column names in the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [80]:
#4. Display the data types of all columns.

df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [81]:
#5. Use df.info() to inspect the structure of the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [82]:
#6. Check the number of missing values in each column.

df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10678    False
10679    False
10680    False
10681    False
10682    False
Length: 10683, dtype: bool

In [83]:
#7. Check the percentage of missing values in each column.

df.isnull().sum()/100

Airline            0.00
Date_of_Journey    0.00
Source             0.00
Destination        0.00
Route              0.01
Dep_Time           0.00
Arrival_Time       0.00
Duration           0.00
Total_Stops        0.01
Additional_Info    0.00
Price              0.00
dtype: float64

In [84]:
#8. Display the unique values and frequency of each value in the Airline column.

df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [85]:
df["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [86]:
#9. Display the frequency distribution of Total_Stops, including missing values.

df["Total_Stops"].isnull().sum()

np.int64(1)

In [87]:
df["Total_Stops"].value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [88]:
# 10.Convert Date_of_Journey into a datetime format.

df["Date_of_Journey"] = pd.to_datetime(
    df["Date_of_Journey"], errors = "coerce")

df

C:\Users\Shree\AppData\Local\Temp\ipykernel_31404\3798158453.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date_of_Journey"] = pd.to_datetime(

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [89]:
#11. Extract the day from Date_of_Journey and create a day column.

df['Day'] = df['Date_of_Journey'].dt.day
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9

In [90]:
#12.Extract the month from Date_of_Journey and create a month column.

df['Month'] = df['Date_of_Journey'].dt.month

df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5

In [91]:
#13.Extract the year from Date_of_Journey and create a year column.

df['Year'] = df['Date_of_Journey'].dt.year

print(df['Year'])

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
10678    2019
10679    2019
10680    2019
10681    2019
10682    2019
Name: Year, Length: 10683, dtype: int32

In [92]:
#14.Drop the original Date_of_Journey column after extracting the required
# features.

df.columns = df.columns.str.strip()

df.drop('Date_of_Journey', axis=1, inplace=True)

In [93]:
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [94]:
'Date_of_Journey' in df.columns

False

In [95]:
#15. Convert Dep_Time into datetime format and extract the departure hour into
# Dep_Hour.

df['Dep_Time'] = pd.to_datetime(df['Dep_Time'], errors='coerce')

df['Dep_Time']

C:\Users\Shree\AppData\Local\Temp\ipykernel_31404\2612526760.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dep_Time'] = pd.to_datetime(df['Dep_Time'], errors='coerce')

0       2026-08-10 22:20:00
1       2026-08-10 05:50:00
2       2026-08-10 09:25:00
3       2026-08-10 18:05:00
4       2026-08-10 16:50:00
                ...
10678   2026-08-10 19:55:00
10679   2026-08-10 20:45:00
10680   2026-08-10 08:20:00
10681   2026-08-10 11:30:00
10682   2026-08-10 10:55:00
Name: Dep_Time, Length: 10683, dtype: datetime64[ns]

In [96]:
df['Dep_Hour'] = df['Dep_Time'].dt.hour
df['Dep_Hour']

0        22
1         5
2         9
3        18
4        16
         ..
10678    19
10679    20
10680     8
10681    11
10682    10
Name: Dep_Hour, Length: 10683, dtype: int32

In [97]:
#16.Extract the departure minute from Dep_Time and create Dep_Minute.

df['Dep_Time'] = pd.to_datetime(df['Dep_Time'], errors='coerce')

df['Dep_Time']

0       2026-08-10 22:20:00
1       2026-08-10 05:50:00
2       2026-08-10 09:25:00
3       2026-08-10 18:05:00
4       2026-08-10 16:50:00
                ...
10678   2026-08-10 19:55:00
10679   2026-08-10 20:45:00
10680   2026-08-10 08:20:00
10681   2026-08-10 11:30:00
10682   2026-08-10 10:55:00
Name: Dep_Time, Length: 10683, dtype: datetime64[ns]

In [98]:
df['Dep_Minute'] =  df['Dep_Time'].dt.hour
df['Dep_Minute']

0        22
1         5
2         9
3        18
4        16
         ..
10678    19
10679    20
10680     8
10681    11
10682    10
Name: Dep_Minute, Length: 10683, dtype: int32

In [99]:
#17.Drop the original Dep_Time column after extracting the required features.

df.drop('Dep_Time', axis=1, inplace=True)

In [100]:
df

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,22
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,5
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,9
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,18
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,22:25,2h 30m,non-stop,No info,4107,9,4,2019,19,19
10679,Air India,Kolkata,Banglore,CCU → BLR,23:20,2h 35m,non-stop,No info,4145,27,4,2019,20,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,11:20,3h,non-stop,No info,7229,27,4,2019,8,8
10681,Vistara,Banglore,New Delhi,BLR → DEL,14:10,2h 40m,non-stop,No info,12648,1,3,2019,11,11
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,8h 20m,2 stops,No info,11753,9,5,2019,10,10

In [101]:
# 18.Extract only the time portion from Arrival_Time.

df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], errors='coerce')

df['Arrival_Time']

C:\Users\Shree\AppData\Local\Temp\ipykernel_31404\1565757603.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], errors='coerce')

0       2026-03-22 01:10:00
1       2026-08-10 13:15:00
2       2026-06-10 04:25:00
3       2026-08-10 23:30:00
4       2026-08-10 21:35:00
                ...
10678   2026-08-10 22:25:00
10679   2026-08-10 23:20:00
10680   2026-08-10 11:20:00
10681   2026-08-10 14:10:00
10682   2026-08-10 19:15:00
Name: Arrival_Time, Length: 10683, dtype: datetime64[ns]

In [102]:
#19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.

df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], format='%H:%M', errors='coerce')

df['Arrival_Hour'] = df['Arrival_Time'].dt.hour
df['Arrival_Minute'] = df['Arrival_Time'].dt.minute

df.head()

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-03-22 01:10:00,2h 50m,non-stop,No info,3897,24,3,2019,22,22,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-10 13:15:00,7h 25m,2 stops,No info,7662,1,5,2019,5,5,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-06-10 04:25:00,19h,2 stops,No info,13882,9,6,2019,9,9,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-10 23:30:00,5h 25m,1 stop,No info,6218,12,5,2019,18,18,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-10 21:35:00,4h 45m,1 stop,No info,13302,1,3,2019,16,16,21,35

In [103]:
# 20.Drop the original Arrival_Time column after extracting the required features.

df.drop('Arrival_Time', axis=1, inplace=True)

In [104]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,22,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,5,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,9,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,18,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,16,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,19,19,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,20,20,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,8,8,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,11,11,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,10,10,19,15

In [105]:
# 21.Extract the hour component from Duration and create Duration_Hour. Handle
# invalid or missing extracted values appropriately.

df["Duration_Hour"] = pd.to_datetime(df["Duration"], errors="coerce").dt.hour
df["Duration_Hour"]

C:\Users\Shree\AppData\Local\Temp\ipykernel_31404\138740772.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Duration_Hour"] = pd.to_datetime(df["Duration"], errors="coerce").dt.hour

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
10678   NaN
10679   NaN
10680   NaN
10681   NaN
10682   NaN
Name: Duration_Hour, Length: 10683, dtype: float64

In [106]:
df["Duration_Hour"] = df["Duration_Hour"].fillna(0).astype(int)
df["Duration_Hour"]

0        0
1        0
2        0
3        0
4        0
        ..
10678    0
10679    0
10680    0
10681    0
10682    0
Name: Duration_Hour, Length: 10683, dtype: int64

In [107]:
df["Duration_Hour"].unique()

array([0])

In [108]:
df["Duration_Hour"].isna().sum()

np.int64(0)

In [109]:
#22.Extract the minute component from Duration and create Duration_Minute.
# Handle invalid or missing extracted values appropriately. 

df['Duration_Minute'] = pd.to_datetime(df["Duration"],errors = "coerce").dt.minute
df['Duration_Minute']

C:\Users\Shree\AppData\Local\Temp\ipykernel_31404\1691923722.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Duration_Minute'] = pd.to_datetime(df["Duration"],errors = "coerce").dt.minute

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
10678   NaN
10679   NaN
10680   NaN
10681   NaN
10682   NaN
Name: Duration_Minute, Length: 10683, dtype: float64

In [110]:
df["Duration_Minute"] = df["Duration_Minute"].fillna(0).astype(int)
df["Duration_Minute"]

0        0
1        0
2        0
3        0
4        0
        ..
10678    0
10679    0
10680    0
10681    0
10682    0
Name: Duration_Minute, Length: 10683, dtype: int64

In [111]:
df["Duration_Minute"].unique()

array([0])

In [112]:
df["Duration_Minute"].isna().sum()

np.int64(0)

In [113]:
#23.Drop the original Duration column after creating the numerical duration
# features.

df = df.drop(columns = ["Duration"])
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,22,22,1,10,0,0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,5,5,13,15,0,0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,9,9,4,25,0,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,18,18,23,30,0,0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,16,16,21,35,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,non-stop,No info,4107,9,4,2019,19,19,22,25,0,0
10679,Air India,Kolkata,Banglore,CCU → BLR,non-stop,No info,4145,27,4,2019,20,20,23,20,0,0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,non-stop,No info,7229,27,4,2019,8,8,11,20,0,0
10681,Vistara,Banglore,New Delhi,BLR → DEL,non-stop,No info,12648,1,3,2019,11,11,14,10,0,0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2 stops,No info,11753,9,5,2019,10,10,19,15,0,0

In [114]:
#24.Replace non-stop in Total_Stops with 0 stops.

df.replace({'Total_Stops':{'non_stop':0}},inplace = True)
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,22,22,1,10,0,0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,5,5,13,15,0,0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,9,9,4,25,0,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,18,18,23,30,0,0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,16,16,21,35,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,non-stop,No info,4107,9,4,2019,19,19,22,25,0,0
10679,Air India,Kolkata,Banglore,CCU → BLR,non-stop,No info,4145,27,4,2019,20,20,23,20,0,0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,non-stop,No info,7229,27,4,2019,8,8,11,20,0,0
10681,Vistara,Banglore,New Delhi,BLR → DEL,non-stop,No info,12648,1,3,2019,11,11,14,10,0,0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2 stops,No info,11753,9,5,2019,10,10,19,15,0,0

In [115]:
#25.Extract only the numerical value from Total_Stops and convert the column into
# an integer data type. Handle missing or invalid values appropriately.

df["Total_Stops"] = pd.to_numeric(df["Total_Stops"], errors = "coerce")
df["Total_Stops"]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
10678   NaN
10679   NaN
10680   NaN
10681   NaN
10682   NaN
Name: Total_Stops, Length: 10683, dtype: float64

In [116]:
df["Total_Stops"] = df["Total_Stops"].fillna(0).astype(int)
df["Total_Stops"]

0        0
1        0
2        0
3        0
4        0
        ..
10678    0
10679    0
10680    0
10681    0
10682    0
Name: Total_Stops, Length: 10683, dtype: int64

In [117]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Total_Stops         int64
Additional_Info    object
Price               int64
Day                 int32
Month               int32
Year                int32
Dep_Hour            int32
Dep_Minute          int32
Arrival_Hour        int32
Arrival_Minute      int32
Duration_Hour       int64
Duration_Minute     int64
dtype: object

In [118]:
#26.Split the Route column using → as the separator and create Route_1,
# Route_2, Route_3, Route_4, and Route_5.

route_split = df['Route'].str.split('→', n=4, expand=True)

route_split.columns = ['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']

df[['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']] = route_split

print(df[['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']])

      Route_1 Route_2 Route_3 Route_4 Route_5
0        BLR      DEL    None    None    None
1        CCU     IXR     BBI      BLR    None
2        DEL     LKO     BOM      COK    None
3        CCU     NAG      BLR    None    None
4        BLR     NAG      DEL    None    None
...       ...     ...     ...     ...     ...
10678    CCU      BLR    None    None    None
10679    CCU      BLR    None    None    None
10680    BLR      DEL    None    None    None
10681    BLR      DEL    None    None    None
10682    DEL     GOI     BOM      COK    None

[10683 rows x 5 columns]

In [119]:
#27.Identify the missing values created in Route_3, Route_4, and Route_5 after
# splitting the route. 


missing_values = df[["Route_3","Route_4","Route_5"]].isnull().sum()
missing_values

Route_3     3492
Route_4     9117
Route_5    10637
dtype: int64

In [120]:
#28.Replace the missing values in the route columns with an appropriate value
# such as None.

df[['Route_3', 'Route_4', 'Route_5']] = (
    df[['Route_3', 'Route_4', 'Route_5']].fillna('None'))

df[['Route_3', 'Route_4', 'Route_5']]

      Route_3 Route_4 Route_5
0        None    None    None
1        BBI      BLR    None
2        BOM      COK    None
3         BLR    None    None
4         DEL    None    None
...       ...     ...     ...
10678    None    None    None
10679    None    None    None
10680    None    None    None
10681    None    None    None
10682    BOM      COK    None

[10683 rows x 3 columns]

In [121]:
#29.Drop the original Route column after creating and cleaning the route features.

df.drop("Route", axis = 1, inplace = True)
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,22,22,1,10,0,0,BLR,DEL,None,None,None
1,Air India,Kolkata,Banglore,0,No info,7662,1,5,2019,5,5,13,15,0,0,CCU,IXR,BBI,BLR,None
2,Jet Airways,Delhi,Cochin,0,No info,13882,9,6,2019,9,9,4,25,0,0,DEL,LKO,BOM,COK,None
3,IndiGo,Kolkata,Banglore,0,No info,6218,12,5,2019,18,18,23,30,0,0,CCU,NAG,BLR,None,None
4,IndiGo,Banglore,New Delhi,0,No info,13302,1,3,2019,16,16,21,35,0,0,BLR,NAG,DEL,None,None

In [122]:
#30.After completing all data cleaning and feature engineering, separate the
# dataset into X (independent variables) and y (target variable), where Price
# is the target.

x = df.drop("Price",axis = 1)
y = df["Price"]
print(x.shape)
print(y.shape)

(10683, 19)
(10683,)