# Hotel Dataset — 30 Data Cleaning Questions

In [1]:
# 1. Remove leading/trailing spaces from column names
# Explanation: Column names like "Booking ID " and "Customer Name" have extra spaces. This
# causes errors when you try to select columns. Just strip the spaces so names become clean
# (Booking ID, Customer Name).

import numpy as np
import pandas as pd

df= pd.read_csv("C:\\Users\\Shree\\Downloads\\Hotel_booking_dataset.csv")
df
df.columns = df.columns.str.strip()

print(df.columns)

Index(['Booking ID', 'Customer Name', 'Booking Date', 'City', 'Room Type',
       'Booking Channel', 'Customer Segment', 'Gender', 'Age', 'Room Nights',
       'Room Rate', 'Discount %', 'Rating', 'Guests', 'Is Member', 'Cancelled',
       'Payment Method', 'Gross Amount', 'Discount Amount', 'Final Amount',
       'Hotel Cost', 'Profit'],
      dtype='object')

In [2]:
df= pd.read_csv("C:\\Users\\Shree\\Downloads\\Hotel_booking_dataset.csv")
df

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39,4,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629424,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25,1,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50,4,...,1.2,1,0,1,Credit Card,66334.52,15575.345296,50759.174704,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53,3,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806936,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27 00:00:00,Hyderabad,Deluxe,Online,Premium,Other,52,3,...,4.0,4,1,0,Net Banking,12777.78,204.444480,12573.335520,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22 00:00:00,Hyderabad,Deluxe,Online,Premium,Male,33,5,...,4.7,5,1,1,Net Banking,51298.55,17574.883230,33723.666770,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11 00:00:00,Mumbai,Deluxe,Online,Premium,Male,48,6,...,1.3,6,1,0,Debit Card,79546.56,23108.275680,56438.284320,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24 00:00:00,Hyderabad,Executive,Travel Agent,Budget,Female,52,2,...,3.8,2,1,1,Debit Card,18041.10,5910.264360,12130.835640,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06 00:00:00,Mumbai,Suite,Walk-in,Premium,Male,23,5,...,4.8,1,1,1,Debit Card,7644.65,1025.147565,6619.502435,3428.758380,3190.744055

In [40]:
# 2. Standardize all date formats into one consistent format (YYYY-MM-DD)
# Explanation: Dates appear as 2025-05-17 00:00:00, 2025/02/20, 15/01/2025, and even
# invalid ones like 32/13/2025. Convert everything to a single clean format and turn bad dates
# into missing values.

df.columns = df.columns.str.strip()
df["Booking Date"] = pd.to_datetime(df["Booking Date"], errors="coerce")
df["Booking Date"]

0      2025-05-17
1      2025-07-29
2      2025-10-19
3      2025-12-14
4      2025-01-20
          ...
2020   2025-11-27
2021   2025-10-22
2022   2025-07-11
2023   2025-01-24
2024   2025-04-06
Name: Booking Date, Length: 2025, dtype: datetime64[ns]

In [4]:
# 3. Handle completely missing Customer Name values
# Explanation: Some rows have blank Customer Name or values like N/A. Decide whether to
# fill them with a placeholder (e.g., “Unknown”) or drop those rows, depending on whether
# the name is critical for analysis.

df["Customer Name"] = df["Customer Name"].replace(["N/A","NA","n/a",""],pd.NA)
df["Customer Name"] = df["Customer Name"].fillna("Unknown")
print(df["Customer Name"].head())

0    Customer_1888
1    Customer_0789
2    Customer_0757
3    Customer_1079
4    Customer_0218
Name: Customer Name, dtype: object

In [5]:
# 4. Fix inconsistent Gender values
# Explanation: Gender appears as Male, FEMALE, male, F, M, Other, etc. Convert everything to
# a standard set such as Male, Female, Other.

df["Gender"] = df["Gender"].replace({"M":"Male","F":"Female",
                                     "male":"Male","female":"Female"})
df["Gender"]

0         Male
1         Male
2        Other
3         Male
4         Male
         ...
2020     Other
2021      Male
2022      Male
2023    Female
2024      Male
Name: Gender, Length: 2025, dtype: object

In [6]:
# 5. Clean and standardize City names
# Explanation: Cities have typos and casing issues (mumbai, Mumbai , Bangalore, Hydrabad,
# blank). Correct spelling, remove extra spaces, and make casing consistent (e.g., Title Case).

df["City"] = df["City"].replace({"mumbai":"Mumbai","Bangalore":"Banglore","Hydrabad":"Hyderabad","":"Unknown"})
df["City"]

0          Mumbai
1       Bengaluru
2            Pune
3          Mumbai
4           Delhi
          ...
2020    Hyderabad
2021    Hyderabad
2022       Mumbai
2023    Hyderabad
2024       Mumbai
Name: City, Length: 2025, dtype: object

In [7]:
df["City"] = df["City"].str.title()
df["City"]

0          Mumbai
1       Bengaluru
2            Pune
3          Mumbai
4           Delhi
          ...
2020    Hyderabad
2021    Hyderabad
2022       Mumbai
2023    Hyderabad
2024       Mumbai
Name: City, Length: 2025, dtype: object

In [8]:
# 6. Standardize Room Type categories
# Explanation: Room Type has Suite, Deluxe, delux, standard, exec, Unknown, and blanks.
# Map similar values to a clean list: Standard, Deluxe, Suite, Executive.

df["Room Type"] = df["Room Type"].replace({"delux" :"Deluxe",
                                           "standard":"Standard",
                                           "exec":"Executive",
                                           "":"Unknown"})
df["Room Type"] = df["Room Type"].str.title()
df["Room Type"]

0           Suite
1           Suite
2           Suite
3          Deluxe
4           Suite
          ...
2020       Deluxe
2021       Deluxe
2022       Deluxe
2023    Executive
2024        Suite
Name: Room Type, Length: 2025, dtype: object

In [9]:
# 7. Clean Booking Channel values
# Explanation: Values include Online, online, Walk-in, Travel Agent, TravelAgent, corp,
# Corporate. Unify them into a small consistent set (Online, Walk-in, Corporate, Travel Agent).

df["Booking Channel"] = df["Booking Channel"].replace({"online":"Online","walk-in":"Walk-in","Travel Agent":"Travel Agent","Corp":"Corporate"})
df["Booking Channel"]

0             Online
1            Walk-in
2          Corporate
3            Walk-in
4       Travel Agent
            ...
2020          Online
2021          Online
2022          Online
2023    Travel Agent
2024         Walk-in
Name: Booking Channel, Length: 2025, dtype: object

In [10]:
# 8. Standardize Customer Segment
# Explanation: Segments appear as Premium, regular, REG, Budget , VIP, etc. Create a clean set
# such as Budget, Regular, Premium, Corporate, VIP and map everything to it.

df["Customer Segment"] = df["Customer Segment"].replace({"reg":"Regular","regular":"Regular","budget":"Budget","premium":"Premium","coroporate":"Corporate","vip":"VIP"})
df["Customer Segment"]

0         Premium
1       Corporate
2       Corporate
3         Regular
4          Budget
          ...
2020      Premium
2021      Premium
2022      Premium
2023       Budget
2024      Premium
Name: Customer Segment, Length: 2025, dtype: object

In [11]:
# 9. Fix Age column (invalid and non-numeric values)
# Explanation: Age has numbers, blanks, 30 yrs, 25 years, 45Y, and impossible values like 150
# or 100. Extract the number, convert to integer, and set unrealistic ages (e.g., <18 or >100) to
# missing.

df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")
df["Age"]

0       39.0
1       25.0
2       50.0
3       53.0
4       38.0
        ...
2020    52.0
2021    33.0
2022    48.0
2023    52.0
2024    23.0
Name: Age, Length: 2025, dtype: float64

In [12]:
df.loc[(df["Age"] < 18) | (df["Age"] > 100), "Age"] = pd.NA
df

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39.0,4,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629424,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25.0,1,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50.0,4,...,1.2,1,0,1,Credit Card,66334.52,15575.345296,50759.174704,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53.0,3,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806936,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38.0,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27 00:00:00,Hyderabad,Deluxe,Online,Premium,Other,52.0,3,...,4.0,4,1,0,Net Banking,12777.78,204.444480,12573.335520,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22 00:00:00,Hyderabad,Deluxe,Online,Premium,Male,33.0,5,...,4.7,5,1,1,Net Banking,51298.55,17574.883230,33723.666770,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11 00:00:00,Mumbai,Deluxe,Online,Premium,Male,48.0,6,...,1.3,6,1,0,Debit Card,79546.56,23108.275680,56438.284320,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24 00:00:00,Hyderabad,Executive,Travel Agent,Budget,Female,52.0,2,...,3.8,2,1,1,Debit Card,18041.10,5910.264360,12130.835640,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06 00:00:00,Mumbai,Suite,Walk-in,Premium,Male,23.0,5,...,4.8,1,1,1,Debit Card,7644.65,1025.147565,6619.502435,3428.758380,3190.744055

In [13]:
# 10. Clean Room Nights column
# Explanation: Values include numbers, N/A, 3 nights, 100, 30. Extract only the numeric part,
# convert to integer, and decide what to do with extreme values (e.g., 100 nights).

df["Room Nights"] = pd.to_numeric(df["Room Nights"],errors = "coerce")
df["Room Nights"]

0       4.0
1       1.0
2       4.0
3       3.0
4       NaN
       ...
2020    3.0
2021    5.0
2022    6.0
2023    2.0
2024    5.0
Name: Room Nights, Length: 2025, dtype: float64

In [14]:
import numpy as np
df.loc[df["Room Nights"] > 10000, "Room Nights"] = np.nan
df.loc[df["Room Nights"] <0, "Room Nights"] = np.nan
df

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39.0,4.0,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629424,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25.0,1.0,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50.0,4.0,...,1.2,1,0,1,Credit Card,66334.52,15575.345296,50759.174704,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53.0,3.0,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806936,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38.0,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27 00:00:00,Hyderabad,Deluxe,Online,Premium,Other,52.0,3.0,...,4.0,4,1,0,Net Banking,12777.78,204.444480,12573.335520,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22 00:00:00,Hyderabad,Deluxe,Online,Premium,Male,33.0,5.0,...,4.7,5,1,1,Net Banking,51298.55,17574.883230,33723.666770,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11 00:00:00,Mumbai,Deluxe,Online,Premium,Male,48.0,6.0,...,1.3,6,1,0,Debit Card,79546.56,23108.275680,56438.284320,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24 00:00:00,Hyderabad,Executive,Travel Agent,Budget,Female,52.0,2.0,...,3.8,2,1,1,Debit Card,18041.10,5910.264360,12130.835640,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06 00:00:00,Mumbai,Suite,Walk-in,Premium,Male,23.0,5.0,...,4.8,1,1,1,Debit Card,7644.65,1025.147565,6619.502435,3428.758380,3190.744055

In [15]:
# 11. Fix Room Rate (mixed formats and extreme values)
# Explanation: Room Rate contains normal numbers, 15k, $8000, 12000 INR, 100000, 250000,
# and blanks. Convert text formats to numbers, remove currency symbols, and flag or handle
# unrealistic rates.

df["Room Rate"] = df["Room Rate"].replace({"15k":15000,"$8000":8000,"12000 INR":12000,250000:250000,"":"Unknown"})
df["Room Rate"]

0        7918.62
1        4822.39
2       16583.63
3        6418.64
4        5228.46
          ...
2020     4259.26
2021       15000
2022    13257.76
2023     9020.55
2024     1528.93
Name: Room Rate, Length: 2025, dtype: object

In [16]:
df["Room Rate"] = pd.to_numeric(df["Room Rate"],errors = "coerce")
df["Room Rate"]

0        7918.62
1        4822.39
2       16583.63
3        6418.64
4        5228.46
          ...
2020     4259.26
2021    15000.00
2022    13257.76
2023     9020.55
2024     1528.93
Name: Room Rate, Length: 2025, dtype: float64

In [17]:
# 12. Clean Discount % column
# Explanation: Discount has numbers, none, 10%, 5 %, N/A, and impossible values like 120.
# Convert everything to a pure number between 0 and 100; treat “none” as 0 and values >100
# as missing or capped. 

df["Discount %"] = df["Discount %"].replace("none", 0)
df["Discount %"] = df["Discount %"].astype(str).str.extract(r"(\d+)").astype(float)
df.loc[df["Discount %"] > 100, "Discount %"] = np.nan
df

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39.0,4.0,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629424,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25.0,1.0,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50.0,4.0,...,1.2,1,0,1,Credit Card,66334.52,15575.345296,50759.174704,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53.0,3.0,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806936,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38.0,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27 00:00:00,Hyderabad,Deluxe,Online,Premium,Other,52.0,3.0,...,4.0,4,1,0,Net Banking,12777.78,204.444480,12573.335520,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22 00:00:00,Hyderabad,Deluxe,Online,Premium,Male,33.0,5.0,...,4.7,5,1,1,Net Banking,51298.55,17574.883230,33723.666770,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11 00:00:00,Mumbai,Deluxe,Online,Premium,Male,48.0,6.0,...,1.3,6,1,0,Debit Card,79546.56,23108.275680,56438.284320,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24 00:00:00,Hyderabad,Executive,Travel Agent,Budget,Female,52.0,2.0,...,3.8,2,1,1,Debit Card,18041.10,5910.264360,12130.835640,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06 00:00:00,Mumbai,Suite,Walk-in,Premium,Male,23.0,5.0,...,4.8,1,1,1,Debit Card,7644.65,1025.147565,6619.502435,3428.758380,3190.744055

In [18]:
# 13. Handle missing and invalid Rating values
# Explanation: Rating has numbers, blanks, 5/5, 4 stars, and values above 5 (e.g., 6, 9).
# Convert to a 1–5 scale and set invalid entries to missing.


df["Rating"] = df["Rating"].astype(str).str.extract(r"(\d+)").astype(float)
df.loc[df["Rating"] > 5, "Rating"] = np.nan
df["Rating"]

0       1.0
1       2.0
2       1.0
3       2.0
4       4.0
       ...
2020    4.0
2021    4.0
2022    1.0
2023    3.0
2024    4.0
Name: Rating, Length: 2025, dtype: float64

In [19]:
# 14. Clean Guests column (extreme values)
# Explanation: Most values are reasonable (1–6), but some are 15, 25, or 40. Decide a sensible
# maximum (e.g., 10) and set higher values to missing or investigate them.

df.loc[df["Guests"] > 10, "Guests"] = np.nan
df

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39.0,4.0,...,1.0,2.0,1,0,Credit Card,31674.48,2096.850576,29577.629424,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25.0,1.0,...,2.0,2.0,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50.0,4.0,...,1.0,1.0,0,1,Credit Card,66334.52,15575.345296,50759.174704,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53.0,3.0,...,2.0,6.0,0,0,Debit Card,19255.92,5328.113064,13927.806936,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38.0,NaN,...,4.0,4.0,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27 00:00:00,Hyderabad,Deluxe,Online,Premium,Other,52.0,3.0,...,4.0,4.0,1,0,Net Banking,12777.78,204.444480,12573.335520,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22 00:00:00,Hyderabad,Deluxe,Online,Premium,Male,33.0,5.0,...,4.0,5.0,1,1,Net Banking,51298.55,17574.883230,33723.666770,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11 00:00:00,Mumbai,Deluxe,Online,Premium,Male,48.0,6.0,...,1.0,6.0,1,0,Debit Card,79546.56,23108.275680,56438.284320,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24 00:00:00,Hyderabad,Executive,Travel Agent,Budget,Female,52.0,2.0,...,3.0,2.0,1,1,Debit Card,18041.10,5910.264360,12130.835640,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06 00:00:00,Mumbai,Suite,Walk-in,Premium,Male,23.0,5.0,...,4.0,1.0,1,1,Debit Card,7644.65,1025.147565,6619.502435,3428.758380,3190.744055

In [20]:
# 15. Standardize Is Member column
# Explanation: Values are mixed: 1, 0, Y, Yes, Member, blanks. Convert everything to a clear
# Yes/No or 1/0 format.

df["Is Member"] = df["Is Member"].replace({
    1: "Yes",
    "1": "Yes",
    0: "No",
    "0": "No",
    "Y": "Yes",
    "Yes": "Yes",
    "Member": "Yes",
    "": "No"
})
df["Is Member"]

0       Yes
1       Yes
2        No
3        No
4       Yes
       ...
2020    Yes
2021    Yes
2022    Yes
2023    Yes
2024    Yes
Name: Is Member, Length: 2025, dtype: object

In [21]:
# 16. Standardize Cancelled column
# Explanation: Cancelled appears as 0, 1, Yes, Y, N. Convert to a consistent 0/1 or Yes/No
# format.

df["Cancelled"] = df["Cancelled"].replace({
    "Yes": 1,
    "Y": 1,
    "N": 0
})

df["Cancelled"] = pd.to_numeric(df["Cancelled"], errors="coerce")
df["Cancelled"]

0       0.0
1       0.0
2       1.0
3       0.0
4       0.0
       ...
2020    0.0
2021    1.0
2022    0.0
2023    1.0
2024    1.0
Name: Cancelled, Length: 2025, dtype: float64

In [22]:
# 17. Clean Payment Method values
# Explanation: Payment methods have inconsistent casing and spacing (Credit Card, credit
# card, upi, Net Banking, cash , blanks). Standardize to a clean list (Credit Card, Debit Card, UPI,
# Net Banking, Cash).

df["Payment Method"] = df["Payment Method"].str.strip().str.title() 
df["Payment Method"]

0       Credit Card
1       Credit Card
2       Credit Card
3        Debit Card
4              Cash
           ...
2020    Net Banking
2021    Net Banking
2022     Debit Card
2023     Debit Card
2024     Debit Card
Name: Payment Method, Length: 2025, dtype: object

In [23]:
df["Payment Method"] = df["Payment Method"].replace("Upi", "UPI")
df["Payment Method"]

0       Credit Card
1       Credit Card
2       Credit Card
3        Debit Card
4              Cash
           ...
2020    Net Banking
2021    Net Banking
2022     Debit Card
2023     Debit Card
2024     Debit Card
Name: Payment Method, Length: 2025, dtype: object

In [41]:
# 18. Remove or flag duplicate Booking IDs
# Explanation: Some Booking IDs (e.g., BKG00042, BKG01640) appear more than once. Decide
# whether to keep the first occurrence, the most complete row, or mark them for review.

df["Duplicate_Flag"] = df.duplicated(subset="Booking ID", keep=False)

df = df.drop_duplicates(subset="Booking ID", keep="first")

print(df)

     Booking ID  Customer Name Booking Date       City  Room Type  \
0      BKG01888  Customer_1888   2025-05-17     Mumbai      Suite
1      BKG00789  Customer_0789   2025-07-29  Bengaluru      Suite
2      BKG00757  Customer_0757   2025-10-19       Pune      Suite
3      BKG01079  Customer_1079   2025-12-14     Mumbai     Deluxe
4      BKG00218  Customer_0218   2025-01-20      Delhi      Suite
...         ...            ...          ...        ...        ...
2020   BKG01738  Customer_1738   2025-11-27  Hyderabad     Deluxe
2021   BKG01193  Customer_1193   2025-10-22  Hyderabad     Deluxe
2022   BKG01210  Customer_1210   2025-07-11     Mumbai     Deluxe
2023   BKG01060  Customer_1060   2025-01-24  Hyderabad  Executive
2024   BKG00642  Customer_0642   2025-04-06     Mumbai      Suite

     Booking Channel Customer Segment  Gender   Age  Room Nights  ...  Guests  \
0             Online          Premium    Male  39.0          4.0  ...     2.0
1            Walk-in        Corporate    Male  25.0          1.0  ...     2.0
2          Corporate        Corporate   Other  50.0          4.0  ...     1.0
3            Walk-in          Regular    Male  53.0          3.0  ...     6.0
4       Travel Agent           Budget    Male  38.0          NaN  ...     4.0
...              ...              ...     ...   ...          ...  ...     ...
2020          Online          Premium   Other  52.0          3.0  ...     4.0
2021          Online          Premium    Male  33.0          5.0  ...     5.0
2022          Online          Premium    Male  48.0          6.0  ...     6.0
2023    Travel Agent           Budget  Female  52.0          2.0  ...     2.0
2024         Walk-in          Premium    Male  23.0          5.0  ...     1.0

      Is Member  Cancelled  Payment Method  Gross Amount  Discount Amount  \
0           1.0        0.0     Credit Card      31674.48      2096.850576
1           1.0        0.0     Credit Card       4822.39       735.414475
2           0.0        1.0     Credit Card      66334.52     15575.345296
3           0.0        0.0      Debit Card      19255.92      5328.113064
4           1.0        0.0            Cash      15685.38      5160.490020
...         ...        ...             ...           ...              ...
2020        1.0        0.0     Net Banking      12777.78       204.444480
2021        1.0        1.0     Net Banking      51298.55     17574.883230
2022        1.0        0.0      Debit Card      79546.56     23108.275680
2023        1.0        1.0      Debit Card      18041.10      5910.264360
2024        1.0        1.0      Debit Card       7644.65      1025.147565

      Final Amount    Hotel Cost        Profit  Duplicate_Flag
0     29577.629424  16901.386253  12676.243171           False
1      4086.975525   2746.904163   1340.071362           False
2     50759.174704  40212.657465  10546.517239           False
3     13927.806936   9639.061764   4288.745172           False
4     10524.889980   6545.581304   3979.308676           False
...            ...           ...           ...             ...
2020  12573.335520   9277.794053   3295.541467           False
2021  33723.666770  22307.978333  11415.688437           False
2022  56438.284320  36544.131723  19894.152597           False
2023  12130.835640   9683.417958   2447.417682           False
2024   6619.502435   3428.758380   3190.744055           False

[2000 rows x 23 columns]

In [25]:
# 19. Handle missing Room Type values
# Explanation: Some rows have blank Room Type. You can either drop those rows, fill with
# “Unknown”, or try to infer from other columns if possible.

df["Room Type"] = df["Room Type"].fillna("Unknown")
df["Room Type"]

0           Suite
1           Suite
2           Suite
3          Deluxe
4           Suite
          ...
2020       Deluxe
2021       Deluxe
2022       Deluxe
2023    Executive
2024        Suite
Name: Room Type, Length: 2025, dtype: object

In [26]:
df["Room Type"] = df["Room Type"].replace("", "Unknown")
df["Room Type"]

0           Suite
1           Suite
2           Suite
3          Deluxe
4           Suite
          ...
2020       Deluxe
2021       Deluxe
2022       Deluxe
2023    Executive
2024        Suite
Name: Room Type, Length: 2025, dtype: object

In [27]:
# 20. Fix inconsistent Final Amount calculations
# Explanation: Final Amount should roughly equal Gross Amount − Discount Amount, but
# some rows have missing Final Amount or clear calculation errors. Recalculate or flag
# inconsistencies.


df["Final Amount"] = df["Gross Amount"] - df["Discount Amount"]
df["Final Amount"]

0       29577.629424
1        4086.975525
2       50759.174704
3       13927.806936
4       10524.889980
            ...
2020    12573.335520
2021    33723.666770
2022    56438.284320
2023    12130.835640
2024     6619.502435
Name: Final Amount, Length: 2025, dtype: float64

In [28]:
df["Final Amount"] = df["Final Amount"].fillna(
    df["Gross Amount"] - df["Discount Amount"]
)
df["Final Amount"]

0       29577.629424
1        4086.975525
2       50759.174704
3       13927.806936
4       10524.889980
            ...
2020    12573.335520
2021    33723.666770
2022    56438.284320
2023    12130.835640
2024     6619.502435
Name: Final Amount, Length: 2025, dtype: float64

In [29]:
# 21. Clean Customer Name (placeholder and invalid names)
# Explanation: Names include Customer_1888, 12345, john doe, N/A, blanks. Decide how to
# treat non-real names (keep as-is, replace with “Unknown”, or drop).


df["Customer Name"] = df["Customer Name"].replace(["N/A", ""], "Unknown")
df.loc[df["Customer Name"].astype(str).str.isnumeric(), "Customer Name"] = "Unknown"
df["Customer Name"]

0       Customer_1888
1       Customer_0789
2       Customer_0757
3       Customer_1079
4       Customer_0218
            ...
2020    Customer_1738
2021    Customer_1193
2022    Customer_1210
2023    Customer_1060
2024    Customer_0642
Name: Customer Name, Length: 2025, dtype: object

In [30]:
# 22. Convert all numeric columns to proper numeric data types
# Explanation: Many columns that should be numbers are currently stored as text because of
# mixed formats. Convert them to integer or float so calculations work correctly.


df = df.apply(pd.to_numeric, errors="ignore")

C:\Users\Shree\AppData\Local\Temp\ipykernel_20968\3158174803.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

In [31]:
# 23. Handle missing values in key financial columns (Gross Amount, Discount Amount, Final
# Amount, Profit)
# Explanation: Some financial columns have blanks. Decide whether to drop those rows, fill
# with 0, or calculate missing values from other columns when possible.

cols = ["Gross Amount", "Discount Amount", "Final Amount", "Profit"]

df[cols] = df[cols].fillna(0)
df[cols]

      Gross Amount  Discount Amount  Final Amount        Profit
0         31674.48      2096.850576  29577.629424  12676.243171
1          4822.39       735.414475   4086.975525   1340.071362
2         66334.52     15575.345296  50759.174704  10546.517239
3         19255.92      5328.113064  13927.806936   4288.745172
4         15685.38      5160.490020  10524.889980   3979.308676
...            ...              ...           ...           ...
2020      12777.78       204.444480  12573.335520   3295.541467
2021      51298.55     17574.883230  33723.666770  11415.688437
2022      79546.56     23108.275680  56438.284320  19894.152597
2023      18041.10      5910.264360  12130.835640   2447.417682
2024       7644.65      1025.147565   6619.502435   3190.744055

[2025 rows x 4 columns]

In [32]:
# 24. Remove rows with completely invalid dates
# Explanation: Dates like 32/13/2025 are impossible. Identify and either remove those rows or
# set the date to missing.

df.columns = df.columns.str.strip()
df["Booking Date"] = pd.to_datetime(df["Booking Date"], errors="coerce")
df["Booking Date"]

0      2025-05-17
1      2025-07-29
2      2025-10-19
3      2025-12-14
4      2025-01-20
          ...
2020   2025-11-27
2021   2025-10-22
2022   2025-07-11
2023   2025-01-24
2024   2025-04-06
Name: Booking Date, Length: 2025, dtype: datetime64[ns]

In [33]:
# 25. Standardize boolean-like columns (Is Member and Cancelled) to the same format
# Explanation: Keeping both columns in the same style (both 0/1 or both Yes/No) makes
# filtering and analysis much easier and less error-prone.

df["Is Member"] = df["Is Member"].replace({"Yes": 1, "Y": 1, "Member": 1, "No": 0})
df["Cancelled"] = df["Cancelled"].replace({"Yes": 1, "Y": 1, "No": 0})

df["Is Member"] = pd.to_numeric(df["Is Member"], errors="coerce")
df["Cancelled"] = pd.to_numeric(df["Cancelled"], errors="coerce")

print(df["Is Member"])
print(df["Cancelled"])

0       1.0
1       1.0
2       0.0
3       0.0
4       1.0
       ...
2020    1.0
2021    1.0
2022    1.0
2023    1.0
2024    1.0
Name: Is Member, Length: 2025, dtype: float64
0       0.0
1       0.0
2       1.0
3       0.0
4       0.0
       ...
2020    0.0
2021    1.0
2022    0.0
2023    1.0
2024    1.0
Name: Cancelled, Length: 2025, dtype: float64

In [34]:
# 26. Trim extra spaces from all text columns
# Explanation: Many text fields have leading/trailing spaces (e.g., "Budget ", "Mumbai ").
# Removing them prevents “Budget” and “Budget ” from being treated as different categories.

df.columns = df.columns.str.strip()
df.columns

Index(['Booking ID', 'Customer Name', 'Booking Date', 'City', 'Room Type',
       'Booking Channel', 'Customer Segment', 'Gender', 'Age', 'Room Nights',
       'Room Rate', 'Discount %', 'Rating', 'Guests', 'Is Member', 'Cancelled',
       'Payment Method', 'Gross Amount', 'Discount Amount', 'Final Amount',
       'Hotel Cost', 'Profit'],
      dtype='object')

In [39]:
# 27. Fix extreme or impossible Age values
# Explanation: Ages such as 150, 120, or 100 are unrealistic for hotel customers. Set a
# reasonable range (e.g., 18–90) and replace values outside it with missing.


df.loc[(df["Age"] < 18) | (df["Age"] > 90), "Age"] = np.nan
df["Age"]

0       39.0
1       25.0
2       50.0
3       53.0
4       38.0
        ...
2020    52.0
2021    33.0
2022    48.0
2023    52.0
2024    23.0
Name: Age, Length: 2025, dtype: float64

In [36]:
# 28. Handle missing Gender values
# Explanation: Some rows have blank Gender. You can fill with “Unknown”, drop the rows, or
# leave them as missing depending on your analysis needs.


df4= pd.read_csv("C:\\Users\\Shree\\Downloads\\Hotel_booking_dataset.csv")
df4

df4["Gender"] = df4["Gender"].replace(" ","Unknown")
df4["Gender"]

0         Male
1         Male
2        Other
3         Male
4         Male
         ...
2020     Other
2021      Male
2022      Male
2023    Female
2024      Male
Name: Gender, Length: 2025, dtype: object

In [37]:
# 29. Correct obvious typos in categorical columns
# Explanation: Examples include delux → Deluxe, exec → Executive, Hydrabad → Hyderabad,
# Bangalore → Bengaluru. Fixing these improves grouping and reporting accuracy.


df4 = df4.replace({
    "delux": "Deluxe",
    "exec": "Executive",
    "Hydrabad": "Hyderabad",
    "Bangalore": "Bengaluru"
})
df4

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39,4,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629424,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25,1,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50,4,...,1.2,1,0,1,Credit Card,66334.52,15575.345296,50759.174704,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53,3,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806936,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27 00:00:00,Hyderabad,Deluxe,Online,Premium,Other,52,3,...,4.0,4,1,0,Net Banking,12777.78,204.444480,12573.335520,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22 00:00:00,Hyderabad,Deluxe,Online,Premium,Male,33,5,...,4.7,5,1,1,Net Banking,51298.55,17574.883230,33723.666770,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11 00:00:00,Mumbai,Deluxe,Online,Premium,Male,48,6,...,1.3,6,1,0,Debit Card,79546.56,23108.275680,56438.284320,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24 00:00:00,Hyderabad,Executive,Travel Agent,Budget,Female,52,2,...,3.8,2,1,1,Debit Card,18041.10,5910.264360,12130.835640,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06 00:00:00,Mumbai,Suite,Walk-in,Premium,Male,23,5,...,4.8,1,1,1,Debit Card,7644.65,1025.147565,6619.502435,3428.758380,3190.744055

In [38]:
# 30. Decide how to treat rows with too many missing values
# Explanation: Some rows are missing Customer Name, City, Room Type, Age, and other
# important fields at the same time. Decide a threshold (e.g., more than 40% missing) and
# drop or flag those incomplete rows.

df4 = df4.dropna(thresh=int(df4.shape[1] * 0.6))
df4

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39,4,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629424,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25,1,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50,4,...,1.2,1,0,1,Credit Card,66334.52,15575.345296,50759.174704,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53,3,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806936,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27 00:00:00,Hyderabad,Deluxe,Online,Premium,Other,52,3,...,4.0,4,1,0,Net Banking,12777.78,204.444480,12573.335520,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22 00:00:00,Hyderabad,Deluxe,Online,Premium,Male,33,5,...,4.7,5,1,1,Net Banking,51298.55,17574.883230,33723.666770,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11 00:00:00,Mumbai,Deluxe,Online,Premium,Male,48,6,...,1.3,6,1,0,Debit Card,79546.56,23108.275680,56438.284320,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24 00:00:00,Hyderabad,Executive,Travel Agent,Budget,Female,52,2,...,3.8,2,1,1,Debit Card,18041.10,5910.264360,12130.835640,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06 00:00:00,Mumbai,Suite,Walk-in,Premium,Male,23,5,...,4.8,1,1,1,Debit Card,7644.65,1025.147565,6619.502435,3428.758380,3190.744055