# Basic Cleaning

In [59]:
# 1. Load the CSV file using Pandas and display the first 10 rows.

import pandas as pd

df = pd.read_csv("C:\\Users\\Shree\\Downloads\\messy_customer_loan_dataset.csv") 
df

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,477723.0,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,65.0,1394481.0,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,45.0,543340.0,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [60]:
# 2. Display the number of rows and columns in the dataset.

df.shape

(1535, 15)

In [61]:
# 3. Display all column names and identify which column names have
# leading/trailing spaces.

df.columns

Index([' Customer ID ', 'Age ', 'Annual Income', 'credit Score ',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment ', 'loan_type', 'Loan Amount (INR)', 'tenure Months',
       'Monthly Visits ', 'debt_to_income', 'Loan Approved?'],
      dtype='object')

In [62]:
#4. Clean all column names by removing extra spaces and converting them into a
# consistent format such as snake_case.

df.columns = df.columns.str.strip()
df.columns

Index(['Customer ID', 'Age', 'Annual Income', 'credit Score',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan Amount (INR)', 'tenure Months',
       'Monthly Visits', 'debt_to_income', 'Loan Approved?'],
      dtype='object')

In [63]:
df.columns = df.columns.str.lower()
df.columns

Index(['customer id', 'age', 'annual income', 'credit score',
       'employment-type', 'education  level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan amount (inr)', 'tenure months',
       'monthly visits', 'debt_to_income', 'loan approved?'],
      dtype='object')

In [64]:
df.columns = df.columns.str.replace(" ","_")
df.columns

Index(['customer_id', 'age', 'annual_income', 'credit_score',
       'employment-type', 'education__level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan_amount_(inr)', 'tenure_months',
       'monthly_visits', 'debt_to_income', 'loan_approved?'],
      dtype='object')

In [65]:
#5. Check the data type of every column.

df.dtypes

customer_id          object
age                  object
annual_income        object
credit_score         object
employment-type      object
education__level     object
marital_status       object
city                 object
customer_segment     object
loan_type            object
loan_amount_(inr)    object
tenure_months         int64
monthly_visits       object
debt_to_income       object
loan_approved?       object
dtype: object

In [66]:
#6. Find the total number of missing values in each column.

missing_value = df.isnull().sum()
missing_value

customer_id            0
age                   71
annual_income         84
credit_score          77
employment-type       60
education__level      46
marital_status         0
city                  52
customer_segment       0
loan_type              0
loan_amount_(inr)    102
tenure_months          0
monthly_visits        55
debt_to_income        89
loan_approved?         0
dtype: int64

In [67]:
#7. Find the percentage of missing values in each column.

missing_per = missing_value / len(df) * 100
missing_per

customer_id          0.000000
age                  4.625407
annual_income        5.472313
credit_score         5.016287
employment-type      3.908795
education__level     2.996743
marital_status       0.000000
city                 3.387622
customer_segment     0.000000
loan_type            0.000000
loan_amount_(inr)    6.644951
tenure_months        0.000000
monthly_visits       3.583062
debt_to_income       5.798046
loan_approved?       0.000000
dtype: float64

In [68]:
# 8. Find all rows where Age is missing.
df["age"] = df["age"].isnull()
df["age"]

0       False
1       False
2       False
3       False
4       False
        ...
1530    False
1531    False
1532    False
1533    False
1534    False
Name: age, Length: 1535, dtype: bool

In [69]:
# 9. Find all rows where Annual Income is missing.

df["annual_income"] = df["annual_income"].isnull().sum()
df["annual_income"]

0       84
1       84
2       84
3       84
4       84
        ..
1530    84
1531    84
1532    84
1533    84
1534    84
Name: annual_income, Length: 1535, dtype: int64

In [70]:
# 10.Remove completely duplicate rows and report how many duplicate rows were
# removed.

df.duplicated().sum()

np.int64(35)

In [71]:
df.drop_duplicates()

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,False,84,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

# Data Type & Invalid Values

In [72]:
# 11.The Age column contains numbers as well as values like "unknown" and
# "twenty five". Clean this column and convert it into a proper numeric column.


df["age"] = pd.to_numeric(df["age"],errors = "coerce")
df["age"]

0       False
1       False
2       False
3       False
4       False
        ...
1530    False
1531    False
1532    False
1533    False
1534    False
Name: age, Length: 1535, dtype: bool

In [73]:
# 12.The Annual Income column contains values such as 650000 INR, ₹720000,
# 1.2L, and N/A. Clean the column and convert the valid values into numeric
# format.

df["annual_income"] = df["annual_income"].astype(str)
df["annual_income"]

0       84
1       84
2       84
3       84
4       84
        ..
1530    84
1531    84
1532    84
1533    84
1534    84
Name: annual_income, Length: 1535, dtype: object

In [74]:
df["aanual_income"] = df["annual_income"].str.replace("INR"," ")
df["annual_income"] = df["annual_income"].str.replace("," , " ")
df["annual_income"] = df["annual_income"].str.replace("₹", " ")
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [75]:
df["annual_income"] = df["annual_income"].str.strip()
df["annual_income"]

0       84
1       84
2       84
3       84
4       84
        ..
1530    84
1531    84
1532    84
1533    84
1534    84
Name: annual_income, Length: 1535, dtype: object

In [76]:
df["annual_income"] = pd.to_numeric(df["annual_income"],errors = "coerce")
df["annual_income"]

0       84
1       84
2       84
3       84
4       84
        ..
1530    84
1531    84
1532    84
1533    84
1534    84
Name: annual_income, Length: 1535, dtype: int64

In [77]:
#13.Clean the Credit Score column and identify values that cannot be converted
# into numbers.

df["credit_score"] = df["credit_score"].astype(str)
df["credit_score"]

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531        0
1532    686.0
1533    720.0
1534    731.0
Name: credit_score, Length: 1535, dtype: object

In [78]:
df["credit_score"] = df["credit_score"].str.strip()
df["credit_score"]

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531        0
1532    686.0
1533    720.0
1534    731.0
Name: credit_score, Length: 1535, dtype: object

In [79]:
df["credit_score"] = df["credit_score"].str.replace("pts"," ")
df["credit_score"]

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531        0
1532    686.0
1533    720.0
1534    731.0
Name: credit_score, Length: 1535, dtype: object

In [80]:
df["credit_score"] = df["credit_score"].str.replace("score:"," ")
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [81]:
df["credit_score"] = pd.to_numeric(df["credit_score"],errors = "coerce")
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [82]:
# 14.The Loan Amount column contains currency symbols, text, and numeric
# values. Remove the unwanted characters and convert it into numeric format.

df["loan_amount_(inr)"] = df["loan_amount_(inr)"].str.replace("INR"," ")
df["loan_amount_(inr)"] = df["loan_amount_(inr)"].str.replace("," , " ")
df["loan_amount_(inr)"] = df["loan_amount_(inr)"].str.replace("₹", " ")
df["loan_amount_(inr)"] = df["loan_amount_(inr)"].str.replace("USD", " ")
df["loan_amount_(inr)"] = df["loan_amount_(inr)"].str.strip()

df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [83]:
df["loan_amount_(inr)"] = pd.to_numeric(df["loan_amount_(inr)"],errors = "coerce")
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [84]:
#15.The Monthly Visits column contains values such as "five", "N/A", and "-".
# Convert valid values into numeric values and handle invalid values.

df["monthly_visits"] = df["monthly_visits"].astype(str).str.strip().str.lower()
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,nan,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [85]:
convert = {"one":1,"two":2,"three":3,"four": 4,"five":5}
df["monthly_visits"] = df["monthly_visits"].replace(convert)
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,nan,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [86]:
df["monthly_visits"] = pd.to_numeric(df["monthly_visits"],errors ="coerce")
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [87]:
#16.Clean the Debt to Income column where some values are written like 35%
# and 0.4x. Convert the valid values into a consistent numeric format.

df["debt_to_income"] = df["debt_to_income"].astype(str).str.strip().str.lower()
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,nan,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [88]:
df["debt_to_income"] = df["debt_to_income"].str.replace("%"," ")
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,nan,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [89]:
df["debt_to_income"] =df["debt_to_income"].str.replace("x"," ")
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,nan,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No,84

In [90]:
# 17.After cleaning the numerical columns, check which columns are still stored as
# object data type.

df.dtypes

customer_id           object
age                     bool
annual_income          int64
credit_score         float64
employment-type       object
education__level      object
marital_status        object
city                  object
customer_segment      object
loan_type             object
loan_amount_(inr)    float64
tenure_months          int64
monthly_visits       float64
debt_to_income        object
loan_approved?        object
aanual_income         object
dtype: object

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1535 entries, 0 to 1534
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1535 non-null   object
 1   age                1535 non-null   bool
 2   annual_income      1535 non-null   int64
 3   credit_score       1438 non-null   float64
 4   employment-type    1475 non-null   object
 5   education__level   1489 non-null   object
 6   marital_status     1535 non-null   object
 7   city               1483 non-null   object
 8   customer_segment   1535 non-null   object
 9   loan_type          1535 non-null   object
 10  loan_amount_(inr)  1417 non-null   float64
 11  tenure_months      1535 non-null   int64
 12  monthly_visits     1468 non-null   float64
 13  debt_to_income     1535 non-null   object
 14  loan_approved?     1535 non-null   object
 15  aanual_income      1535 non-null   object
dtypes: bool(1), float64(3), int64(2), object(10)
memory usage: 181.5+ KB

# Categorical Cleaning

In [92]:
# 18.Find all unique values in the Employment-Type column.

df.columns

Index(['customer_id', 'age', 'annual_income', 'credit_score',
       'employment-type', 'education__level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan_amount_(inr)', 'tenure_months',
       'monthly_visits', 'debt_to_income', 'loan_approved?', 'aanual_income'],
      dtype='object')

In [93]:
df["employment-type"].unique()

array(['Self-Employed', 'Contract', 'Salaried', ' SALARIED ',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

In [94]:
# 19.Standardize the Employment-Type column so that values such as salaried,
# SALARIED, and Salaried become one consistent value.

df["employment-type"] =df["employment-type"].replace({"salaried":"SALARIED"})
df["employment-type"]

0       Self-Employed
1            Contract
2       Self-Employed
3            Salaried
4       Self-Employed
            ...
1530    Self-Employed
1531    Self-Employed
1532         Contract
1533         Business
1534         Salaried
Name: employment-type, Length: 1535, dtype: object

In [95]:
# 20.Clean the Education Level column and make values such as graduate,
# GRADUATE, and Graduate consistent.

df["education__level"] = df["education__level"].replace({"graduate":"GRADUATE"})
df["education__level"]

0               12th
1           Graduate
2       Postgraduate
3           Graduate
4           Graduate
            ...
1530        Graduate
1531            12th
1532           Other
1533        Graduate
1534    Postgraduate
Name: education__level, Length: 1535, dtype: object

In [99]:
# 21.Clean the City column. Identify incorrect or inconsistent values such as
# hyderbad, Hyd, Bangalore, and Bengaluru.

df["city"].replace({"Hyderabad":"hyd",
                                 "Mumbai" :"mumbai",
                                 "Jaipur": "jaipur",
                                 "Kolkata" : "kolkata",
                                 "Delhi" :"delhi",
                                 "Pune" : "pune",
                                 "Chennai" :"chennai"},inplace = True)
df

C:\Users\Shree\AppData\Local\Temp\ipykernel_9628\2614301787.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["city"].replace({"Hyderabad":"hyd",

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,mumbai,mass,Education,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,jaipur,premium,Auto,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,kolkata,affluent,Auto,892792.0,84,4.0,nan,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,kolkata,premium,Home,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,hyd,mass,Education,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,jaipur,mass,Personal,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,delhi,mass,Personal,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,pune,mass,Education,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,chennai,affluent,Education,753995.0,12,5.0,0.259,No,84

In [97]:
# 22.Find all unique values in the Customer Segment column and identify invalid
# categories.

df["customer_segment"] = df["customer_segment"].str.strip().str.lower()
df["customer_segment"]

0           mass
1        premium
2       affluent
3        premium
4           mass
          ...
1530        mass
1531        mass
1532        mass
1533        mass
1534    affluent
Name: customer_segment, Length: 1535, dtype: object

In [103]:
# 23.Clean the Loan Type column so that values such as personal, PERSONAL,
# and personal loan are standardized.

df["loan_type"].replace({
                         "Education" : "EDUCATION",
                         "Auto" : "AUTO",
                         "Home":"HOME",
                         "Home Loan":"HOME LOAN",
                        "Personal": "PERSONAL"},inplace = True)
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,mumbai,mass,EDUCATION,378342.0,60,3.0,0.258,No,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,jaipur,premium,AUTO,751792.0,48,11.0,0.558,Yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,kolkata,affluent,AUTO,892792.0,84,4.0,nan,Yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,kolkata,premium,HOME,908250.0,84,10.0,0.356,Yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,hyd,mass,EDUCATION,386370.0,72,4.0,0.169,Yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,jaipur,mass,HOME LOAN,1106455.0,48,NaN,0.569,No,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,jaipur,mass,PERSONAL,222828.0,120,8.0,0.344,Yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,delhi,mass,PERSONAL,50000000.0,36,9.0,0.084,Yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,pune,mass,EDUCATION,302389.0,72,9.0,0.089,No,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,chennai,affluent,EDUCATION,753995.0,12,5.0,0.259,No,84

In [105]:
#24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No,
#  NO, N, and 0. Convert them into only Yes/No.

df["loan_approved?"].replace({ "Yes":"yes",
                               "No" : "NO",
                               "Y" : 1,
                               "N" : 0},inplace = True)
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,mumbai,mass,EDUCATION,378342.0,60,3.0,0.258,NO,84
1,CUST100077,False,84,874.0,Contract,Graduate,Single,jaipur,premium,AUTO,751792.0,48,11.0,0.558,yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,kolkata,affluent,AUTO,892792.0,84,4.0,nan,yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,kolkata,premium,HOME,908250.0,84,10.0,0.356,yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,hyd,mass,EDUCATION,386370.0,72,4.0,0.169,yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,jaipur,mass,HOME LOAN,1106455.0,48,NaN,0.569,NO,84
1531,CUST101295,False,84,0.0,Self-Employed,12th,Single,jaipur,mass,PERSONAL,222828.0,120,8.0,0.344,yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,delhi,mass,PERSONAL,50000000.0,36,9.0,0.084,yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,pune,mass,EDUCATION,302389.0,72,9.0,0.089,NO,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,chennai,affluent,EDUCATION,753995.0,12,5.0,0.259,NO,84

# Outliers & Data Validation

In [ ]:
# 25.Check the Age column and identify unrealistic ages such as negative ages or
# ages above 100.

import numpy as np

df["age"] = [age if (0<= age <=120) else np.nan for age in df["age"]]
df["age"]

In [118]:
# 26.Check the Credit Score column and identify values outside the valid credit-
# score range.
import numpy as np

df["credit_score"] = [score if (300 <= score <= 850) else np.nan for score in df["credit_score"]]
df["credit_score"]

0       698.0
1         NaN
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531      NaN
1532    686.0
1533    720.0
1534    731.0
Name: credit_score, Length: 1535, dtype: float64

In [113]:
# 27.Detect outliers in Annual Income using the IQR method.



Q3 = df["annual_income"].quantile(0.25)
Q1 = df["annual_income"].quantile(0.25)

IQR = Q3 - Q1

lowerbond = Q1 - 1.5 * IQR
upperbond = Q3 + 1.5 * IQR

outliers = df[(df["annual_income"] < lowerbond) | (df["annual_income"] > upperbond)]
print(lowerbond)
print(upperbond)
print(outliers)

84.0
84.0
Empty DataFrame
Columns: [customer_id, age, annual_income, credit_score, employment-type, education__level, marital_status, city, customer_segment, loan_type, loan_amount_(inr), tenure_months, monthly_visits, debt_to_income, loan_approved?, aanual_income]
Index: []

In [115]:
# 28.Detect outliers in Loan Amount using the IQR method.

Q3 = df["loan_amount_(inr)"].quantile(0.25)
Q1 = df["loan_amount_(inr)"].quantile(0.25)

IQR = Q3 - Q1

lowerbond = Q1 - 1.5 * IQR
upperbond = Q3 + 1.5 * IQR

outliers = df[(df["loan_amount_(inr)"] < lowerbond) |(df["loan_amount_(inr)"]>upperbond)]
print(lowerbond)
print(upperbond)
print(outliers)

281062.0
281062.0
     customer_id    age  annual_income  credit_score employment-type  \
0     CUST101160  False             84         698.0   Self-Employed
1     CUST100077  False             84         874.0        Contract
2     CUST100317  False             84         661.0   Self-Employed
3     CUST101041  False             84         722.0        Salaried
4     CUST101358  False             84         727.0   Self-Employed
...          ...    ...            ...           ...             ...
1530  CUST101131  False             84         719.0   Self-Employed
1531  CUST101295  False             84           0.0   Self-Employed
1532  CUST100861  False             84         686.0        Contract
1533  CUST101460  False             84         720.0        Business
1534  CUST101127  False             84         731.0        Salaried

     education__level marital_status     city customer_segment  loan_type  \
0                12th        Married   mumbai             mass  EDUCATION
1            Graduate         Single   jaipur          premium       AUTO
2        Postgraduate        Married  kolkata         affluent       AUTO
3            Graduate         Single  kolkata          premium       HOME
4            Graduate        Married      hyd             mass  EDUCATION
...               ...            ...      ...              ...        ...
1530         Graduate         Single   jaipur             mass  HOME LOAN
1531             12th         Single   jaipur             mass   PERSONAL
1532            Other        Married    delhi             mass   PERSONAL
1533         Graduate        Married     pune             mass  EDUCATION
1534     Postgraduate         Single  chennai         affluent  EDUCATION

      loan_amount_(inr)  tenure_months  monthly_visits debt_to_income  \
0              378342.0             60             3.0          0.258
1              751792.0             48            11.0          0.558
2              892792.0             84             4.0            nan
3              908250.0             84            10.0          0.356
4              386370.0             72             4.0          0.169
...                 ...            ...             ...            ...
1530          1106455.0             48             NaN          0.569
1531           222828.0            120             8.0          0.344
1532         50000000.0             36             9.0          0.084
1533           302389.0             72             9.0          0.089
1534           753995.0             12             5.0          0.259

     loan_approved? aanual_income
0                NO            84
1               yes            84
2               yes            84
3               yes            84
4               yes            84
...             ...           ...
1530             NO            84
1531            yes            84
1532            yes            84
1533             NO            84
1534             NO            84

[1416 rows x 16 columns]

In [134]:
# 29.Check the Debt to Income column and identify impossible values such as
# negative values or values greater than 1.

df["debt_to_income"] = pd.to_numeric(df["debt_to_income"],errors = "coerce")
df
df[df(["debt_to_income"]<0) | (df["debt_to_income"]>1)

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,mumbai,mass,EDUCATION,378342.0,60,3.0,0.258,NO,84
1,CUST100077,False,84,NaN,Contract,Graduate,Single,jaipur,premium,AUTO,751792.0,48,11.0,0.558,yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,kolkata,affluent,AUTO,892792.0,84,4.0,NaN,yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,kolkata,premium,HOME,908250.0,84,10.0,0.356,yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,hyd,mass,EDUCATION,386370.0,72,4.0,0.169,yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,jaipur,mass,HOME LOAN,1106455.0,48,NaN,0.569,NO,84
1531,CUST101295,False,84,NaN,Self-Employed,12th,Single,jaipur,mass,PERSONAL,222828.0,120,8.0,0.344,yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,delhi,mass,PERSONAL,50000000.0,36,9.0,0.084,yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,pune,mass,EDUCATION,302389.0,72,9.0,0.089,NO,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,chennai,affluent,EDUCATION,753995.0,12,5.0,0.259,NO,84

In [119]:
# 30.Final cleaning task: Create a completely cleaned version of the dataset by:
# • Cleaning column names
# • Removing duplicates
# • Handling missing values
# • Fixing data types
# • Cleaning numerical columns
# • Standardizing categorical values
# • Handling invalid values
# • Detecting and treating outliers
# • Checking the final dataset for remaining errors

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['customer_id', 'age', 'annual_income', 'credit_score',
       'employment-type', 'education__level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan_amount_(inr)', 'tenure_months',
       'monthly_visits', 'debt_to_income', 'loan_approved?', 'aanual_income'],
      dtype='object')

In [125]:
df.drop_duplicates()

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,aanual_income
0,CUST101160,False,84,698.0,Self-Employed,12th,Married,mumbai,mass,EDUCATION,378342.0,60,3.0,0.258,NO,84
1,CUST100077,False,84,NaN,Contract,Graduate,Single,jaipur,premium,AUTO,751792.0,48,11.0,0.558,yes,84
2,CUST100317,False,84,661.0,Self-Employed,Postgraduate,Married,kolkata,affluent,AUTO,892792.0,84,4.0,nan,yes,84
3,CUST101041,False,84,722.0,Salaried,Graduate,Single,kolkata,premium,HOME,908250.0,84,10.0,0.356,yes,84
4,CUST101358,False,84,727.0,Self-Employed,Graduate,Married,hyd,mass,EDUCATION,386370.0,72,4.0,0.169,yes,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,False,84,719.0,Self-Employed,Graduate,Single,jaipur,mass,HOME LOAN,1106455.0,48,NaN,0.569,NO,84
1531,CUST101295,False,84,NaN,Self-Employed,12th,Single,jaipur,mass,PERSONAL,222828.0,120,8.0,0.344,yes,84
1532,CUST100861,False,84,686.0,Contract,Other,Married,delhi,mass,PERSONAL,50000000.0,36,9.0,0.084,yes,84
1533,CUST101460,False,84,720.0,Business,Graduate,Married,pune,mass,EDUCATION,302389.0,72,9.0,0.089,NO,84
1534,CUST101127,False,84,731.0,Salaried,Postgraduate,Single,chennai,affluent,EDUCATION,753995.0,12,5.0,0.259,NO,84

In [128]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1530    False
1531    False
1532    False
1533    False
1534    False
Length: 1535, dtype: bool

In [129]:
df.dtypes

customer_id           object
age                     bool
annual_income          int64
credit_score         float64
employment-type       object
education__level      object
marital_status        object
city                  object
customer_segment      object
loan_type             object
loan_amount_(inr)    float64
tenure_months          int64
monthly_visits       float64
debt_to_income        object
loan_approved?        object
aanual_income         object
dtype: object

In [131]:
df.describe()

,annual_income,credit_score,loan_amount_(inr),tenure_months,monthly_visits
count,1535.0,1389.000000,1.417000e+03,1535.000000,1468.000000
mean,84.0,714.768179,1.022389e+06,56.685342,5.668937
std,0.0,59.449136,6.868144e+06,32.249021,9.031910
min,84.0,525.000000,1.000000e+02,12.000000,-5.000000
25%,84.0,674.000000,2.810620e+05,24.000000,3.000000
50%,84.0,716.000000,4.440660e+05,60.000000,5.000000
75%,84.0,758.000000,6.934220e+05,72.000000,6.000000
max,84.0,849.000000,1.200000e+08,120.000000,150.000000

In [132]:
for col in df.select_dtypes(include = ["object","category"]).columns:
    print(df[col].unique())

['CUST101160' 'CUST100077' 'CUST100317' ... 'CUST100861' 'CUST101460'
 'CUST101127']
['Self-Employed' 'Contract' 'Salaried' ' SALARIED ' 'Self employed'
 'Business' nan 'Unknown' 'self-employed' 'SALARIED']
['12th' 'Graduate' 'Postgraduate' 'Diploma' nan 'Post Graduate' 'Other'
 ' GRADUATE' 'postgraduate ' 'GRADUATE']
['Married' 'Single' 'M' 'Divorced' ' MARRIED ' 'unknown' 'Single '
 'married']
['mumbai' 'jaipur' 'kolkata' 'hyd' 'chennai' 'Bengaluru' nan 'delhi'
 'pune' 'MUMBAI' 'Hyd' 'mumbai ' 'Bangalore' ' Bengaluru ' 'hyderbad']
['mass' 'premium' 'affluent' 'sme' 'unknown' 'high value']
['EDUCATION' 'AUTO' 'HOME' 'PERSONAL' 'Business' 'personal loan'
 'HOME LOAN' 'auto ' 'Unknown']
['0.258' '0.558' 'nan' '0.356' '0.169' '0.46' '0.323' '0.233' '0.375'
 '0.394' '0.476' '0.487' '0.494' '0.364' '0.529' '0.564' '0.303' '0.386'
 '0.177' '0.353' '0.657' '0.234' '0.195' '0.333' '0.485' '0.42' '0.4 '
 '0.231' '-0.2' '0.291' '0.366' '0.449' '0.397' '0.287' '0.508' '0.533'
 '1.2' '0.112' '0.327' '0.348' '0.079' '0.328' '0.653' '0.228' '0.361'
 '0.164' '0.538' '0.381' '0.274' '0.741' '0.357' '0.317' '0.02' '0.419'
 '0.341' '0.304' '0.3' '0.32' '0.555' '0.44' '0.552' '0.259' '0.377'
 '0.331' '0.083' '0.619' '0.418' '9.0' '0.617' '0.246' '0.238' '0.308'
 '0.645' '0.723' '0.354' '0.682' '0.167' '0.457' '0.31' '0.368' '0.181'
 '0.241' '0.413' '0.048' '0.268' '0.441' '0.133' '0.365' '0.402' '0.276'
 '0.158' '0.352' '0.553' '0.279' '0.722' '0.193' '0.102' '0.622' '3.5'
 '0.629' '0.416' '0.199' '0.513' '0.215' '0.334' '0.29' '0.282' '0.608'
 '0.426' '0.35' '0.115' '0.343' '35 ' '0.495' '0.444' '0.172' '0.596'
 '0.173' '0.2' '0.252' '0.398' '0.399' '0.031' '0.313' '0.211' '0.236'
 '0.423' '0.424' '0.292' '0.261' '0.183' '0.683' '0.285' '0.321' '0.4'
 '0.445' '0.464' '0.256' '0.165' '0.408' '0.237' '0.521' '0.094' '0.383'
 '0.157' '0.296' '0.134' '0.182' '0.637' '0.483' '0.493' '0.455' '0.16'
 '0.251' '0.213' '0.288' '0.509' '0.107' '0.243' '0.422' '0.325' '0.224'
 '0.283' '0.36' '0.401' '0.728' '0.492' '0.216' '0.209' '0.175' '0.545'
 '0.119' '0.139' '0.524' '0.324' '0.373' '0.561' '0.219' '0.09' '0.153'
 '0.459' '0.403' '0.551' '0.454' '0.319' '0.514' '0.272' '0.411' '0.128'
 '0.125' '0.489' '0.143' '0.523' '0.436' '0.269' '0.098' '0.548' '0.574'
 '0.472' '0.137' '0.189' '0.567' '0.142' '0.446' '0.433' '0.388' '0.415'
 '0.254' '0.186' '0.203' '0.477' '0.51' '0.267' '0.166' '0.369' '0.121'
 '0.147' '0.271' '0.469' '0.486' '0.473' '0.439' '0.748' '0.322' '0.136'
 '0.275' '0.295' '0.212' '0.501' '0.382' '0.479' '0.065' '0.226' '0.385'
 '0.38' '0.468' '0.185' '0.318' '0.539' '0.5' '0.421' '0.198' '0.248'
 '0.171' '0.289' '0.431' '0.581' '0.478' '0.432' '0.335' '0.652' '0.097'
 '0.435' '0.376' 'unknown' '0.355' '0.338' '0.222' '0.425' '0.427' '0.515'
 '0.417' '0.103' '0.404' '0.559' '0.384' '0.14' '0.18' '0.488' '0.148'
 '0.161' '0.229' '0.249' '0.387' '0.526' '0.344' '0.371' '0.255' '0.096'
 '0.124' '0.178' '0.482' '0.311' '0.544' '0.24' '0.108' '0.264' '0.37'
 '0.347' '0.309' '0.463' '0.168' '0.461' '0.442' '0.541' '0.174' '0.221'
 '0.242' '0.475' '0.214' '0.598' '0.247' '0.316' '0.208' '0.277' '0.499'
 '0.095' '0.342' '0.326' '0.346' '0.45' '0.456' '0.504' '0.606' '0.122'
 '0.345' '0.578' '0.336' '0.359' '0.379' '0.263' '0.497' '0.298' '0.41'
 '0.618' '0.281' '0.412' '0.438' '0.306' '0.135' '0.041' '0.106' '0.126'
 '0.563' '0.414' '0.23' '0.266' '0.245' '0.315' '0.636' '0.407' '0.075'
 '0.577' '0.676' '0.244' '0.48' '0.329' '0.13' '0.101' '0.151' '0.196'
 '0.027' '0.297' '0.536' '0.588' '0.54' '0.374' '0.047' '0.584' '0.451'
 '0.556' '0.518' '0.613' '0.081' '0.447' '0.078' '0.12' '0.273' '0.191'
 '0.428' '0.305' '0.253' '0.349' '0.638' '0.542' '0.159' '0.516' '0.39'
 '0.307' '0.698' '0.507' '0.406' '0.512' '0.755' '0.465' '0.474' '0.301'
 '0.063' '0.27' '0.184' '0.074' '0.572' '0.57' '0.484' '0.481' '0.284'
 '0.294' '0.179' '0.064' '0.207' '0.672' '0.491' '0.503' '0.114' '0.188'
 '0.197' '0.156' '0.076' '0.59' '0.389' '0.458' '0.648' '0.144' '0.293'
 '0.217' '0.235' '0.05' '0.395' '0.68' '0.066' '0.339' '0.032' '0.78'
 '0.19' '0.547' '0.55' '0.466' '0.227' '0.358' '0.362' '0.15' '0.084'
 '0.53' '0.257' '0.367' '0.64' '0.363' '0.614' '0.405' '0.129' '0.34'
 '0.739' '0.332' '0.141' '0.314' '0.537' '0.434' '0.579' '0.43' '0.452'
 '0.082' '0.735' '0.554' '0.517' '0.665' '0.605' '0.239' '0.505' '0.26'
 '0.639' '0.163' '0.351' '0.534' '0.204' '0.532' '0.378' '0.74' '0.206'
 '0.569' '0.149' '0.396' '0.49' '0.462' '0.409' '0.146' '0.594' '0.123'
 '0.67' '0.506' '0.771' '0.21' '0.372' '0.104' '0.202' '0.176' '0.691'
 '0.58' '0.582' '0.635' '0.674' '0.22' '0.117' '0.528' '0.688' '0.392'
 '0.429' '0.527' '0.393' '0.17' '0.28' '0.087' '0.437' '0.225' '0.597'
 '0.6' '0.059' '0.549' '0.33' '0.25' '0.089' '0.522' '0.391' '0.724'
 '0.337' '0.633' '0.145' '0.223' '0.496' '0.302' '0.023' '0.651' '0.628']
['NO' 'yes' '0' 0 'pending' '1' 'approved' 1]
['84']