# Pandas Challenges (Based on Your Notebook)

In [16]:
#1. Challenge 1 – Complete Data Cleaning
# Your manager gives you a messy dataset.
# Perform all of the following:
# • Load the dataset.
# • Display dataset information.
# • Find missing values.
# • Remove duplicate rows.
# • Fill missing values:
# o Age → median
# o Balance → mean
# • Rename:
# o Target → CustomerStatus
# o AnnualIncome → Income
# • Display the first 15 rows.
# Methods expected:
# read_csv()
# info()
# isnull()
# drop_duplicates()
# median()
# mean()
# fillna()
# rename()
# head()

import pandas as pd
df = pd.read_csv("C:\\Users\\Shree\\Downloads\\Task_dataset.csv")
df
print(df.info())
print(df.isnull().sum())
print(df.drop_duplicates())
df["Age"].fillna(df["Age"].median())
df["Balance"].fillna(df["Balance"].mean())
df.rename(columns = { "Target":"CustomerStatus","AnnualIncome":"Income"},inplace = True)

print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
None
 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64
      CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
0           10001  58.0       49184.0      2139          581        NaN
1           10002  65.0      162964.0      6197          732    6356.54
2           10003  56.0       26956.0     37281          503  143203.92
3           10004  55.0       92926.0       925          463  139627.88
4           10005  66.0      108236.0      7198          394   75985.46
..            ...   ...           ...       ...          ...        ...
995         10996  34.0       81731.0     40980          761  181465.65
996         10997  47.0       42475.0      1176          780   26640.99
997         10998  31.0      120531.0     46929          733  147220.82
998         10999  21.0       33661.0     22314          540   94186.48
999         11000  63.0       31930.0       851          559  100908.40

     Tenure Geography  Gender    Segment Target
0         2    France    Male        SME   Stay
1         1       USA    Male        SME  Churn
2         8    Canada    Male  Corporate   Stay
3         5       NaN    Male     Retail  Churn
4         5        UK   Other  Corporate  Churn
..      ...       ...     ...        ...    ...
995       5   Germany   Other        SME   Stay
996       5    France  Female        SME   Stay
997       4     India    Male        SME   Stay
998       5       NaN   Other        SME   Stay
999       6        UK  Female        NaN   Stay

[1000 rows x 11 columns]
    CustomerID    Age    Income  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0   49184.0      2139          581        NaN       2
1         10002  65.0  162964.0      6197          732    6356.54       1
2         10003  56.0   26956.0     37281          503  143203.92       8
3         10004  55.0   92926.0       925          463  139627.88       5
4         10005  66.0  108236.0      7198          394   75985.46       5

  Geography Gender    Segment CustomerStatus
0    France   Male        SME           Stay
1       USA   Male        SME          Churn
2    Canada   Male  Corporate           Stay
3       NaN   Male     Retail          Churn
4        UK  Other  Corporate          Churn

In [16]:
#2. Banking Report
# The bank wants a numeric report.
# Tasks
# • Select only numeric columns.

# • Display summary statistics.
# • Convert Age and CreditScore to float.
# • Display information again.


numeric_df = df.select_dtypes(include=["number"])
print(numeric_df.describe())
df["Age"] = df["Age"].astype(float)
df["CreditScore"] = df["CreditScore"].astype(float)
df.info()

        CustomerID          Age         Income      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    CustomerID     1020 non-null   int64
 1   Age             970 non-null    float64
 2   Income          967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   float64
 5   Balance         969 non-null    float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  CustomerStatus  1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [25]:
#3. Duplicate Investigation
# Find duplicate customer
# Then
# • Count duplicate rows.
# • Remove duplicates.
# • Print information before and after removing duplicates.
# • Show the last 20 rows.

print(df.drop_duplicates())
count = df.duplicated().sum()
count
df= df.drop_duplicates()
df
df.tail(20)

      CustomerID    Age    Income  Spending  CreditScore    Balance  Tenure  \
0           10001  58.0   49184.0      2139        581.0        NaN       2
1           10002  65.0  162964.0      6197        732.0    6356.54       1
2           10003  56.0   26956.0     37281        503.0  143203.92       8
3           10004  55.0   92926.0       925        463.0  139627.88       5
4           10005  66.0  108236.0      7198        394.0   75985.46       5
..            ...   ...       ...       ...          ...        ...     ...
995         10996  34.0   81731.0     40980        761.0  181465.65       5
996         10997  47.0   42475.0      1176        780.0   26640.99       5
997         10998  31.0  120531.0     46929        733.0  147220.82       4
998         10999  21.0   33661.0     22314        540.0   94186.48       5
999         11000  63.0   31930.0       851        559.0  100908.40       6

    Geography  Gender    Segment CustomerStatus
0      France    Male        SME           Stay
1         USA    Male        SME          Churn
2      Canada    Male  Corporate           Stay
3         NaN    Male     Retail          Churn
4          UK   Other  Corporate          Churn
..        ...     ...        ...            ...
995   Germany   Other        SME           Stay
996    France  Female        SME           Stay
997     India    Male        SME           Stay
998       NaN   Other        SME           Stay
999        UK  Female        NaN           Stay

[1000 rows x 11 columns]

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
980,10981,41.0,199633.0,8498,847.0,173390.59,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541.0,59484.58,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334.0,NaN,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732.0,175352.25,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730.0,120423.19,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488.0,126031.27,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621.0,115161.87,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720.0,158528.46,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635.0,159905.73,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884.0,44897.43,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773.0,39653.24,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452.0,17812.25,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764.0,165451.49,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594.0,149288.61,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493.0,83666.20,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761.0,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.40,6,UK,Female,NaN,Stay

In [29]:
#4. HR Department
# HR wants better column names.
# Rename
# CustomerID → Employee_ID
# Age → EmployeeAge
# Gender → EmployeeGender
# AnnualIncome → Salary
# Target → PromotionStatus
# Then
# • Add prefix
#HR_
# t o every column.
# Display 10 random records.

df = df.rename(columns= {"CustomerID":"Employee_ID","Age":"EmployeeAge","Gender":"EmployeeGender","Anuualincome":"Salary","Target":"PromotionStatus"})
df
df.add_prefix("HR_")
df.sample(10)

,CustomerID,EmployeeAge,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
942,10943,60.0,178116.0,27005,796,102282.90,2,Canada,Male,Retail,Stay
361,10362,19.0,109935.0,42965,411,135427.87,2,France,Male,SME,Churn
214,10215,58.0,155102.0,38186,547,143708.87,4,Canada,Male,SME,Stay
18,10019,24.0,183918.0,20058,819,121794.04,2,UK,Male,SME,Stay
445,10446,54.0,69344.0,32758,855,61810.61,7,India,Male,Retail,Stay
330,10331,20.0,80231.0,14355,880,95100.06,0,India,Other,Corporate,Churn
698,10699,46.0,112359.0,21153,863,198292.60,5,UK,Female,SME,Stay
649,10650,NaN,94608.0,23772,632,134638.57,7,France,Female,Retail,Stay
945,10946,27.0,99364.0,41261,398,152034.29,10,Germany,Female,Corporate,Churn
375,10376,50.0,49677.0,38033,416,53577.78,8,UK,Other,Retail,Churn

In [39]:
#5. Finance Cleaning
# Finance department reports missing values.

# Tasks
# Fill
# AnnualIncome → Median
# Balance → Mean
# Age → Median

df2 = pd.read_csv("C:\\Users\\Shree\\Downloads\\Task_dataset.csv")
df2
print(df2.isnull().sum())
print(df2["AnnualIncome"].fillna(df2["AnnualIncome"].median()))
print(df2["Balance"].fillna(df2["Balance"].mean()))
print(df2["Age"].fillna(df2["Age"].mean()))
print(df.describe())

 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64
0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64
0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64
0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64
        CustomerID   EmployeeAge   AnnualIncome      Spending  CreditScore  \
count   1020.000000   970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020    44.249485  112505.928645  25232.615686   602.659804
std      288.022115    15.521935   52303.362541  14219.393105   176.560690
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10252.750000    30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000    44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000    58.000000  158000.500000  37956.000000   757.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000

In [186]:
#6.– Data Type Audit
# The company says
# Age and AnnualIncome are stored incorrectly.
# Tasks
# Convert
# Age → int
# AnnualIncome → float
# Balance → float
import pandas as pd
df7 = pd.read_csv("C:\\Users\\Shree\\Downloads\\Task_dataset.csv")
df7

df7["Age"] = df7["Age"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [47]:
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["AnnualIncome"]

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018         NaN
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [46]:
df["Balance"] = df["Balance"].astype(float)
df["Balance"]

0             NaN
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019          NaN
Name: Balance, Length: 1020, dtype: float64

In [13]:
#7. – Customer Analytics
# Create a new DataFrame that
# • removes Segment
# • removes Geography
# • removes duplicate rows
#Display
# •  first 10 rows
# • dataset information
# • statistical summary


print(df2.drop_duplicates())
print(df2.head(10))
print(df2.info())
print(df2.describe())

      CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
0           10001  58.0       49184.0      2139          581        NaN
1           10002  65.0      162964.0      6197          732    6356.54
2           10003  56.0       26956.0     37281          503  143203.92
3           10004  55.0       92926.0       925          463  139627.88
4           10005  66.0      108236.0      7198          394   75985.46
..            ...   ...           ...       ...          ...        ...
995         10996  34.0       81731.0     40980          761  181465.65
996         10997  47.0       42475.0      1176          780   26640.99
997         10998  31.0      120531.0     46929          733  147220.82
998         10999  21.0       33661.0     22314          540   94186.48
999         11000  63.0       31930.0       851          559  100908.40

     Tenure Geography  Gender    Segment Target
0         2    France    Male        SME   Stay
1         1       USA    Male        SME  Churn
2         8    Canada    Male  Corporate   Stay
3         5       NaN    Male     Retail  Churn
4         5        UK   Other  Corporate  Churn
..      ...       ...     ...        ...    ...
995       5   Germany   Other        SME   Stay
996       5    France  Female        SME   Stay
997       4     India    Male        SME   Stay
998       5       NaN   Other        SME   Stay
999       6        UK  Female        NaN   Stay

[1000 rows x 11 columns]
    CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0       49184.0      2139          581        NaN       2
1         10002  65.0      162964.0      6197          732    6356.54       1
2         10003  56.0       26956.0     37281          503  143203.92       8
3         10004  55.0       92926.0       925          463  139627.88       5
4         10005  66.0      108236.0      7198          394   75985.46       5
5         10006  69.0       31390.0     48323          770  107245.62       6
6         10007  58.0      182141.0     24200          891   38457.72       1
7         10008  67.0       95861.0      5729          538  173296.73       6
8         10009  41.0       62638.0     24760          663   41901.41       4
9         10010  22.0      179680.0     42113          475  106827.98       3

  Geography  Gender    Segment Target
0    France    Male        SME   Stay
1       USA    Male        SME  Churn
2    Canada    Male  Corporate   Stay
3       NaN    Male     Retail  Churn
4        UK   Other  Corporate  Churn
5     India   Other  Corporate   Stay
6     India   Other     Retail  Churn
7        UK  Female        SME   Stay
8    France   Other        SME   Stay
9       USA  Female  Corporate  Churn
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
None
        CustomerID          Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000

In [53]:
#8. – ML Dataset Preparation
# Prepare a machine learning dataset.
# Perform
# • Remove duplicates
# • Remove CustomerID
# • Remove Segment
# • Fill missing values
# • Rename Target to Output
#Finally
#Display
# head()
# info()
# describe()
# value_counts(Output)

import pandas as pd
df2 = pd.read_csv("C:\\Users\\Shree\\Downloads\\Task_dataset.csv")
df2
df2.drop_duplicates()
df2['Age'].fillna('unknown')
df2
df2.rename = df2.rename(columns = {"Target":"Output"})
df2.rename
df2.head()
df2.info()
df2.describe()
df2.value_counts("Target")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [40]:
#9. Column Transformation
# Create these new columns
# NetWorth = Balance + AnnualIncome
# AgeAfterRetirement = Age + 20
# DoubleCreditScore = CreditScore * 2
# IncomePerMonth = AnnualIncome / 12
# Then
# Display first 15 rows.

df2["Networth"] = df2["Balance"] + df2["AnnualIncome"]
df2["Networth"]
df2["AgeAfterRetirement"] = df2["Age"] + 20
df2["AgeAfterRetirement"]
df2["DoubleCreditScore"] = df2["CreditScore"] * 2
df2["DoubleCreditScore"]

df2["IncomePerMonth"] = df2["AnnualIncome"] / 12
df2["IncomePerMonth"]

print(df2.head(20))

     CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
6          10007  58.0      182141.0     24200          891   38457.72
7          10008  67.0       95861.0      5729          538  173296.73
8          10009  41.0       62638.0     24760          663   41901.41
9          10010  22.0      179680.0     42113          475  106827.98
10         10011   NaN      187772.0     45599          870   43923.03
11         10012  69.0      102694.0     26790          574   13237.72
12         10013  59.0      150870.0     26428          769   28574.32
13         10014  52.0       88876.0     49456          898   85686.77
14         10015  26.0      153569.0     32843          393  151156.43
15         10016  68.0      198384.0     28166          365   76953.46
16         10017  53.0           NaN     45083          417  136342.07
17         10018   NaN       96939.0     28992          461   90744.74
18         10019  24.0      183918.0     20058          819  121794.04
19         10020  67.0      159029.0       537          631   97721.14

    Tenure Geography  Gender    Segment Target   Networth  AgeAfterRetirement  \
0        2    France    Male        SME   Stay        NaN                78.0
1        1       USA    Male        SME  Churn  169320.54                85.0
2        8    Canada    Male  Corporate   Stay  170159.92                76.0
3        5       NaN    Male     Retail  Churn  232553.88                75.0
4        5        UK   Other  Corporate  Churn  184221.46                86.0
5        6     India   Other  Corporate   Stay  138635.62                89.0
6        1     India   Other     Retail  Churn  220598.72                78.0
7        6        UK  Female        SME   Stay  269157.73                87.0
8        4    France   Other        SME   Stay  104539.41                61.0
9        3       USA  Female  Corporate  Churn  286507.98                42.0
10       5     India     NaN     Retail   Stay  231695.03                 NaN
11       9    France  Female     Retail  Churn  115931.72                89.0
12       2       USA   Other        SME   Stay  179444.32                79.0
13       9    Canada  Female     Retail   Stay  174562.77                72.0
14       1       USA   Other     Retail  Churn  304725.43                46.0
15       9    Canada   Other  Corporate  Churn  275337.46                88.0
16       8        UK   Other  Corporate  Churn        NaN                73.0
17       4       NaN    Male        SME  Churn  187683.74                 NaN
18       2        UK    Male        SME   Stay  305712.04                44.0
19       1        UK  Female     Retail  Churn  256750.14                87.0

    DoubleCreditScore  IncomePerMonth
0                1162     4098.666667
1                1464    13580.333333
2                1006     2246.333333
3                 926     7743.833333
4                 788     9019.666667
5                1540     2615.833333
6                1782    15178.416667
7                1076     7988.416667
8                1326     5219.833333
9                 950    14973.333333
10               1740    15647.666667
11               1148     8557.833333
12               1538    12572.500000
13               1796     7406.333333
14                786    12797.416667
15                730    16532.000000
16                834             NaN
17                922     8078.250000
18               1638    15326.500000
19               1262    13252.416667

In [51]:
#10. – Company Report
# Display
# • first five rows
# • last five rows
# • ten random rows
# • dataset information
# •  descriptive statistics
# Finally rename
# Target → Customer_Status

print(df2.head(5))
print(df2.tail(5))
df2.sample(10)
df2.info()
df2.describe()

    CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0       49184.0      2139          581        NaN       2
1         10002  65.0      162964.0      6197          732    6356.54       1
2         10003  56.0       26956.0     37281          503  143203.92       8
3         10004  55.0       92926.0       925          463  139627.88       5
4         10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target   Networth  AgeAfterRetirement  \
0    France   Male        SME   Stay        NaN                78.0
1       USA   Male        SME  Churn  169320.54                85.0
2    Canada   Male  Corporate   Stay  170159.92                76.0
3       NaN   Male     Retail  Churn  232553.88                75.0
4        UK  Other  Corporate  Churn  184221.46                86.0

   DoubleCreditScore  IncomePerMonth
0               1162     4098.666667
1               1464    13580.333333
2               1006     2246.333333
3                926     7743.833333
4                788     9019.666667
       CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
1015         10450  43.0      173620.0      7121          644   60353.03
1016         10753  25.0       54490.0     13794          303  124512.07
1017         10810  49.0       82062.0     47170          813   53850.09
1018         10267  38.0           NaN     10424          722  138100.05
1019         10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target   Networth  \
1015       2       USA   Other  Corporate   Stay  233973.03
1016       4     India     NaN  Corporate  Churn  179002.07
1017       8   Germany  Female     Retail   Stay  135912.09
1018       6   Germany   Other  Corporate   Stay        NaN
1019      10    Canada   Other        NaN  Churn        NaN

      AgeAfterRetirement  DoubleCreditScore  IncomePerMonth
1015                63.0               1288    14468.333333
1016                45.0                606     4540.833333
1017                69.0               1626     6838.500000
1018                58.0               1444             NaN
1019                82.0                860     8125.333333
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0    CustomerID         1020 non-null   int64
 1   Age                 970 non-null    float64
 2   AnnualIncome        967 non-null    float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             969 non-null    float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Target              1020 non-null   object
 11  Networth            920 non-null    float64
 12  AgeAfterRetirement  970 non-null    float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      967 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Networth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000,920.000000,970.000000,1020.000000,967.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765,209641.594380,64.249485,1205.319608,9375.494054
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330,74287.727616,15.521935,353.121379,4358.613545
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,38.000000,600.000000,1685.583333
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000,156965.307500,50.250000,881.500000,5512.416667
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000,209204.760000,64.000000,1214.000000,9363.166667
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000,261256.997500,78.000000,1514.500000,13166.708333
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,90.000000,1800.000000,16663.916667

In [52]:
df.rename(columns = {"Target":"Customer_Status"})

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [55]:
#11. – Missing Value Report
# Create a report showing
#  • Total missing values
# • Numerical columns
# • Mean of Balance
# • Median of Age
# • Fill missing values
# • Display information again

df.isnull().sum()

 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [179]:
df.isna().sum()

 CustomerID         0
Age                50
AnnualIncome       53
Spending            0
CreditScore         0
Balance            51
Tenure              0
SeniorCitizen      50
HighCreditScore     0
dtype: int64

In [56]:
int_column=df.select_dtypes(include = ["int64"]).columns
len(int_column)

4

In [57]:
print(df2["Balance"].fillna(df2["Balance"].mean()))

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [60]:
df["Age"] = df["Age"].fillna("Age")
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: object

In [62]:
df['Age'].fillna('unknown',inplace = True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   object
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(4), object(5)
memory usage: 87.8+ KB

In [66]:
#12. Customer Classification
# Count
# Stay

# Churn
# Then
# Rename
# Target → Customer_Class
# Convert it into string.

df.rename(columns = {"Target":"Customer_class"})
df["Age"] = df["Age"].astype(str)
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: object

In [67]:
#13. Rename
# Balance → AccountBalance
# AnnualIncome → Salary
# CreditScore → Score
# Add prefix
# Sales_
# Then
# Display
# sample(20)

df.rename(columns = {"Balance":"AccountBalance","AnnualIncome":"Salary","CreditScore":"Score"})

,CustomerID,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [68]:
df.add_prefix("Sales_")

,Sales_ CustomerID,Sales_Age,Sales_AnnualIncome,Sales_Spending,Sales_CreditScore,Sales_Balance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   object
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(4), object(5)
memory usage: 87.8+ KB

In [70]:
df.sample(20)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1007,10756,53.0,74430.0,3705,489,29651.23,10,UK,Male,Retail,Churn
235,10236,63.0,136683.0,6253,627,133567.96,1,Germany,Other,Corporate,Churn
529,10530,64.0,168114.0,15179,646,103819.94,9,India,Female,SME,Stay
678,10679,68.0,144589.0,45615,458,74279.73,1,USA,Male,Corporate,Churn
374,10375,32.0,160930.0,19418,472,156148.04,9,France,Female,SME,Churn
429,10430,37.0,178152.0,3143,520,167184.95,5,USA,Male,SME,Stay
27,10028,24.0,192748.0,28749,662,84715.72,7,France,Male,SME,Stay
85,10086,45.0,193413.0,24785,370,101192.16,5,India,Female,Corporate,Churn
986,10987,30.0,184704.0,20524,621,115161.87,1,USA,Male,SME,Churn
58,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn
430,10431,33.0,113255.0,26468,825,9790.12,4,UK,Male,Retail,Churn
704,10705,33.0,81078.0,17293,607,18381.02,6,Germany,Male,SME,Churn
638,10639,20.0,151720.0,23259,703,172080.03,2,Canada,Male,SME,Stay
1011,10457,44.0,63604.0,27633,804,176354.13,5,Germany,Female,Retail,Stay
639,10640,51.0,140604.0,21186,308,NaN,3,Canada,Other,Retail,Churn
263,10264,44.0,173014.0,20663,327,119381.92,4,France,Other,SME,Churn
227,10228,45.0,63684.0,45704,754,70309.40,0,France,Female,SME,Churn
1014,10181,50.0,166466.0,44281,662,14415.10,0,Canada,Male,Corporate,Churn
945,10946,27.0,99364.0,41261,398,152034.29,10,Germany,Female,Corporate,Churn
366,10367,58.0,102157.0,39623,697,122261.68,9,India,Female,Corporate,Stay

In [71]:
#14. Without creating another DataFrame,
# perform
# • remove duplicates
# • rename Target
# •  fill missing values
#• convert Balance to float
# •  display summary

df2.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [72]:
df.rename(columns ={"Target":"Output"})

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [75]:
df['Age'].fillna('unknown')
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [76]:
df["Balance"] = df["Balance"].astype(float)
df["Balance"]

0             NaN
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019          NaN
Name: Balance, Length: 1020, dtype: float64

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           1020 non-null   object
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(4), object(5)
memory usage: 87.8+ KB

In [168]:
#15. Data Engineer Task
# Load the dataset.
# Create another DataFrame containing only numeric columns.
# Drop
# CustomerID
# Target
# CustomerID
# Target
# Display summary.

import pandas as pd
df5 = pd.read_csv("C:\\Users\\Shree\\Downloads\\Task_dataset.csv")
df5

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [152]:
df = df.select_dtypes(include=["number"])
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,NaN,2,58.0,581
1,10002,65.0,162964.0,6197,732,6356.54,1,65.0,732
2,10003,56.0,26956.0,37281,503,143203.92,8,56.0,503
3,10004,55.0,92926.0,925,463,139627.88,5,55.0,463
4,10005,66.0,108236.0,7198,394,75985.46,5,66.0,394
...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,43.0,644
1016,10753,25.0,54490.0,13794,303,124512.07,4,25.0,303
1017,10810,49.0,82062.0,47170,813,53850.09,8,49.0,813
1018,10267,38.0,NaN,10424,722,138100.05,6,38.0,722
1019,10059,62.0,97504.0,36833,430,NaN,10,62.0,430

In [175]:
df5.drop(columns ={"CustomerID"},axis=1)
df5

KeyError: "['CustomerID'] not found in axis"

In [178]:
df5.drop(columns = {"Target"},axis=1)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate
...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0    CustomerID      1020 non-null   int64
 1   Age              970 non-null    float64
 2   AnnualIncome     967 non-null    float64
 3   Spending         1020 non-null   int64
 4   CreditScore      1020 non-null   int64
 5   Balance          969 non-null    float64
 6   Tenure           1020 non-null   int64
 7   SeniorCitizen    970 non-null    float64
 8   HighCreditScore  1020 non-null   int64
dtypes: float64(4), int64(5)
memory usage: 71.8 KB

In [79]:
#16. – Mixed Cleaning
# Perform
# drop_duplicates()
# fillna()
# astype()
# rename()
# head()
# info()
# using only one DataFrame variable.

df.drop_duplicates()
df.

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [80]:
df['Age'].fillna('unknown')
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [81]:
df["Balance"] = df["Balance"].astype(float)
df["Balance"]

0             NaN
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019          NaN
Name: Balance, Length: 1020, dtype: float64

In [82]:
df.rename(columns = {"Target":"Output"})

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [83]:
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [150]:
#17. – Real Company Dataset
# Manager asks
# Remove duplicate records
# Fill missing values
# Rename all business columns
# Add company prefix
# Display summary
# Display target counts

print(df.duplicated().sum())
print(df.drop_duplicates())
df['Age'].fillna('unknown')
df
print(df.add_prefix("Company_"))
print(df.info())
print(df['Age'].value_counts(dropna = False))

20
      CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
0           10001  58.0       49184.0      2139          581        NaN
1           10002  65.0      162964.0      6197          732    6356.54
2           10003  56.0       26956.0     37281          503  143203.92
3           10004  55.0       92926.0       925          463  139627.88
4           10005  66.0      108236.0      7198          394   75985.46
..            ...   ...           ...       ...          ...        ...
995         10996  34.0       81731.0     40980          761  181465.65
996         10997  47.0       42475.0      1176          780   26640.99
997         10998  31.0      120531.0     46929          733  147220.82
998         10999  21.0       33661.0     22314          540   94186.48
999         11000  63.0       31930.0       851          559  100908.40

     Tenure Geography  Gender    Segment Target  SeniorCitizen  \
0         2    France    Male        SME   Stay           58.0
1         1       USA    Male        SME  Churn           65.0
2         8    Canada    Male  Corporate   Stay           56.0
3         5       NaN    Male     Retail  Churn           55.0
4         5        UK   Other  Corporate  Churn           66.0
..      ...       ...     ...        ...    ...            ...
995       5   Germany   Other        SME   Stay           34.0
996       5    France  Female        SME   Stay           47.0
997       4     India    Male        SME   Stay           31.0
998       5       NaN   Other        SME   Stay           21.0
999       6        UK  Female        NaN   Stay           63.0

     HighCreditScore
0                581
1                732
2                503
3                463
4                394
..               ...
995              761
996              780
997              733
998              540
999              559

[1000 rows x 13 columns]
      Company_ CustomerID   Company_Age  Company_AnnualIncome  \
0                    10001         58.0               49184.0
1                    10002         65.0              162964.0
2                    10003         56.0               26956.0
3                    10004         55.0               92926.0
4                    10005         66.0              108236.0
...                    ...          ...                   ...
1015                 10450         43.0              173620.0
1016                 10753         25.0               54490.0
1017                 10810         49.0               82062.0
1018                 10267         38.0                   NaN
1019                 10059         62.0               97504.0

      Company_Spending  Company_CreditScore  Company_Balance  Company_Tenure  \
0                 2139                  581              NaN               2
1                 6197                  732          6356.54               1
2                37281                  503        143203.92               8
3                  925                  463        139627.88               5
4                 7198                  394         75985.46               5
...                ...                  ...              ...             ...
1015              7121                  644         60353.03               2
1016             13794                  303        124512.07               4
1017             47170                  813         53850.09               8
1018             10424                  722        138100.05               6
1019             36833                  430              NaN              10

     Company_Geography Company_Gender Company_Segment Company_Target  \
0               France           Male             SME           Stay
1                  USA           Male             SME          Churn
2               Canada           Male       Corporate           Stay
3                  NaN           Male          Retail          Churn
4                   UK          Other       Corporate          Churn
...                ...            ...             ...            ...
1015               USA          Other       Corporate           Stay
1016             India            NaN       Corporate          Churn
1017           Germany         Female          Retail           Stay
1018           Germany          Other       Corporate           Stay
1019            Canada          Other             NaN          Churn

      Company_SeniorCitizen  Company_HighCreditScore
0                      58.0                      581
1                      65.0                      732
2                      56.0                      503
3                      55.0                      463
4                      66.0                      394
...                     ...                      ...
1015                   43.0                      644
1016                   25.0                      303
1017                   49.0                      813
1018                   38.0                      722
1019                   62.0                      430

[1020 rows x 13 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0    CustomerID      1020 non-null   int64
 1   Age              970 non-null    float64
 2   AnnualIncome     967 non-null    float64
 3   Spending         1020 non-null   int64
 4   CreditScore      1020 non-null   int64
 5   Balance          969 non-null    float64
 6   Tenure           1020 non-null   int64
 7   Geography        969 non-null    object
 8   Gender           968 non-null    object
 9   Segment          969 non-null    object
 10  Target           1020 non-null   object
 11  SeniorCitizen    970 non-null    float64
 12  HighCreditScore  1020 non-null   int64
dtypes: float64(4), int64(5), object(4)
memory usage: 103.7+ KB
None
Age
NaN     50
27.0    33
44.0    27
66.0    26
69.0    26
37.0    25
26.0    24
38.0    24
61.0    23
53.0    23
25.0    22
21.0    22
58.0    22
70.0    22
47.0    21
67.0    21
50.0    20
46.0    20
34.0    20
51.0    20
62.0    20
32.0    19
30.0    18
41.0    18
40.0    18
31.0    18
64.0    18
43.0    18
24.0    18
57.0    17
52.0    17
20.0    17
45.0    17
19.0    17
59.0    17
68.0    17
29.0    16
33.0    16
65.0    16
48.0    15
23.0    15
18.0    15
36.0    15
55.0    15
63.0    14
56.0    14
49.0    14
54.0    13
28.0    13
22.0    13
35.0    12
39.0    10
42.0    10
60.0     9
Name: count, dtype: int64

In [92]:
#18. – Customer Summary
# Generate
# Mean Balance
# Median Balance
# Mean Age
# Median AnnualIncome
# Then
# fill missing values using these statistics.

age_balance = df['Balance'].mean()
age_balance

np.float64(97523.53566563467)

In [93]:
balance_median = df['Balance'].median()
balance_median

95100.06

In [94]:
age_median = df['Age'].median()
age_median

44.0

In [95]:
age_AnnualIncome = df['AnnualIncome'].median()
age_AnnualIncome

112358.0

In [143]:
#19. Transformation Challenge
# Create
# Income_in_Lakhs
# Balance_in_Lakhs

# SeniorCitizen
# HighCreditScore
# where
# SeniorCitizen = Age + 0
# HighCreditScore = CreditScore * 1
# (No conditional statements.)

df4["Income_in_Lakhs"] = df4["AnnualIncome"] > 100000
df4["Income_in_Lakhs"]

df4["Balance_in_Lakhs"]= df4["Balance"] > 100000
df4["Balance_in_Lakhs"]

0       False
1       False
2        True
3        True
4       False
        ...
1015    False
1016     True
1017    False
1018     True
1019    False
Name: Balance_in_Lakhs, Length: 1020, dtype: bool

In [145]:
df["SeniorCitizen"] = df["Age"] +0
df["SeniorCitizen"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: SeniorCitizen, Length: 1020, dtype: float64

In [148]:
df["HighCreditScore"] = df["CreditScore"] * 1
df["HighCreditScore"]

0       581
1       732
2       503
3       463
4       394
       ...
1015    644
1016    303
1017    813
1018    722
1019    430
Name: HighCreditScore, Length: 1020, dtype: int64

In [149]:
print(df.head())

    CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0       49184.0      2139          581        NaN       2
1         10002  65.0      162964.0      6197          732    6356.54       1
2         10003  56.0       26956.0     37281          503  143203.92       8
3         10004  55.0       92926.0       925          463  139627.88       5
4         10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target  SeniorCitizen  HighCreditScore
0    France   Male        SME   Stay           58.0              581
1       USA   Male        SME  Churn           65.0              732
2    Canada   Male  Corporate   Stay           56.0              503
3       NaN   Male     Retail  Churn           55.0              463
4        UK  Other  Corporate  Churn           66.0              394

In [108]:
# Final Interview Project
# Your manager gives you a dirty customer dataset.
# Prepare the final dataset.
# Requirements
# Load dataset
# Check information
# Find missing values
# Remove duplicates
# Rename
# CustomerID
# AnnualIncome
# CreditScore
# Target
# Convert
# Age
# AnnualIncome
# Balance
# Fill missing values
# Remove
# Segment
# CustomerID
# Create new columns
# TotalMoney = Balance + AnnualIncome
# AgeAfter5Years = Age + 5
# MonthlyIncome = AnnualIncome / 12
# CreditScoreDouble = CreditScore * 2Display
# • Head
# • Tail
# • Sample
# • Describe
# • Target counts
# • Final information

import pandas as pd
df = pd.read_csv("C:\\Users\\Shree\\Downloads\\Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [100]:
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [101]:
df.isnull().sum()

 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [103]:
df.rename(columns = {"CustomerID":"Customer_Id","AnnualIncome":"Annual_Income","CreditScore":"Credit_Score","Target":"Output"})

,CustomerID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Segment,Output
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [104]:
df["Age"] = df["Age"].astype(float)
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [105]:
df["Balance"] = df["Balance"].astype(float)
df["Balance"]

0             NaN
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019          NaN
Name: Balance, Length: 1020, dtype: float64

In [106]:
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["AnnualIncome"]

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018         NaN
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [120]:
import pandas as pd
df4 = pd.read_csv("C:\\Users\\Shree\\Downloads\\Task_dataset.csv")
df4
df4["CreditScoreDouble"] = df4["CreditScore"] * 2
df4

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,63.0,4098.666667,1162
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,70.0,13580.333333,1464
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,61.0,2246.333333,1006
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,60.0,7743.833333,926
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,71.0,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,48.0,14468.333333,1288
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,30.0,4540.833333,606
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,54.0,6838.500000,1626
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,43.0,NaN,1444
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,67.0,8125.333333,860

In [122]:
df4["TotalMoney"] = df4["Balance"] + df4["AnnualIncome"]
df4

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,63.0,4098.666667,1162
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,70.0,13580.333333,1464
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,61.0,2246.333333,1006
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,60.0,7743.833333,926
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,71.0,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,48.0,14468.333333,1288
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,30.0,4540.833333,606
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,54.0,6838.500000,1626
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,43.0,NaN,1444
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,67.0,8125.333333,860

In [124]:
df4["AgeAfter5Years"] = df4["Age"] +5
df4

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,63.0,4098.666667,1162
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,70.0,13580.333333,1464
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,61.0,2246.333333,1006
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,60.0,7743.833333,926
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,71.0,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,48.0,14468.333333,1288
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,30.0,4540.833333,606
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,54.0,6838.500000,1626
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,43.0,NaN,1444
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,67.0,8125.333333,860

In [125]:
df4["MonthlyIncome"] = df4["AnnualIncome"] /12
df4

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,63.0,4098.666667,1162
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,70.0,13580.333333,1464
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,61.0,2246.333333,1006
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,60.0,7743.833333,926
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,71.0,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,48.0,14468.333333,1288
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,30.0,4540.833333,606
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,54.0,6838.500000,1626
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,43.0,NaN,1444
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,67.0,8125.333333,860

In [126]:
df4.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,63.0,4098.666667,1162
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,70.0,13580.333333,1464
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,61.0,2246.333333,1006
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,60.0,7743.833333,926
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,71.0,9019.666667,788

In [127]:
df4.tail()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,48.0,14468.333333,1288
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,30.0,4540.833333,606
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,54.0,6838.500000,1626
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,43.0,NaN,1444
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,67.0,8125.333333,860

In [128]:
df.sample()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
575,10576,19.0,144253.0,10744,846,43973.15,6,Germany,Female,SME,Stay

In [129]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [134]:
df4["Target"].value_counts()

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [135]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0    CustomerID        1020 non-null   int64
 1   Age                970 non-null    float64
 2   AnnualIncome       967 non-null    float64
 3   Spending           1020 non-null   int64
 4   CreditScore        1020 non-null   int64
 5   Balance            969 non-null    float64
 6   Tenure             1020 non-null   int64
 7   Geography          969 non-null    object
 8   Gender             968 non-null    object
 9   Segment            969 non-null    object
 10  Target             1020 non-null   object
 11  TotalMoney         920 non-null    float64
 12  AgeAfter5Years     970 non-null    float64
 13  MonthlyIncome      967 non-null    float64
 14  CreditScoreDouble  1020 non-null   int64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB