# Easy Level (1–10)

In [3]:
#1. Load the dataset and display the first 10 records.
import pandas as pd
df = pd.read_csv("C:\\Users\\Shree\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [25]:
#2. Display the last 15 customers.

df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [26]:
#3. Show 7 random customer records.
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5576,5577,15635964,Eve,566,Germany,Male,65,4,120100.41,1,1,0,107563.16,1
6771,6772,15621818,Anayolisa,747,Germany,Male,29,7,117726.33,1,1,1,175398.34,0
8336,8337,15788480,Pagnotto,786,Germany,Female,33,0,122325.58,1,0,0,34712.34,1
1623,1624,15804516,Builder,589,France,Male,38,2,0.00,1,1,0,79915.28,0
497,498,15733616,Sopuluchukwu,806,France,Male,40,5,80613.93,1,1,1,142838.64,0
7823,7824,15616029,Adams,705,France,Male,32,7,0.00,2,1,0,7921.57,0
363,364,15745088,Chen,443,Germany,Female,29,9,99027.61,2,1,0,10940.40,0

In [31]:
#4. Print complete dataset information and identify:
# • Total columns
# • Data type of each column
# • Missing values

cols = df.shape
print("no.of columns:",cols)
df1 = df.info()
df1
df2 = df.isnull()
df2

no.of columns: (10000, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [33]:
#5. Find missing values in every column.

df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [34]:
#6. Display only numerical columns.

int_column=df.select_dtypes(include = ["int64"]).columns
int_column

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited'],
      dtype='object')

In [35]:
#7. Generate the statistical summary of numerical columns.

df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [39]:
#8. Find duplicate rows and print how many exist.

duplicates = df.duplicated().sum()
duplicates
rows = df.shape
print("no.of rows:",rows)

no.of rows: (10000, 14)

In [40]:
#9. Remove duplicate rows and store the cleaned dataset.

df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

In [41]:
#10. Count how many customers have exited and how many have not exited.

counts = df["Exited"].value_counts()
print(counts)

Exited
0    7963
1    2037
Name: count, dtype: int64

# Medium Level (11–20)

In [107]:
#11. Rename the following columns:
# CustomerId → Customer_ID
# CreditScore → Credit_Score
# EstimatedSalary → Salary
# Exited → Churn

df.rename(columns = {"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Churn"},inplace = True)
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'Salary', 'Churn'],
      dtype='object')

In [72]:
#12. Add the prefix Bank_ to every column name.

df.add_prefix("Bank_")

    Bank_Age
0       10.0
1       23.0
2       45.0
3       56.0
4       66.0
5        NaN
6       34.0
7        NaN
8       12.0
9       13.0
10      54.0
11       NaN

In [73]:
#13. Convert the Age column into float datatype.

import numpy as np
dicts = {"Age":[10,23,45,56,66,np.nan,34,np.nan,12,13,54,np.nan]}
df = pd.DataFrame(dicts)
df.head()
df['Age'] = df['Age'].astype("float")
df['Age']

0     10.0
1     23.0
2     45.0
3     56.0
4     66.0
5      NaN
6     34.0
7      NaN
8     12.0
9     13.0
10    54.0
11     NaN
Name: Age, dtype: float64

In [77]:
#14. Convert the Exited column into string datatype.

df["Exited"] = df["Exited"].astype("str")
df['Exited']

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: object

In [92]:
#15. Suppose the Balance column has missing values.
# Replace them using the mean of the Balance column.

df['Balance'] = df["Balance"].fillna(balance_mean)
df['Balance']

rep_bal = df["Balance"].fillna(balance_mean)
rep_bal

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [69]:
#16. Suppose the Age column has missing values. Replace them using the median age.
age_median = df['Age'].median()
age_median

34.0

In [105]:
#17. Display only the first five rows after renaming the columns.

df.rename(index = {0:"first",1:"second",2:"third",3:"fourth",4:"fifth"})

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
first,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
second,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
third,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
fourth,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
fifth,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [12]:
#18. Create a new DataFrame by dropping these columns:
# RowNumber
# CustomerId
# Surname
# Display the first 10 rows.

df_new = df.drop({"RowNumber","CustomerId","Surname"},axis = 1)
df_new

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [96]:
#19. Drop the Geography column and display dataset information again.

In [97]:
#20. Rename NumOfProducts to Products and HasCrCard to CreditCard.
df.rename(columns = {"NumOfProducts":"Product","HasCrCard":"CreditCard"},inplace = True)
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'Product', 'CreditCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

# Hard Level (21–30)

In [13]:
#21. (Real Company Task)
# Your manager wants cleaner column names.
# Rename every column as follows:
# RowNumber → Row_No
# CustomerId → Customer_ID
# Surname → Last_Name
# CreditScore → Credit_Score
# Geography → Country
# Gender → Sex
# EstimatedSalary → Salary
# Exited → Target
# Display the first five rows.


df.rename(columns = {"RowNumber":"Row_No","CustomerId":"Customer_ID","Surname":"Last_Name","CreditScore":"Credit_Score","Geography":"Country","Gender":"Sex","EstimatedSalary":"Salary","Exited":"Target"},inplace = True)
df.columns

df.head(5)

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Sex,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [14]:
#22. Create a new DataFrame that contains only numeric columns.
# Then generate its statistical summary.

int_column=df.select_dtypes(include = ["int64"]).columns

df.describe()

,Row_No,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [15]:
#23. Your company received duplicate customer records.
# Tasks:
# • Count duplicates.
# • Remove duplicates.
# • Display dataset information after cleaning.

df.drop_duplicates
df.duplicated().sum()
df.head()

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Sex,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [16]:
#24. Management wants every column name to begin with
# Customer_
# Apply this transformation using the appropriate method.

df.add_prefix("Customer_")

,Customer_Row_No,Customer_Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Age,Customer_Tenure,Customer_Balance,Customer_NumOfProducts,Customer_HasCrCard,Customer_IsActiveMember,Customer_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [120]:
#25. After renaming the columns, convert
# Age
# Balance
# Salary
# to float datatype.
# Print dataset information.

int_column=df.select_dtypes(include = ["int64"]).columns
len(int_column)

9

In [121]:
#26. Assume CreditScore contains missing values.
# Replace them with the median CreditScore.

CreditScore_median = df['CreditScore'].median()
CreditScore_median

652.0

In [31]:
#27.Assume EstimatedSalary contains missing values.
# Replace them with the mean salary.
# Then print the first eight rows.
df1 = pd.read_csv("C:\\Users\\Shree\\Downloads\\Bank_customer_churn.csv")

mean_salary = df1["EstimatedSalary"].mean()
df1["EstimatedSalary"].fillna(mean_salary)
print(df1.head(8))

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43
5          6    15574012       Chu          645     Spain    Male   44
6          7    15592531  Bartlett          822    France    Male   50
7          8    15656148    Obinna          376   Germany  Female   29

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1
5       8  113755.78              2          1               0
6       7       0.00              2          1               1
7       4  115046.74              4          1               0

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0
5        149756.71       1
6         10062.80       0
7        119346.88       1

In [19]:
#28.(Data Cleaning Challenge)
# Perform all the following:
# • Remove duplicate rows.
# • Rename Exited to Target.
# • Convert Target to string.
# • Display dataset information.

df= df.drop_duplicates()
df.rename(columns={"Exited":"Target"})
df["Target"] = df["Target"].astype(str)
df.info

<bound method DataFrame.info of       Row_No  Customer_ID  Last_Name  Credit_Score  Country     Sex  Age  \
0          1     15634602   Hargrave           619   France  Female   42
1          2     15647311       Hill           608    Spain  Female   41
2          3     15619304       Onio           502   France  Female   42
3          4     15701354       Boni           699   France  Female   39
4          5     15737888   Mitchell           850    Spain  Female   43
...      ...          ...        ...           ...      ...     ...  ...
9995    9996     15606229   Obijiaku           771   France    Male   39
9996    9997     15569892  Johnstone           516   France    Male   35
9997    9998     15584532        Liu           709   France  Female   36
9998    9999     15682355  Sabbatini           772  Germany    Male   42
9999   10000     15628319     Walker           792   France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0          2       0.00              1          1               1  101348.88
1          1   83807.86              1          0               1  112542.58
2          8  159660.80              3          1               0  113931.57
3          1       0.00              2          0               0   93826.63
4          2  125510.82              1          1               1   79084.10
...      ...        ...            ...        ...             ...        ...
9995       5       0.00              2          1               0   96270.64
9996      10   57369.61              1          1               1  101699.77
9997       7       0.00              1          0               1   42085.58
9998       3   75075.31              2          1               0   92888.52
9999       4  130142.79              1          1               0   38190.78

     Target
0         1
1         0
2         1
3         0
4         0
...     ...
9995      0
9996      0
9997      1
9998      1
9999      0

[10000 rows x 14 columns]>

In [8]:
#29.(Transformation Challenge)
# Create a copy of the dataset.
# Perform these transformations:
# • Rename Gender to CustomerGender
# • Rename Geography to Country
# • Add prefix Bank_
# • Remove RowNumber
# • Display first 10 rows

df_copy = df.copy()
df_copy.rename(columns={"Gender":"CustomerGender","Geography":"Country"},inplace = True)
df_copy = df_copy.add_prefix("Bank_")
df_copy.drop(columns=["Bank_RowNumber"],inplace = True)
print(df_copy.head(10))

   Bank_CustomerId Bank_Surname  Bank_CreditScore Bank_Country  \
0         15634602     Hargrave               619       France
1         15647311         Hill               608        Spain
2         15619304         Onio               502       France
3         15701354         Boni               699       France
4         15737888     Mitchell               850        Spain
5         15574012          Chu               645        Spain
6         15592531     Bartlett               822       France
7         15656148       Obinna               376      Germany
8         15792365           He               501       France
9         15592389           H?               684       France

  Bank_CustomerGender  Bank_Age  Bank_Tenure  Bank_Balance  \
0              Female        42            2          0.00
1              Female        41            1      83807.86
2              Female        42            8     159660.80
3              Female        39            1          0.00
4              Female        43            2     125510.82
5                Male        44            8     113755.78
6                Male        50            7          0.00
7              Female        29            4     115046.74
8                Male        44            4     142051.07
9                Male        27            2     134603.88

   Bank_NumOfProducts  Bank_HasCrCard  Bank_IsActiveMember  \
0                   1               1                    1
1                   1               0                    1
2                   3               1                    0
3                   2               0                    0
4                   1               1                    1
5                   2               1                    0
6                   2               1                    1
7                   4               1                    0
8                   2               0                    1
9                   1               1                    1

   Bank_EstimatedSalary  Bank_Exited
0             101348.88            1
1             112542.58            0
2             113931.57            1
3              93826.63            0
4              79084.10            0
5             149756.71            1
6              10062.80            0
7             119346.88            1
8              74940.50            0
9              71725.73            0

In [29]:
#30. Real Industry Mini Project

# Your manager asks you to prepare a cleaned dataset for the Machine Learning team.
# Perform all of these steps:
# 1. Load the dataset.
# 2. Display dataset information.
# 3. Check missing values.
# 4. Remove duplicate rows.
# 5. Rename the following columns:
# o CustomerId → Customer_ID
# o CreditScore → Credit_Score
# o EstimatedSalary → Salary
# o Exited → Target
# 6. Convert:
# o Age → float
# o Balance → float
# o Target → string
# 7. Replace missing values:
# o Age → median
# o Balance → mean
# 8 . Remove:
# o RowNumber
# o Surname
# 9. Display:
# o First 10 rows
# o Statistical summary
# o Value counts of Target
# o Final dataset information

df = pd.read_csv("C:\\Users\\Shree\\Downloads\\Bank_customer_churn.csv")
df
print(df.info())
print(df.isnull().sum())
df = df.drop_duplicates()

df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
}, inplace=True)

df["Age"] = df["Age"].astype(float)
df["Balance"] =df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

df["Age"].fillna(df["Age"].median())
df["Balance"].fillna(df["Balance"].mean())
df.drop(columns = ["RowNumber","Surname"])

print(df.head(10))
print(df.describe())
print(df["Target"].value_counts())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
   RowNumber  Customer_ID   Surname  Credit_Score Geography  Gender   Age  \
0          1     15634602  Hargrave           619    France  Female  42.0
1          2     15647311      Hill           608     Spain  Female  41.0
2          3     15619304      Onio           502    France  Female  42.0
3          4     15701354      Boni           699    France  Female  39.0
4          5     15737888  Mitchell           850     Spain  Female  43.0
5          6     15574012       Chu           645     Spain    Male  44.0
6          7     15592531  Bartlett           822    France    Male  50.0
7          8     15656148    Obinna           376   Germany  Female  29.0
8          9     15792365        He           501    France    Male  44.0
9         10     15592389        H?           684    France    Male  27.0

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0       2       0.00              1          1               1  101348.88
1       1   83807.86              1          0               1  112542.58
2       8  159660.80              3          1               0  113931.57
3       1       0.00              2          0               0   93826.63
4       2  125510.82              1          1               1   79084.10
5       8  113755.78              2          1               0  149756.71
6       7       0.00              2          1               1   10062.80
7       4  115046.74              4          1               0  119346.88
8       4  142051.07              2          0               1   74940.50
9       2  134603.88              1          1               1   71725.73

  Target
0      1
1      0
2      1
3      0
4      0
5      1
6      0
7      1
8      0
9      0
         RowNumber   Customer_ID  Credit_Score           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000
mean    76485.889288       1.530200      0.70550        0.515100
std     62397.405202       0.581654      0.45584        0.499797
min         0.000000       1.000000      0.00000        0.000000
25%         0.000000       1.000000      0.00000        0.000000
50%     97198.540000       1.000000      1.00000        1.000000
75%    127644.240000       2.000000      1.00000        1.000000
max    250898.090000       4.000000      1.00000        1.000000

              Salary
count   10000.000000
mean   100090.239881
std     57510.492818
min        11.580000
25%     51002.110000
50%    100193.915000
75%    149388.247500
max    199992.480000
Target
0    7963
1    2037
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RowNumber       10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Surname         10000 non-null  object
 3   Credit_Score    10000 non-null  int64
 4   Geography       10000 non-null  object
 5   Gender          10000 non-null  object
 6   Age             10000 non-null  float64
 7   Tenure          10000 non-null  int64
 8   Balance         10000 non-null  float64
 9   NumOfProducts   10000 non-null  int64
 10  HasCrCard       10000 non-null  int64
 11  IsActiveMember  10000 non-null  int64
 12  Salary          10000 non-null  float64
 13  Target          10000 non-null  object
dtypes: float64(3), int64(7), object(4)
memory usage: 1.1+ MB

# Bonus Challenge (Create New Columns)

In [32]:
#B1 Create a new column: TotalMoney = Balance + EstimatedSalary
df2 = pd.read_csv("C:\\Users\\Shree\\Downloads\\Bank_customer_churn.csv")

df2["TotalMoney"] = df2["Balance"] + df2["EstimatedSalary"]
print(df2.head(10))

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43
5          6    15574012       Chu          645     Spain    Male   44
6          7    15592531  Bartlett          822    France    Male   50
7          8    15656148    Obinna          376   Germany  Female   29
8          9    15792365        He          501    France    Male   44
9         10    15592389        H?          684    France    Male   27

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1
5       8  113755.78              2          1               0
6       7       0.00              2          1               1
7       4  115046.74              4          1               0
8       4  142051.07              2          0               1
9       2  134603.88              1          1               1

   EstimatedSalary  Exited  TotalMoney
0        101348.88       1   101348.88
1        112542.58       0   196350.44
2        113931.57       1   273592.37
3         93826.63       0    93826.63
4         79084.10       0   204594.92
5        149756.71       1   263512.49
6         10062.80       0    10062.80
7        119346.88       1   234393.62
8         74940.50       0   216991.57
9         71725.73       0   206329.61

In [34]:
# B2 Create a new column: DoubleScore = CreditScore × 2

df["DoubleScore"] = df["Credit_Score"] * 2
print(df.head(10))

   RowNumber  Customer_ID   Surname  Credit_Score Geography  Gender   Age  \
0          1     15634602  Hargrave           619    France  Female  42.0
1          2     15647311      Hill           608     Spain  Female  41.0
2          3     15619304      Onio           502    France  Female  42.0
3          4     15701354      Boni           699    France  Female  39.0
4          5     15737888  Mitchell           850     Spain  Female  43.0
5          6     15574012       Chu           645     Spain    Male  44.0
6          7     15592531  Bartlett           822    France    Male  50.0
7          8     15656148    Obinna           376   Germany  Female  29.0
8          9     15792365        He           501    France    Male  44.0
9         10     15592389        H?           684    France    Male  27.0

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0       2       0.00              1          1               1  101348.88
1       1   83807.86              1          0               1  112542.58
2       8  159660.80              3          1               0  113931.57
3       1       0.00              2          0               0   93826.63
4       2  125510.82              1          1               1   79084.10
5       8  113755.78              2          1               0  149756.71
6       7       0.00              2          1               1   10062.80
7       4  115046.74              4          1               0  119346.88
8       4  142051.07              2          0               1   74940.50
9       2  134603.88              1          1               1   71725.73

  Target  DoubleScore
0      1         1238
1      0         1216
2      1         1004
3      0         1398
4      0         1700
5      1         1290
6      0         1644
7      1          752
8      0         1002
9      0         1368

In [35]:
# B3
# Create a new column:
# AgeAfter10Years = Age + 10

df["AgeAfter10Years"] = df["Age"] + 10
print(df.head(10))

   RowNumber  Customer_ID   Surname  Credit_Score Geography  Gender   Age  \
0          1     15634602  Hargrave           619    France  Female  42.0
1          2     15647311      Hill           608     Spain  Female  41.0
2          3     15619304      Onio           502    France  Female  42.0
3          4     15701354      Boni           699    France  Female  39.0
4          5     15737888  Mitchell           850     Spain  Female  43.0
5          6     15574012       Chu           645     Spain    Male  44.0
6          7     15592531  Bartlett           822    France    Male  50.0
7          8     15656148    Obinna           376   Germany  Female  29.0
8          9     15792365        He           501    France    Male  44.0
9         10     15592389        H?           684    France    Male  27.0

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0       2       0.00              1          1               1  101348.88
1       1   83807.86              1          0               1  112542.58
2       8  159660.80              3          1               0  113931.57
3       1       0.00              2          0               0   93826.63
4       2  125510.82              1          1               1   79084.10
5       8  113755.78              2          1               0  149756.71
6       7       0.00              2          1               1   10062.80
7       4  115046.74              4          1               0  119346.88
8       4  142051.07              2          0               1   74940.50
9       2  134603.88              1          1               1   71725.73

  Target  DoubleScore  AgeAfter10Years
0      1         1238             52.0
1      0         1216             51.0
2      1         1004             52.0
3      0         1398             49.0
4      0         1700             53.0
5      1         1290             54.0
6      0         1644             60.0
7      1          752             39.0
8      0         1002             54.0
9      0         1368             37.0

In [37]:
# B4
# Create a new column:
# HasBalance = Balance
# Replace missing values in this new column using the mean.

df["HasBalance"] = df["Balance"]
mean_balance = df["HasBalance"].mean()
df["HasBalance"].fillna(mean_balance)
print(df.head(10))

   RowNumber  Customer_ID   Surname  Credit_Score Geography  Gender   Age  \
0          1     15634602  Hargrave           619    France  Female  42.0
1          2     15647311      Hill           608     Spain  Female  41.0
2          3     15619304      Onio           502    France  Female  42.0
3          4     15701354      Boni           699    France  Female  39.0
4          5     15737888  Mitchell           850     Spain  Female  43.0
5          6     15574012       Chu           645     Spain    Male  44.0
6          7     15592531  Bartlett           822    France    Male  50.0
7          8     15656148    Obinna           376   Germany  Female  29.0
8          9     15792365        He           501    France    Male  44.0
9         10     15592389        H?           684    France    Male  27.0

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0       2       0.00              1          1               1  101348.88
1       1   83807.86              1          0               1  112542.58
2       8  159660.80              3          1               0  113931.57
3       1       0.00              2          0               0   93826.63
4       2  125510.82              1          1               1   79084.10
5       8  113755.78              2          1               0  149756.71
6       7       0.00              2          1               1   10062.80
7       4  115046.74              4          1               0  119346.88
8       4  142051.07              2          0               1   74940.50
9       2  134603.88              1          1               1   71725.73

  Target  DoubleScore  AgeAfter10Years  HasBalance
0      1         1238             52.0        0.00
1      0         1216             51.0    83807.86
2      1         1004             52.0   159660.80
3      0         1398             49.0        0.00
4      0         1700             53.0   125510.82
5      1         1290             54.0   113755.78
6      0         1644             60.0        0.00
7      1          752             39.0   115046.74
8      0         1002             54.0   142051.07
9      0         1368             37.0   134603.88

In [38]:
#B5
# Create a new column:
# SalaryInLakhs = EstimatedSalary / 100000

df["SalaryInLakhs"] = df["EstimatedSalary"] / 100000
print(df.head(10))

KeyError: 'EstimatedSalary'