In [37]:
# 1. Load the dataset using the appropriate Pandas method and store it in a
# variable named df.

import pandas as pd

df = pd.read_csv("C:\\Users\\Shree\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [38]:
#2. Display the first 8 rows of the dataset.

df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [39]:
#3. Display the last 12 rows of the dataset.
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [40]:
#4. Show 10 random rows from the dataset.

df.sample(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
2975,2976,15774179,Sutherland,487,France,Male,37,6,0.00,2,1,1,126477.41,0
4431,4432,15783629,Degtyaryov,616,Germany,Female,42,6,117899.95,2,0,0,150266.81,0
8507,8508,15771749,Duncan,653,Germany,Female,38,5,114268.22,2,1,1,89524.83,0
1722,1723,15624391,Thomson,595,Spain,Female,30,5,100683.54,1,1,1,178361.04,0
4997,4998,15613886,Trevisan,722,Spain,Male,43,1,0.00,1,1,0,44560.17,1
4526,4527,15604818,Edmund la Touche,798,France,Male,34,9,154495.79,1,1,0,191395.88,0
3746,3747,15804709,Watt,688,Germany,Male,35,5,111578.18,1,0,0,166165.93,1
8690,8691,15756167,Doyne,762,Spain,Female,43,5,134204.67,1,1,1,139971.01,0
3993,3994,15779414,Rossi,696,Spain,Male,40,3,153639.11,1,1,1,138351.68,0
5410,5411,15723613,Jenkins,623,France,Female,28,4,0.00,2,1,0,41227.67,0
4848,4849,15807167,Konovalova,635,France,Male,42,1,146766.72,2,0,1,164357.10,0

In [41]:
#5. Find the shape of the dataset.
# o How many rows are there?
# o How many columns are there?

rows,cols = df.shape
print("no.of rows:",rows)
print("no.of columns:",cols)

no.of rows: 10000
no.of columns: 14

In [42]:
#6. Display complete information about the dataset using one method.
# o Number of non-null values
# o Data types
# o Memory usage 


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [43]:
#7. Print the names of all columns in the dataset.

print(list(df.columns))

['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']

In [44]:
#8. Find the data type of every column.

df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [45]:
#9. Check for missing values in every column using:
# o isnull().sum()
# o isna().sum()

df.isnull().sum()
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [46]:
#10.Select only one column:
# o CreditScore

credit = df["CreditScore"]
print(credit)

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [47]:
#11.Select the following multiple columns:
# o CustomerId
# o Surname
# o Balance
# o Exited

selected= df[["CustomerId","Balance","Exited"]]
print(selected.head())

   CustomerId    Balance  Exited
0    15634602       0.00       1
1    15647311   83807.86       0
2    15619304  159660.80       1
3    15701354       0.00       0
4    15737888  125510.82       0

In [50]:
#12. Display only numeric columns using select_dtypes().

df.select_dtypes(include=['number'])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [51]:
# 13.Generate the statistical summary of all numeric columns using describe().

df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [54]:
#14.Check for duplicate rows in the dataset.
# o How many duplicate rows exist?
# o Remove all duplicate rows.

duplicates = df.duplicated().sum()

In [66]:
#15.Count the number of customers in each class of the Exited column using
# value_counts().

counts = df["Exited"].value_counts()
print(counts)

Exited
0    7963
1    2037
Name: count, dtype: int64

# Operators + Loops (1-5)

In [68]:
#1. Take two numbers from user. Perform all arithmetic operations and also check
# which number is greater using comparison operators.

a =int(input("Enter a no.:"))
b = int(input("Enter a no.:"))

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:",a//b)
print("Modulus:", a%b)
print("Exponent:", a**b)

Enter a no.: 23
Enter a no.: 34

Addition: 57
Subtraction: -11
Multiplication: 782
Division: 0.6764705882352942
Floor Division: 0
Modulus: 23
Exponent: 19895113660064588580108197261066338165074766609

In [69]:
#2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop
# completely when number 40 is reached using break.

for i in range(1,51):
    if i % 5 == 0:
        continue
    if i == 40:
        break
    print(i, end = " ")

1 2 3 4 6 7 8 9 11 12 13 14 16 17 18 19 21 22 23 24 26 27 28 29 31 32 33 34 36 37 38 39 41 42 43 44 46 47 48 49

In [70]:
#3. Take numbers from user until they enter negative number. Calculate sum and
# average using while loop.

total = 0
count = 0
while True:
    num = int(input("Enter a no.:"))

    if num < 0:
        break
    total += num
    count += 1

if count > 0:
    average = total / count
    print("sum =", total)
    print("Average=", average)
else:
    print("No positive numbers entered.")

Enter a no.: 3
Enter a no.: 23
Enter a no.: 34
Enter a no.: -1

sum = 60
Average= 20.0

In [71]:
# 4. Print the following pattern using nested loops:
# *****
# ****
# ***
# **
# *

rows = 5
for i in range(rows,0,-1):
    for j in range(i):
        print("*", end = " ")
    print()

* * * * *
* * * *
* * *
* *
*

In [72]:
# 5. Find the factorial of a number using for loop and also using while loop.

num = int(input("Enter a no.:"))
fact = 1
for i in range(1,num+1):
    fact *= i
print("Factorial=",fact)

Enter a no.: 23

Factorial= 25852016738884976640000

# Data Types & Methods (6-9)

In [79]:
#6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace
# spaces with -, and check if it starts with “Hello”.

text = input("Enter a string:")

print("Uppercase:",text.upper())
print("Occurrence of 'a':",text.count('a'))
print("Replace :", text.replace(" ","-"))
print("Start with 'Hello':",text.startswith("Hello"))

Enter a string: sdfg

Uppercase: SDFG
Occurrence of 'a': 0
Replace : sdfg
Start with 'Hello': False

In [89]:
#7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)
# and reverse.

list = [1,2,3,4,5,6]
print("Original list:",list)
list.append(34)
print("append:",list)
list.insert(23,2)
print("insert:",list)
list.remove(2)
print("remove:",list)
list.sort(reverse = True)
print("reverse:", list)

Original list: [1, 2, 3, 4, 5, 6]
append: [1, 2, 3, 4, 5, 6, 34]
insert: [1, 2, 3, 4, 5, 6, 34, 2]
remove: [1, 3, 4, 5, 6, 34, 2]
reverse: [34, 6, 5, 4, 3, 2, 1]

In [95]:
#8. Create a dictionary of 4 students (name:marks). Print only those students who
# scored more than 80 using items().

students = {
    "Ram": 75,
    "Amit": 92,
    "Neha": 88,
    "Raj": 60
}

print("Students scoring more than 80:")
for name, marks in students.items():
    if marks > 80:
        print(name, ":", marks)

Students scoring more than 80:
Amit : 92
Neha : 88

In [108]:
#9. Create two sets and perform union, intersection, difference. Also add and discard
# elements.

set1 = {3,4,5,6}
set2 = {1,2,3,4}

print("set1:",set1)
print("set2:",set2)

print("Union:",set1.union(set2))
print("intersection:",set1.intersection(set2))
print("difference:",set1.difference(set2))

set1.add(7)
print("set1:", set1)

set2.discard(7)
print("set2:",set2)

set1: {3, 4, 5, 6}
set2: {1, 2, 3, 4}
Union: {1, 2, 3, 4, 5, 6}
intersection: {3, 4}
difference: {5, 6}
set1: {3, 4, 5, 6, 7}
set2: {1, 2, 3, 4}

# OOP + Encapsulation (10-14)

In [113]:
#10. Create a class Student with private attribute __marks. Add getter and setter with
# validation (0–100).

class Student:
    def __init__(self,marks):
        self.__marks = marks
    def set_marks(self,n_marks):
        if 0 <= marks <= 100:
            self.__marks = n_marks
            print("marks updated sucessfully.")
        else:
            print("Marks must be between 0 and 100")
    def get_marks(self):
        return self.__marks
s = Student(77)
print(s.set_marks(67))

print(s.get_marks())

marks updated sucessfully.
None
67

In [116]:
#11. Create class BankAccount with private __balance. Add deposit and withdraw
# methods. Raise custom exception if balance becomes negative.


class NegativeBalanceError(Exception):
    def __init__(self, message="Balance cannot be negative!"):
        super().__init__(message)


class BankAccount:
    def __init__(self,balance=0):
        self.__balance = balance
    def deposit(self,amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited {amount}.current balance:{self.__balance}")
        else:
            print(f"Deposit amount must be greater than 0.")
    def withdraw(self,amount):
        if amount <= 0:
            print("withdraw amount must be greater than 0")
        elif amount > self.__balance:
            raise NegativBalanceError("Insufficient funds:")
        else:
            self.__balance -= amount
            print(f"withdraw {amount}")
    def get_balance(self):
        return self.__balance
try:
    acc = BankAccount(20000)
    acc.deposit(500)
    acc.withdraw(800)
except NegativeBalanceError as e:
    print("Exception:",e)

Deposited 500.current balance:20500
withdraw 800

In [118]:
#12. Create class Employee with class attribute company_name. Show that it is
# shared by all objects. Also update the class attribute.

class Employee:
    Company_name = "Google"
    
    def __init__(self,name):
        self.name = name 
    def show(self):
        print(f"name :",{self.name})
e = Employee("Raghav")
e.show()

Employee.company_name = "Microsoft"

print("company name is updated:")
e.show()

name : {'Raghav'}
company name is updated:
name : {'Raghav'}

In [121]:
#13. Create class Product with private __price. Add getter and setter. Setter should
# not allow price less than 100.

class Product:
    def __init__(self,price):
        self.__price = price
        self.set_price(price)
    def set_price(self,price):
        if price >= 100:
            self.__price = price
            print("Price set sucessfully.")
        else:
            print("price always less than 100")
    def get_price(self):
        return self.__price

p = Product(200)
print("price:",p.get_price())

p.set_price(500)
print("price:",p.get_price())

Price set sucessfully.
price: 200
Price set sucessfully.
price: 500

In [126]:
#14.Create class Rectangle with private length and width. Add method to calculate
# area and perimeter.

class Rectangle:
    def __init__(self,length,width):
        self.__length = length
        self.__width = width
    def area(self):
        return self.__length * self.__width
    def perimeter(self):
        return 2*(self.__length + self.__width)
    def get_length(self):
        return self.__length
    def get_width(self):
        return self.__width
r = Rectangle(23,5)

print(r.area())
print(r.perimeter())
print(r.get_length())
print(r.get_width())

115
56
23
5

# Inheritance + Abstraction + super() (15-19)

In [132]:
#15. Create single level inheritance: Person → Student. Use super() in constructor.

class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def show_info(self):
        print(f"name: {self.name}, age: {self.age}")
class Student(Person):
    def __init__(self,name,age,marks):
        super().__init__(name,age)
        self.marks = marks
    def show_info(self):
        print(f"marks: {self.marks}")

p = Person("Shweta",34)
p.show_info()

s = Student("Shweta",34,99)
s.show_info()

name: Shweta, age: 34
marks: 99

In [137]:
#16. Create multi-level inheritance: Person → Employee → Manager. Override a
# method at each level.

class Person:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(f"Person name :{self.name}")
class Employee(Person):
    def __init__(self,name,salary):
        self.salary = salary
        super().__init__(name)
    def show(self):
        print(f"Employee salary:{self.salary}")
class Manager(Employee):
    def __init__(self,name,salary,department):
        self.department = department
        super().__init__(name,salary)
    def show(self):
        print(f"Manager department : {self.department}")
        
e = Employee("Mahi",40000)
e.show() 

m = Manager("Mahi",30000,"IT")
m.show()

Employee salary:40000
Manager department : IT

In [141]:
#17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound()
# method.

class Animal:
    def sound(self):
        print("Animal sound:")
class Dog(Animal):
    def sound(self):
        print("Dog sound bhauuu...")
class cat(Animal):
    def sound(self):
        print("Cat sound meowww...")

d = Dog()
d.sound()

c = cat()
c.sound()

Dog sound bhauuu...
Cat soun meowww...

In [146]:
#18. Create abstract class Shape with abstract method area(). Implement it in Circle
# and Square using super().

from abc import ABC, abstractmethod

class Shape(ABC):
    def __init__(self,color):
        self.color = color
    @abstractmethod
    def area(self):
        pass
class Circle(Shape):
    def __init__(self,radius,color):
        super().__init__(color)
        self.radius = radius
    def area(self):
        return 3.14 * (self.radius ** 2)
class Square(Shape):
    def __init__(self,side,color):
        super().__init__(color)
        self.side = side
    def area(self):
        return self.side ** 2

c = Circle(6,"Red")
print(c.area())

s = Square(5,"Red")
print(s.area())

113.04
25

In [147]:
#19. Create multiple inheritance with two classes Father and Mother. Create child
# class and resolve method conflict.

class Father:
    def skill(self):
        print("Father: Teaching")
class Mother:
    def skill(self):
        print("Mother: Cooking")
class Child(Father,Mother):
    def skill(self):
        print("Child : Drawing")
        Father.skill(self)
        Mother.skill(self)

c = Child()
c.skill()

Child : Drawing
Father: Teaching
Mother: Cooking

# Overloading + Exception + File Handling (20-25)

In [149]:
#20. Create a class Calculator that can add 2 or 3 numbers (method overloading
# using *args). 

class Calculator:
    def add(self, *args):
        if len(args) == 2:
            return args[0] + args[1]
        elif len(args) == 3:
            return args[0] + args[2]
        else:
            raise ValueError("Provide either 2 or 3 numbers")
calc = Calculator()

print(calc.add(12,34))
print(calc.add(2,3,4))

46
6

In [156]:
#21. Create class Point and overload + and > operators.

class Point:
    def __init__(self,x,y):
       self.x = x
       self.y = y
    def __add__(self,other):
       return Point(self.x + other.x, self.y + other.y)
    def __gt__(self,other):
        self_dist = (self.x**2 + self.y**2) ** 0.5
        other_dist = (self.x**2 + self.y**2) ** 0.5
        return self_dist >other_dist
    def __str__(self):
        return f"Point({self.x}, {self.y})"
        
p1= Point(5,5)
p2= Point(7,7)
print("Addition:",p1+p2)
print("Is p1 > p2",p1>p2)
print("Is p1 >p2", p1>p2)

Addition: Point(12, 12)
Is p1 > p2 False
Is p1 >p2 False

In [157]:
#22. Write a program that handles ZeroDivisionError, ValueError and IndexError using
# multiple except blocks.


try:
    num1 = int(input("Enter numerator:"))
    num2 = int(input("Enter denomerator:"))

    result = num1 / num2
    print("Result =",result)

    my_list = [10, 20, 30]
    index = int(input("Enter index (0-2): "))
    print("Element at index:", my_list[index])
except ZeroDivisionError:
    print("Error: please enter the valid no. zero is not allowed:")
except ValueError:
    print("Error: Please enter the valid integers only.")
except IndexError:
    print("Error: Index out of range:")

Enter numerator: 23
Enter denomerator: 34

Result = 0.6764705882352942

Enter index (0-2):  34

Error: Index out of range:

In [158]:
#23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.

class InvalidAgeError(Exception):
    def __init__(self,message = "Age must be at least 18."):
        super().__init__(message)
try:
    age = int(input("Enter your age:"))
    if age < 18:
        raise InvalidAgeError("Access Denied: Age is less than 18.")
    else:
        print("Access Granted Age = ", age)
except InvalidAgeError as e:
    print("Error:",e)
except ValueError:
    print("Error: Please enter a valid integer age.")

Enter your age: 23

Access Granted Age =  23

In [162]:
#24. Write a program to read a file, count number of words, and write the count into
# another file.

try:
    with open("inforamation.txt","r") as infile:
        content = infile.read()
    words = content.split()
    word_count = len(words)

    with open("output.txt","w") as outfile:
        outfile.write("Total no. of words:" + str(word_count))
    print("word count written to output.txt")

except FileNotFoundError:
    print("Error : The file does not exist.")
except PermissionError:
    print("Error : You dont have permission to read this file.")

Error : The file does not exist.

In [163]:
#25. Create a menu-driven program for file operations: Write, Read, Append, and Exit.
# Handle FileNotFoundError.

while True:
    print("\nMenu:")
    print("1. Write to file")
    print("2. Read file")
    print("3. Append to file")
    print("4. Exit")

    choice = int(input("Enter your choice :"))

    if choice == 1:
        filename = input("Enter filename:")
        data = input("Enter text to write:")
        with open(filename,"w") as file:
            file.write(data + "\n")
        print("Data written sucessfully.")
    elif choice == 2:
        filename = input("Enter filename:")
        try:
            with open(filename,"r")as file:
                content = file.read()
                print("\n file content :\n",content)
        except FileNotFoundError:
            print("Error: File not found. Please write something first.")

    elif choice == 3:
        # Append content
        filename = input("Enter filename: ")
        try:
            data = input("Enter text to append: ")
            with open(filename, "a") as file:
                file.write(data + "\n")
            print("Data appended successfully.")
        except FileNotFoundError:
            print("Error: File not found. Please create/write file first.")

    elif choice == 4:
        print("Exiting program... Goodbye!")
        break

    else:
        print("Invalid choice! Please try again.")

Menu:
1. Write to file
2. Read file
3. Append to file
4. Exit

Enter your choice : 1
Enter filename: 2ert
Enter text to write: df

Data written sucessfully.

Menu:
1. Write to file
2. Read file
3. Append to file
4. Exit

Enter your choice : 23

Invalid choice! Please try again.

Menu:
1. Write to file
2. Read file
3. Append to file
4. Exit

Enter your choice : 4

Exiting program... Goodbye!