In [69]:
# 1. Load the CSV using Pandas and display the first 10 rows.

import pandas as pd

df = pd.read_csv("C:\\Users\\Shree\\Downloads\\customer_data.csv") 
df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [70]:
# 2. Check the number of rows and columns in the dataset.

df.shape

(2000, 15)

In [71]:
#3. Display all column names and identify which column names contain
# leading/trailing spaces or inconsistent capitalization.


df.columns

Index(['Customer ID', 'Age ', 'income_usd', 'credit Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [72]:
space_cols = [col for col in df.columns if col!= col.strip()]
space_cols

['Age ']

In [73]:
cap_cols = [col for col in df.columns if not col.islower() and not col.isupper()]
cap_cols

['Customer ID', 'Age ', 'credit Score', 'City']

In [74]:
# 4. Check the data type of every column using Pandas.

df.dtypes

Customer ID          object
Age                  object
income_usd           object
credit Score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

In [75]:
# 5. Calculate the number and percentage of missing values in every column.

missing_value = df.isnull().sum()
missing_value

Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

In [76]:
missing_per = missing_value / len(df) * 100
missing_per

Customer ID          1.00
Age                 16.55
income_usd          22.00
credit Score        18.00
tenure_years        12.90
monthly_visits      14.00
satisfaction        19.95
City                15.00
customer_segment    19.00
gender              12.00
is_active           17.00
churn_flag           8.00
signup_date         12.00
lead_source         21.00
notes_text          32.80
dtype: float64

In [77]:
# 6. Find the rows where Customer ID is missing.

df["Customer ID"] = df["Customer ID"].isnull()
df["Customer ID"]

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: Customer ID, Length: 2000, dtype: bool

In [78]:
# 7. Remove leading/trailing whitespace from all column names and convert them
# to lowercase with underscores.

df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [79]:
# 8. Identify duplicate Customer ID values and count how many duplicates exist.

df["customer_id"] = df["customer_id"].duplicated().sum()
df["customer_id"]

0       1998
1       1998
2       1998
3       1998
4       1998
        ...
1995    1998
1996    1998
1997    1998
1998    1998
1999    1998
Name: customer_id, Length: 2000, dtype: int64

In [80]:
# 9. Remove duplicate customer records while keeping the first occurrence.
df.drop_duplicates

<bound method DataFrame.drop_duplicates of       customer_id                 age          income_usd       credit_score  \
0            1998   45.86741673405659   28198.41033378447  660.5629175986682
1            1998   47.76516427959453   61312.83129054326            838 pts
2            1998                 NaN   44199.67123886594  613.1327753975876
3            1998   62.72357804628894   56259.90961066413  720.2369862405794
4            1998                 NaN  31238.641956219115   549.183252322903
...           ...                 ...                 ...                ...
1995         1998  27.269511776246272   79436.89335323017  633.9740063023814
1996         1998   41.09168505105393  39912.379910506046  701.7201056433207
1997         1998   26.21576696203639  24522.265445928326  647.7993363128053
1998         1998          42.3 years   84103.61055756662            521 pts
1999         1998    59.2560949072122   53723.87392391664   576.739073460913

      tenure_years  monthly_visits  satisfaction       city customer_segment  \
0         5.274076             5.0      3.382150       Pune        consumer
1         5.632826             9.0           NaN  Hyderabad         Consumer
2              NaN             8.0      4.195157     Mumbai         Consumer
3         2.029634             4.0           NaN    Chennai       Enterprise
4         2.648626             5.0      3.117326     Mumbai       Enterprise
...            ...             ...           ...        ...              ...
1995     14.007477             NaN      3.556073  Bengaluru         Consumer
1996      0.673289             8.0      2.963094       Pune              SMB
1997      2.026485            12.0      3.079259  Hyderabad             SMB.
1998      7.168156             5.0      3.579652  Hyderabad              SMB
1999      9.720663             NaN      1.100520       Pune         Consumer

     gender is_active churn_flag signup_date lead_source        notes_text
0       NaN       Yes         No  2026-03-11    Referral               NaN
1      Male       NaN         No         NaN     website  follow-up needed
2         m       Yes         No  2024-09-20       Email               NaN
3         m         N         No  2023-07-12     Website            normal
4      Male       Yes         No  2024-08-06         NaN               ???
...     ...       ...        ...         ...         ...               ...
1995      M        no         No  2024-02-26       email            normal
1996      m         N        Yes  2024-08-11     Website            good
1997      F       yes         No  2023-05-27         WEB               ???
1998    NaN         N        Yes  2025-01-26       Email                ok
1999    NaN       yes         No  2024-02-22         ???            good

[2000 rows x 15 columns]>

In [81]:
# 10.Find all unique values in the customer_segment column and identify
# inconsistent categories such as Consumer, consumer, consumer , etc.


df["customer_segment"].unique()

array(['consumer ', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

In [82]:
#11.Clean the customer_segment column by standardizing capitalization and
# whitespace.

df["customer_segment"] = df["customer_segment"].str.strip().str.lower()
df["customer_segment"]

0         consumer
1         consumer
2         consumer
3       enterprise
4       enterprise
           ...
1995      consumer
1996           smb
1997          smb.
1998           smb
1999      consumer
Name: customer_segment, Length: 2000, dtype: object

In [83]:
# 12.Find all unique values in the gender column and convert them into consistent
# categories such as Male and Female.

df["gender"].unique()

array([nan, 'Male', 'm', 'Female', 'M', 'F', 'f'], dtype=object)

In [84]:
df["gender"] = df["gender"].replace({
    "male": "Male",
    "m": "Male",
    "female": "Female",
    "f": "Female"
})
df["gender"]

0        NaN
1       Male
2       Male
3       Male
4       Male
        ...
1995       M
1996    Male
1997       F
1998     NaN
1999     NaN
Name: gender, Length: 2000, dtype: object

In [85]:
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
# No, no, N, 0 become 0.

df["is_active"] = df["is_active"].replace({
    "Yes": 1, "yes": 1, "Y": 1, "y": 1, 1: 1,
    "No": 0, "no": 0, "N": 0, "n": 0, 0: 0
})
df["is_active"]

0         1
1       NaN
2         1
3         0
4         1
       ...
1995      0
1996      0
1997      1
1998      0
1999      1
Name: is_active, Length: 2000, dtype: object

In [86]:
df["is_active"].value_counts(dropna = False)

is_active
1      625
0      625
NaN    340
1      224
0      186
Name: count, dtype: int64

In [87]:
#14.Convert the churn_flag column from categorical values (Yes/No) into a binary
# numerical column (1/0).

df["churn_flag"].value_counts(dropna=False)

churn_flag
No     1394
Yes     446
NaN     160
Name: count, dtype: int64

In [88]:
df["churn_flag_binary"] = df["churn_flag"].map({"Yes":1,"No":0})
df["churn_flag_binary"]

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1995    0.0
1996    1.0
1997    0.0
1998    1.0
1999    0.0
Name: churn_flag_binary, Length: 2000, dtype: float64

In [89]:
#15.Identify all values in income_usd that cannot be directly interpreted as
# numbers.

income = pd.to_numeric(df["income_usd"],errors = "coerce")
income

0       28198.410334
1       61312.831291
2       44199.671239
3       56259.909611
4       31238.641956
            ...
1995    79436.893353
1996    39912.379911
1997    24522.265446
1998    84103.610558
1999    53723.873924
Name: income_usd, Length: 2000, dtype: float64

In [90]:
numbers = df.loc[income.isna(), "income_usd"]
numbers

5       $44,696
10      $41,941
11          NaN
13          NaN
18          NaN
         ...
1980    $58,046
1985        NaN
1989        NaN
1990        NaN
1991        NaN
Name: income_usd, Length: 645, dtype: object

In [91]:
# 16.Clean income_usd by removing currency symbols, commas, and invalid text,
# then convert it to a numeric column using pd.to_numeric().

df["income_usd"] = df["income_usd"].str.replace("$", "", regex=False)
df["income_usd"] = df["income_usd"].str.replace("USD", "", regex=False)
df["income_usd"] = df["income_usd"].str.replace(",", "", regex=False)
df["income_usd"]

0        28198.41033378447
1        61312.83129054326
2        44199.67123886594
3        56259.90961066413
4       31238.641956219115
               ...
1995     79436.89335323017
1996    39912.379910506046
1997    24522.265445928326
1998     84103.61055756662
1999     53723.87392391664
Name: income_usd, Length: 2000, dtype: object

In [92]:
df["income_usd"] = pd.to_numeric(df["income_usd"],errors = "coerce")
df["income_usd"]

0       28198.410334
1       61312.831291
2       44199.671239
3       56259.909611
4       31238.641956
            ...
1995    79436.893353
1996    39912.379911
1997    24522.265446
1998    84103.610558
1999    53723.873924
Name: income_usd, Length: 2000, dtype: float64

In [93]:
# 17.Clean the Age column so values such as "35 years" become numeric values.

df["age"] = pd.to_numeric(df["age"],errors = "coerce")
df["age"]

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998          NaN
1999    59.256095
Name: age, Length: 2000, dtype: float64

In [94]:
# 18.Identify unrealistic age values using NumPy/Pandas and replace them with
# NaN.

import numpy as np

df["age"] = [age if (0<= age <=120) else np.nan for age in df["age"]]
df["age"]

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998          NaN
1999    59.256095
Name: age, Length: 2000, dtype: float64

In [95]:
#19.Clean the credit_score column by removing text such as "pts" and converting
# the column to numeric.

df["credit_score"] = pd.to_numeric(df["credit_score"], errors="coerce")
df["credit_score"]

0       660.562918
1              NaN
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998           NaN
1999    576.739073
Name: credit_score, Length: 2000, dtype: float64

In [96]:
df["credit_score"] = df["credit_score"].replace("pts", "", regex=False)
df["credit_score"]

0       660.562918
1              NaN
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998           NaN
1999    576.739073
Name: credit_score, Length: 2000, dtype: float64

In [148]:
# 20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["income_usd"] < lower) | (df["income_usd"] > upper)]
print(lower)
print(upper)
print(outliers)

506.3161876841002
796.4586161797977
      customer_id        age    income_usd  credit_score  tenure_years  \
0            1998  45.867417  28198.410334    660.562918      5.274076
1            1998  47.765164  61312.831291    649.277051      5.632826
2            1998  38.016078  44199.671239    613.132775      4.683845
3            1998  62.723578  56259.909611    720.236986      2.029634
4            1998  38.016078  31238.641956    549.183252      2.648626
...           ...        ...           ...           ...           ...
1995         1998  27.269512  79436.893353    633.974006     14.007477
1996         1998  41.091685  39912.379911    701.720106      0.673289
1997         1998  26.215767  24522.265446    647.799336      2.026485
1998         1998  38.016078  84103.610558    649.277051      7.168156
1999         1998  59.256095  53723.873924    576.739073      9.720663

      monthly_visits  satisfaction       city customer_segment gender  \
0                5.0      3.382150       Pune         consumer   Male
1                9.0      3.742125  Hyderabad         consumer   Male
2                8.0      4.195157     Mumbai         consumer   Male
3                4.0      3.742125    Chennai       enterprise   Male
4                5.0      3.117326     Mumbai       enterprise   Male
...              ...           ...        ...              ...    ...
1995             6.0      3.556073  Bengaluru         consumer      M
1996             8.0      2.963094       Pune              smb   Male
1997            12.0      3.079259  Hyderabad             smb.      F
1998             5.0      3.579652  Hyderabad              smb   Male
1999             6.0      1.100520       Pune         consumer   Male

     is_active churn_flag signup_date lead_source        notes_text  \
0            1         No  2026-11-03    Referral            normal
1            0         No         NaT     Website  follow-up needed
2            1         No         NaT       email            normal
3            0         No  2023-12-07     Website            normal
4            1         No  2024-06-08    Referral               ???
...        ...        ...         ...         ...               ...
1995         0         No         NaT       email            normal
1996         0        Yes  2024-11-08     Website            good
1997         1         No         NaT     Website               ???
1998         0        Yes         NaT       email                ok
1999         1         No         NaT         ???            good

      churn_flag_binary
0                   0.0
1                   0.0
2                   0.0
3                   0.0
4                   0.0
...                 ...
1995                0.0
1996                1.0
1997                0.0
1998                1.0
1999                0.0

[1839 rows x 16 columns]

In [151]:
#21.Detect outliers in credit_score using the IQR method.

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["credit_score"] < lower) | (df["credit_score"] > upper)]
print(lower)
print(upper)
print(outliers)

506.3161876841002
796.4586161797977
Empty DataFrame
Columns: [customer_id, age, income_usd, credit_score, tenure_years, monthly_visits, satisfaction, city, customer_segment, gender, is_active, churn_flag, signup_date, lead_source, notes_text, churn_flag_binary]
Index: []

In [99]:
#22.Detect suspicious values such as -999 and 99999 in tenure_years and
# satisfaction.

df["tenure_years"] = [val if val not in [-999,99999] else np.nan for val in df["tenure_years"]]
df["tenure_years"]

0        5.274076
1        5.632826
2             NaN
3        2.029634
4        2.648626
          ...
1995    14.007477
1996     0.673289
1997     2.026485
1998     7.168156
1999     9.720663
Name: tenure_years, Length: 2000, dtype: float64

In [100]:
df["satisfaction"] = [val if val not in [-999,99999] else np.nan for val in df["satisfaction"]]
df["satisfaction"]

0       3.382150
1            NaN
2       4.195157
3            NaN
4       3.117326
          ...
1995    3.556073
1996    2.963094
1997    3.079259
1998    3.579652
1999    1.100520
Name: satisfaction, Length: 2000, dtype: float64

In [101]:
# 23.Replace invalid/suspicious numerical values with NaN.

df["tenure_years"] = df["tenure_years"].replace([-999, 99999], np.nan)
df["satisfaction"] = df["satisfaction"].replace([-999, 99999], np.nan)
df["income_usd"] = df["income_usd"].replace([-999, 99999], np.nan)

In [102]:
df["tenure_years"]

0        5.274076
1        5.632826
2             NaN
3        2.029634
4        2.648626
          ...
1995    14.007477
1996     0.673289
1997     2.026485
1998     7.168156
1999     9.720663
Name: tenure_years, Length: 2000, dtype: float64

In [103]:
df["satisfaction"]

0       3.382150
1            NaN
2       4.195157
3            NaN
4       3.117326
          ...
1995    3.556073
1996    2.963094
1997    3.079259
1998    3.579652
1999    1.100520
Name: satisfaction, Length: 2000, dtype: float64

In [104]:
df["income_usd"]

0       28198.410334
1       61312.831291
2       44199.671239
3       56259.909611
4       31238.641956
            ...
1995    79436.893353
1996    39912.379911
1997    24522.265446
1998    84103.610558
1999    53723.873924
Name: income_usd, Length: 2000, dtype: float64

In [105]:
df["age"] = [age if (0 <= age <= 100) else np.nan for age in df["age"]]
df["age"]

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998          NaN
1999    59.256095
Name: age, Length: 2000, dtype: float64

In [106]:
df["credit_score"] = [score if (300 <= score <= 850) else np.nan for score in df["credit_score"]]
df["credit_score"]

0       660.562918
1              NaN
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998           NaN
1999    576.739073
Name: credit_score, Length: 2000, dtype: float64

In [107]:
df.head()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,NaN,1,No,2026-03-11,Referral,NaN,0.0
1,1998,47.765164,61312.831291,NaN,5.632826,9.0,NaN,Hyderabad,consumer,Male,NaN,No,NaN,website,follow-up needed,0.0
2,1998,NaN,44199.671239,613.132775,NaN,8.0,4.195157,Mumbai,consumer,Male,1,No,2024-09-20,Email,NaN,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,NaN,Chennai,enterprise,Male,0,No,2023-07-12,Website,normal,0.0
4,1998,NaN,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-08-06,NaN,???,0.0

In [108]:
# 24.Fill missing numerical values using the median of each numerical column.

df.fillna(df.median(numeric_only=True))

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,NaN,1,No,2026-03-11,Referral,NaN,0.0
1,1998,47.765164,61312.831291,649.277051,5.632826,9.0,3.742125,Hyderabad,consumer,Male,NaN,No,NaN,website,follow-up needed,0.0
2,1998,38.016078,44199.671239,613.132775,4.683845,8.0,4.195157,Mumbai,consumer,Male,1,No,2024-09-20,Email,NaN,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,3.742125,Chennai,enterprise,Male,0,No,2023-07-12,Website,normal,0.0
4,1998,38.016078,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-08-06,NaN,???,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1998,27.269512,79436.893353,633.974006,14.007477,6.0,3.556073,Bengaluru,consumer,M,0,No,2024-02-26,email,normal,0.0
1996,1998,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,Pune,smb,Male,0,Yes,2024-08-11,Website,good,1.0
1997,1998,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,Hyderabad,smb.,F,1,No,2023-05-27,WEB,???,0.0
1998,1998,38.016078,84103.610558,649.277051,7.168156,5.0,3.579652,Hyderabad,smb,NaN,0,Yes,2025-01-26,Email,ok,1.0
1999,1998,59.256095,53723.873924,576.739073,9.720663,6.0,1.100520,Pune,consumer,NaN,1,No,2024-02-22,???,good,0.0

In [109]:
df.isnull().sum()

customer_id            0
age                  557
income_usd           469
credit_score         560
tenure_years         268
monthly_visits       280
satisfaction         409
city                 300
customer_segment     380
gender               240
is_active            340
churn_flag           160
signup_date          240
lead_source          420
notes_text           656
churn_flag_binary    160
dtype: int64

In [110]:
# 25.Fill missing categorical values using the mode of each categorical column.

df = df.apply(lambda col: col.fillna(col.mode()[0]) if col.dtypes == "object" else col)
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,Male,1,No,2026-03-11,Referral,normal,0.0
1,1998,47.765164,61312.831291,NaN,5.632826,9.0,NaN,Hyderabad,consumer,Male,0,No,not_a_date,website,follow-up needed,0.0
2,1998,NaN,44199.671239,613.132775,NaN,8.0,4.195157,Mumbai,consumer,Male,1,No,2024-09-20,Email,normal,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,NaN,Chennai,enterprise,Male,0,No,2023-07-12,Website,normal,0.0
4,1998,NaN,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-08-06,referral,???,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1998,27.269512,79436.893353,633.974006,14.007477,NaN,3.556073,Bengaluru,consumer,M,0,No,2024-02-26,email,normal,0.0
1996,1998,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,Pune,smb,Male,0,Yes,2024-08-11,Website,good,1.0
1997,1998,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,Hyderabad,smb.,F,1,No,2023-05-27,WEB,???,0.0
1998,1998,NaN,84103.610558,NaN,7.168156,5.0,3.579652,Hyderabad,smb,Male,0,Yes,2025-01-26,Email,ok,1.0
1999,1998,59.256095,53723.873924,576.739073,9.720663,NaN,1.100520,Pune,consumer,Male,1,No,2024-02-22,???,good,0.0

In [111]:
df.isna().sum()

customer_id            0
age                  557
income_usd           469
credit_score         560
tenure_years         268
monthly_visits       280
satisfaction         409
city                   0
customer_segment       0
gender                 0
is_active              0
churn_flag             0
signup_date            0
lead_source            0
notes_text             0
churn_flag_binary    160
dtype: int64

In [112]:
# 26.Clean the signup_date column, which contains multiple date formats and
# invalid dates, and convert it to Pandas datetime.

df["signup_date"] = pd.to_datetime(df["signup_date"], errors="coerce", dayfirst=True)
df["signup_date"]

0      2026-11-03
1             NaT
2             NaT
3      2023-12-07
4      2024-06-08
          ...
1995          NaT
1996   2024-11-08
1997          NaT
1998          NaT
1999          NaT
Name: signup_date, Length: 2000, dtype: datetime64[ns]

In [113]:
df["signup_date"].dtype

dtype('<M8[ns]')

In [114]:
#27.Find rows where signup_date could not be converted into a valid date.

df["signup_date"] = pd.to_datetime(df["signup_date"], errors="coerce")
df["signup_date"]

0      2026-11-03
1             NaT
2             NaT
3      2023-12-07
4      2024-06-08
          ...
1995          NaT
1996   2024-11-08
1997          NaT
1998          NaT
1999          NaT
Name: signup_date, Length: 2000, dtype: datetime64[ns]

In [115]:
df["signup_date"].isna()

0       False
1        True
2        True
3       False
4       False
        ...
1995     True
1996    False
1997     True
1998     True
1999     True
Name: signup_date, Length: 2000, dtype: bool

In [116]:
# 28.Clean the lead_source column by standardizing values such as Website,
# website, WEB, Referral, referral , Google Ads, and google_ads.


df["lead_source"] = df["lead_source"].replace({
    "website": "Website",
    "web": "Website",
    "referral": "Referral",
    "google ads": "Google Ads",
    "google_ads": "Google Ads"
})
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,Male,1,No,2026-11-03,Referral,normal,0.0
1,1998,47.765164,61312.831291,NaN,5.632826,9.0,NaN,Hyderabad,consumer,Male,0,No,NaT,Website,follow-up needed,0.0
2,1998,NaN,44199.671239,613.132775,NaN,8.0,4.195157,Mumbai,consumer,Male,1,No,NaT,Email,normal,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,NaN,Chennai,enterprise,Male,0,No,2023-12-07,Website,normal,0.0
4,1998,NaN,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-06-08,referral,???,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1998,27.269512,79436.893353,633.974006,14.007477,NaN,3.556073,Bengaluru,consumer,M,0,No,NaT,email,normal,0.0
1996,1998,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,Pune,smb,Male,0,Yes,2024-11-08,Website,good,1.0
1997,1998,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,Hyderabad,smb.,F,1,No,NaT,WEB,???,0.0
1998,1998,NaN,84103.610558,NaN,7.168156,5.0,3.579652,Hyderabad,smb,Male,0,Yes,NaT,Email,ok,1.0
1999,1998,59.256095,53723.873924,576.739073,9.720663,NaN,1.100520,Pune,consumer,Male,1,No,NaT,???,good,0.0

In [117]:
#29.Create a final cleaned DataFrame containing:
# • cleaned column names
# • no duplicate IDs
# • standardized categorical values
# • numeric columns converted to numeric types
#• invalid values converted to NaN
# •  missing values handled
# • detected outliers handled

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text',
       'churn_flag_binary'],
      dtype='object')

In [118]:
df = df.drop_duplicates()
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,Male,1,No,2026-11-03,Referral,normal,0.0
1,1998,47.765164,61312.831291,NaN,5.632826,9.0,NaN,Hyderabad,consumer,Male,0,No,NaT,Website,follow-up needed,0.0
2,1998,NaN,44199.671239,613.132775,NaN,8.0,4.195157,Mumbai,consumer,Male,1,No,NaT,Email,normal,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,NaN,Chennai,enterprise,Male,0,No,2023-12-07,Website,normal,0.0
4,1998,NaN,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-06-08,referral,???,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1998,27.269512,79436.893353,633.974006,14.007477,NaN,3.556073,Bengaluru,consumer,M,0,No,NaT,email,normal,0.0
1996,1998,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,Pune,smb,Male,0,Yes,2024-11-08,Website,good,1.0
1997,1998,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,Hyderabad,smb.,F,1,No,NaT,WEB,???,0.0
1998,1998,NaN,84103.610558,NaN,7.168156,5.0,3.579652,Hyderabad,smb,Male,0,Yes,NaT,Email,ok,1.0
1999,1998,59.256095,53723.873924,576.739073,9.720663,NaN,1.100520,Pune,consumer,Male,1,No,NaT,???,good,0.0

In [119]:
df["lead_source"] = df["lead_source"].str.lower().str.strip().replace({
    "website": "Website", "web": "Website",
    "referral": "Referral",
    "google ads": "Google Ads"
})
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,Male,1,No,2026-11-03,Referral,normal,0.0
1,1998,47.765164,61312.831291,NaN,5.632826,9.0,NaN,Hyderabad,consumer,Male,0,No,NaT,Website,follow-up needed,0.0
2,1998,NaN,44199.671239,613.132775,NaN,8.0,4.195157,Mumbai,consumer,Male,1,No,NaT,email,normal,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,NaN,Chennai,enterprise,Male,0,No,2023-12-07,Website,normal,0.0
4,1998,NaN,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-06-08,Referral,???,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1998,27.269512,79436.893353,633.974006,14.007477,NaN,3.556073,Bengaluru,consumer,M,0,No,NaT,email,normal,0.0
1996,1998,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,Pune,smb,Male,0,Yes,2024-11-08,Website,good,1.0
1997,1998,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,Hyderabad,smb.,F,1,No,NaT,Website,???,0.0
1998,1998,NaN,84103.610558,NaN,7.168156,5.0,3.579652,Hyderabad,smb,Male,0,Yes,NaT,email,ok,1.0
1999,1998,59.256095,53723.873924,576.739073,9.720663,NaN,1.100520,Pune,consumer,Male,1,No,NaT,???,good,0.0

In [120]:
numeric_cols = ["age", "annual_income", "account_balance",
                "credit_score", "monthly_spend",
                "transactions", "satisfaction", "tenure_years", "income_usd"]
numeric_cols

['age',
 'annual_income',
 'account_balance',
 'credit_score',
 'monthly_spend',
 'transactions',
 'satisfaction',
 'tenure_years',
 'income_usd']

In [128]:
df["age"] = [val if (0 <= val <= 120) else np.nan for val in df["age"]]
df["credit_score"] = [val if (300 <= val <= 850) else np.nan for val in df["credit_score"]]

print(df["age"])
print(df["credit_score"])

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998          NaN
1999    59.256095
Name: age, Length: 2000, dtype: float64
0       660.562918
1              NaN
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998           NaN
1999    576.739073
Name: credit_score, Length: 2000, dtype: float64

In [123]:
df["tenure_years"] = df["tenure_years"].replace([-999, 99999], np.nan)
df["tenure_years"]

0        5.274076
1        5.632826
2             NaN
3        2.029634
4        2.648626
          ...
1995    14.007477
1996     0.673289
1997     2.026485
1998     7.168156
1999     9.720663
Name: tenure_years, Length: 2000, dtype: float64

In [124]:
df["satisfaction"] = df["satisfaction"].replace([-999, 99999], np.nan)
df["satisfaction"]

0       3.382150
1            NaN
2       4.195157
3            NaN
4       3.117326
          ...
1995    3.556073
1996    2.963094
1997    3.079259
1998    3.579652
1999    1.100520
Name: satisfaction, Length: 2000, dtype: float64

In [125]:
df["income_usd"] = df["income_usd"].replace([-999, 99999], np.nan)
df["income_usd"]

0       28198.410334
1       61312.831291
2       44199.671239
3       56259.909611
4       31238.641956
            ...
1995    79436.893353
1996    39912.379911
1997    24522.265446
1998    84103.610558
1999    53723.873924
Name: income_usd, Length: 2000, dtype: float64

In [132]:
for col in df.select_dtypes(include=["object"]).columns:  # categorical → mode
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\Shree\AppData\Local\Temp\ipykernel_34780\3438159995.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [131]:
df = df.fillna(df.median(numeric_only=True))  
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,Male,1,No,2026-11-03,Referral,normal,0.0
1,1998,47.765164,61312.831291,649.277051,5.632826,9.0,3.742125,Hyderabad,consumer,Male,0,No,NaT,Website,follow-up needed,0.0
2,1998,38.016078,44199.671239,613.132775,4.683845,8.0,4.195157,Mumbai,consumer,Male,1,No,NaT,email,normal,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,3.742125,Chennai,enterprise,Male,0,No,2023-12-07,Website,normal,0.0
4,1998,38.016078,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-06-08,Referral,???,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1998,27.269512,79436.893353,633.974006,14.007477,6.0,3.556073,Bengaluru,consumer,M,0,No,NaT,email,normal,0.0
1996,1998,41.091685,39912.379911,701.720106,0.673289,8.0,2.963094,Pune,smb,Male,0,Yes,2024-11-08,Website,good,1.0
1997,1998,26.215767,24522.265446,647.799336,2.026485,12.0,3.079259,Hyderabad,smb.,F,1,No,NaT,Website,???,0.0
1998,1998,38.016078,84103.610558,649.277051,7.168156,5.0,3.579652,Hyderabad,smb,Male,0,Yes,NaT,email,ok,1.0
1999,1998,59.256095,53723.873924,576.739073,9.720663,6.0,1.100520,Pune,consumer,Male,1,No,NaT,???,good,0.0

In [133]:
for col in ["income_usd", "credit_score"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[col] = [val if (lower_bound <= val <= upper_bound) else np.nan for val in df[col]]

In [134]:
df[col].fillna(df[col].median())

0       660.562918
1       649.277051
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    649.277051
1999    576.739073
Name: credit_score, Length: 2000, dtype: float64

In [135]:
df.head()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,churn_flag_binary
0,1998,45.867417,28198.410334,660.562918,5.274076,5.0,3.382150,Pune,consumer,Male,1,No,2026-11-03,Referral,normal,0.0
1,1998,47.765164,61312.831291,649.277051,5.632826,9.0,3.742125,Hyderabad,consumer,Male,0,No,NaT,Website,follow-up needed,0.0
2,1998,38.016078,44199.671239,613.132775,4.683845,8.0,4.195157,Mumbai,consumer,Male,1,No,NaT,email,normal,0.0
3,1998,62.723578,56259.909611,720.236986,2.029634,4.0,3.742125,Chennai,enterprise,Male,0,No,2023-12-07,Website,normal,0.0
4,1998,38.016078,31238.641956,549.183252,2.648626,5.0,3.117326,Mumbai,enterprise,Male,1,No,2024-06-08,Referral,???,0.0

In [136]:
#30.Perform a final data-quality audit using Pandas and NumPy:
# • Check remaining missing values
# • Check duplicate rows
# • Check duplicate customer IDs
# • Check data types
# • Check numerical ranges
# • Check unique categorical values
# • Confirm the final dataset is ready for analysis/ML

df.isna().sum()

customer_id             0
age                     0
income_usd            161
credit_score          159
tenure_years            0
monthly_visits          0
satisfaction            0
city                    0
customer_segment        0
gender                  0
is_active               0
churn_flag              0
signup_date          1375
lead_source             0
notes_text              0
churn_flag_binary       0
dtype: int64

In [137]:
df.duplicated().sum()

np.int64(0)

In [139]:
if "customer_id" in df.columns:
    print(df["customer_id"].duplicated().sum())

1999

In [140]:
df.dtypes

customer_id                   int64
age                         float64
income_usd                  float64
credit_score                float64
tenure_years                float64
monthly_visits              float64
satisfaction                float64
city                         object
customer_segment             object
gender                       object
is_active                    object
churn_flag                   object
signup_date          datetime64[ns]
lead_source                  object
notes_text                   object
churn_flag_binary           float64
dtype: object

In [141]:
df.describe()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,signup_date,churn_flag_binary
count,2000.0,2000.000000,1839.000000,1841.000000,2000.000000,2000.000000,2000.000000,625,2000.000000
mean,1998.0,37.909271,55813.511699,651.182482,5.408540,6.393500,3.703481,2023-09-30 22:30:08.640000,0.223000
min,1998.0,18.000000,10198.638783,508.577038,0.073142,0.000000,1.000000,2021-01-01 00:00:00,0.000000
25%,1998.0,33.313792,41941.000000,624.256628,3.157410,5.000000,3.300636,2022-05-08 00:00:00,0.000000
50%,1998.0,38.016078,56124.711724,649.277051,4.683845,6.000000,3.742125,2023-09-08 00:00:00,0.000000
75%,1998.0,42.226192,64257.911526,682.806409,6.881265,7.000000,4.138932,2025-01-10 00:00:00,0.000000
max,1998.0,99.743573,114703.000000,796.248744,20.000000,80.000000,5.000000,2026-12-07 00:00:00,1.000000
std,0.0,10.134100,20526.174080,59.205722,3.361040,4.681412,0.742411,NaN,0.416362

In [144]:
for col in df.select_dtypes(include = ["object","category"]).columns:
    print(df[col].unique())

['Pune' 'Hyderabad' 'Mumbai' 'Chennai' 'Bengaluru' 'Kolkata' 'Delhi']
['consumer' 'enterprise' 'smb' 'smb.' 'unknown']
['Male' 'Female' 'M' 'F']
[1 0 '1' '0']
['No' 'Yes']
['Referral' 'Website' 'email' 'Google Ads' 'social' 'unknown' '???']
['normal' 'follow-up needed' '???' 'good customer' 'complaint!!!' 'ok'
 'VIP' 'urgent' 'good  ' 'late payment']

In [145]:
print("Final dataset is clean and ready for analysis/ML")

Final dataset is clean and ready for analysis/ML